// <auto-generated />

using System.Text;

namespace XenoAtom.Terminal.UI;

public static partial class NerdFont
{
    /// <summary>
    /// dev-aarch64.
    /// </summary>
    public static Rune DevAarch64 => new(0xE700);

    /// <summary>
    /// dev-adonisjs.
    /// </summary>
    public static Rune DevAdonisjs => new(0xE701);

    /// <summary>
    /// dev-aftereffects.
    /// </summary>
    public static Rune DevAftereffects => new(0xE705);

    /// <summary>
    /// dev-akka.
    /// </summary>
    public static Rune DevAkka => new(0xE708);

    /// <summary>
    /// dev-algolia.
    /// </summary>
    public static Rune DevAlgolia => new(0xE70A);

    /// <summary>
    /// dev-alpinejs.
    /// </summary>
    public static Rune DevAlpinejs => new(0xE713);

    /// <summary>
    /// dev-amazonwebservices.
    /// </summary>
    public static Rune DevAmazonwebservices => new(0xE7AD);

    /// <summary>
    /// dev-anaconda.
    /// </summary>
    public static Rune DevAnaconda => new(0xE715);

    /// <summary>
    /// dev-android.
    /// </summary>
    public static Rune DevAndroid => new(0xE70E);

    /// <summary>
    /// dev-androidstudio.
    /// </summary>
    public static Rune DevAndroidstudio => new(0xE71A);

    /// <summary>
    /// dev-angular.
    /// </summary>
    public static Rune DevAngular => new(0xE753);

    /// <summary>
    /// dev-angularjs.
    /// </summary>
    public static Rune DevAngularjs => new(0xE71C);

    /// <summary>
    /// dev-angularmaterial.
    /// </summary>
    public static Rune DevAngularmaterial => new(0xE720);

    /// <summary>
    /// dev-ansible.
    /// </summary>
    public static Rune DevAnsible => new(0xE723);

    /// <summary>
    /// dev-antdesign.
    /// </summary>
    public static Rune DevAntdesign => new(0xE72A);

    /// <summary>
    /// dev-apache.
    /// </summary>
    public static Rune DevApache => new(0xE72B);

    /// <summary>
    /// dev-apacheairflow.
    /// </summary>
    public static Rune DevApacheairflow => new(0xE72C);

    /// <summary>
    /// dev-apachekafka.
    /// </summary>
    public static Rune DevApachekafka => new(0xE72E);

    /// <summary>
    /// dev-apachespark.
    /// </summary>
    public static Rune DevApachespark => new(0xE72F);

    /// <summary>
    /// dev-apl.
    /// </summary>
    public static Rune DevApl => new(0xE730);

    /// <summary>
    /// dev-appcelerator.
    /// </summary>
    public static Rune DevAppcelerator => new(0xE7AB);

    /// <summary>
    /// dev-apple.
    /// </summary>
    public static Rune DevApple => new(0xE711);

    /// <summary>
    /// dev-appwrite.
    /// </summary>
    public static Rune DevAppwrite => new(0xE731);

    /// <summary>
    /// dev-archlinux.
    /// </summary>
    public static Rune DevArchlinux => new(0xE732);

    /// <summary>
    /// dev-arduino.
    /// </summary>
    public static Rune DevArduino => new(0xE733);

    /// <summary>
    /// dev-argocd.
    /// </summary>
    public static Rune DevArgocd => new(0xE734);

    /// <summary>
    /// dev-astro.
    /// </summary>
    public static Rune DevAstro => new(0xE735);

    /// <summary>
    /// dev-atom.
    /// </summary>
    public static Rune DevAtom => new(0xE764);

    /// <summary>
    /// dev-awk.
    /// </summary>
    public static Rune DevAwk => new(0xE741);

    /// <summary>
    /// dev-aws.
    /// </summary>
    public static Rune DevAws => new(0xE7AD);

    /// <summary>
    /// dev-axios.
    /// </summary>
    public static Rune DevAxios => new(0xE74F);

    /// <summary>
    /// dev-azure.
    /// </summary>
    public static Rune DevAzure => new(0xE754);

    /// <summary>
    /// dev-azuredevops.
    /// </summary>
    public static Rune DevAzuredevops => new(0xE756);

    /// <summary>
    /// dev-azuresqldatabase.
    /// </summary>
    public static Rune DevAzuresqldatabase => new(0xE75B);

    /// <summary>
    /// dev-babel.
    /// </summary>
    public static Rune DevBabel => new(0xE75D);

    /// <summary>
    /// dev-backbone.
    /// </summary>
    public static Rune DevBackbone => new(0xE752);

    /// <summary>
    /// dev-backbonejs.
    /// </summary>
    public static Rune DevBackbonejs => new(0xE752);

    /// <summary>
    /// dev-ballerina.
    /// </summary>
    public static Rune DevBallerina => new(0xE75E);

    /// <summary>
    /// dev-bamboo.
    /// </summary>
    public static Rune DevBamboo => new(0xE75F);

    /// <summary>
    /// dev-bash.
    /// </summary>
    public static Rune DevBash => new(0xE760);

    /// <summary>
    /// dev-beats.
    /// </summary>
    public static Rune DevBeats => new(0xE761);

    /// <summary>
    /// dev-behance.
    /// </summary>
    public static Rune DevBehance => new(0xE762);

    /// <summary>
    /// dev-bitbucket.
    /// </summary>
    public static Rune DevBitbucket => new(0xE703);

    /// <summary>
    /// dev-blazor.
    /// </summary>
    public static Rune DevBlazor => new(0xE765);

    /// <summary>
    /// dev-blender.
    /// </summary>
    public static Rune DevBlender => new(0xE766);

    /// <summary>
    /// dev-bootstrap.
    /// </summary>
    public static Rune DevBootstrap => new(0xE747);

    /// <summary>
    /// dev-bower.
    /// </summary>
    public static Rune DevBower => new(0xE74D);

    /// <summary>
    /// dev-browserstack.
    /// </summary>
    public static Rune DevBrowserstack => new(0xE76B);

    /// <summary>
    /// dev-bulma.
    /// </summary>
    public static Rune DevBulma => new(0xE76C);

    /// <summary>
    /// dev-bun.
    /// </summary>
    public static Rune DevBun => new(0xE76F);

    /// <summary>
    /// dev-c.
    /// </summary>
    public static Rune DevC => new(0xE771);

    /// <summary>
    /// dev-c_lang.
    /// </summary>
    public static Rune DevCLang => new(0xE771);

    /// <summary>
    /// dev-cairo.
    /// </summary>
    public static Rune DevCairo => new(0xE773);

    /// <summary>
    /// dev-cakephp.
    /// </summary>
    public static Rune DevCakephp => new(0xE77A);

    /// <summary>
    /// dev-canva.
    /// </summary>
    public static Rune DevCanva => new(0xE77C);

    /// <summary>
    /// dev-capacitor.
    /// </summary>
    public static Rune DevCapacitor => new(0xE785);

    /// <summary>
    /// dev-carbon.
    /// </summary>
    public static Rune DevCarbon => new(0xE788);

    /// <summary>
    /// dev-cassandra.
    /// </summary>
    public static Rune DevCassandra => new(0xE789);

    /// <summary>
    /// dev-centos.
    /// </summary>
    public static Rune DevCentos => new(0xE78A);

    /// <summary>
    /// dev-ceylon.
    /// </summary>
    public static Rune DevCeylon => new(0xE78B);

    /// <summary>
    /// dev-chrome.
    /// </summary>
    public static Rune DevChrome => new(0xE743);

    /// <summary>
    /// dev-circleci.
    /// </summary>
    public static Rune DevCircleci => new(0xE78C);

    /// <summary>
    /// dev-clarity.
    /// </summary>
    public static Rune DevClarity => new(0xE78D);

    /// <summary>
    /// dev-clion.
    /// </summary>
    public static Rune DevClion => new(0xE78E);

    /// <summary>
    /// dev-clojure.
    /// </summary>
    public static Rune DevClojure => new(0xE768);

    /// <summary>
    /// dev-clojure_alt.
    /// </summary>
    public static Rune DevClojureAlt => new(0xE76A);

    /// <summary>
    /// dev-clojurescript.
    /// </summary>
    public static Rune DevClojurescript => new(0xE790);

    /// <summary>
    /// dev-cloudflare.
    /// </summary>
    public static Rune DevCloudflare => new(0xE792);

    /// <summary>
    /// dev-cloudflareworkers.
    /// </summary>
    public static Rune DevCloudflareworkers => new(0xE793);

    /// <summary>
    /// dev-cmake.
    /// </summary>
    public static Rune DevCmake => new(0xE794);

    /// <summary>
    /// dev-codeac.
    /// </summary>
    public static Rune DevCodeac => new(0xE796);

    /// <summary>
    /// dev-codecov.
    /// </summary>
    public static Rune DevCodecov => new(0xE797);

    /// <summary>
    /// dev-codeigniter.
    /// </summary>
    public static Rune DevCodeigniter => new(0xE780);

    /// <summary>
    /// dev-codepen.
    /// </summary>
    public static Rune DevCodepen => new(0xE716);

    /// <summary>
    /// dev-coffeescript.
    /// </summary>
    public static Rune DevCoffeescript => new(0xE751);

    /// <summary>
    /// dev-composer.
    /// </summary>
    public static Rune DevComposer => new(0xE783);

    /// <summary>
    /// dev-confluence.
    /// </summary>
    public static Rune DevConfluence => new(0xE799);

    /// <summary>
    /// dev-consul.
    /// </summary>
    public static Rune DevConsul => new(0xE79A);

    /// <summary>
    /// dev-contao.
    /// </summary>
    public static Rune DevContao => new(0xE79B);

    /// <summary>
    /// dev-corejs.
    /// </summary>
    public static Rune DevCorejs => new(0xE79D);

    /// <summary>
    /// dev-cosmosdb.
    /// </summary>
    public static Rune DevCosmosdb => new(0xE79F);

    /// <summary>
    /// dev-couchbase.
    /// </summary>
    public static Rune DevCouchbase => new(0xE7A0);

    /// <summary>
    /// dev-couchdb.
    /// </summary>
    public static Rune DevCouchdb => new(0xE7A2);

    /// <summary>
    /// dev-cplusplus.
    /// </summary>
    public static Rune DevCplusplus => new(0xE7A3);

    /// <summary>
    /// dev-crystal.
    /// </summary>
    public static Rune DevCrystal => new(0xE7AC);

    /// <summary>
    /// dev-csharp.
    /// </summary>
    public static Rune DevCsharp => new(0xE7B2);

    /// <summary>
    /// dev-css3.
    /// </summary>
    public static Rune DevCss3 => new(0xE749);

    /// <summary>
    /// dev-css3_full.
    /// </summary>
    public static Rune DevCss3Full => new(0xE74A);

    /// <summary>
    /// dev-cucumber.
    /// </summary>
    public static Rune DevCucumber => new(0xE7B7);

    /// <summary>
    /// dev-cypressio.
    /// </summary>
    public static Rune DevCypressio => new(0xE7B9);

    /// <summary>
    /// dev-d3js.
    /// </summary>
    public static Rune DevD3js => new(0xE7BC);

    /// <summary>
    /// dev-dart.
    /// </summary>
    public static Rune DevDart => new(0xE798);

    /// <summary>
    /// dev-database.
    /// </summary>
    public static Rune DevDatabase => new(0xE706);

    /// <summary>
    /// dev-datagrip.
    /// </summary>
    public static Rune DevDatagrip => new(0xE7BD);

    /// <summary>
    /// dev-dataspell.
    /// </summary>
    public static Rune DevDataspell => new(0xE7BE);

    /// <summary>
    /// dev-dbeaver.
    /// </summary>
    public static Rune DevDbeaver => new(0xE7BF);

    /// <summary>
    /// dev-debian.
    /// </summary>
    public static Rune DevDebian => new(0xE77D);

    /// <summary>
    /// dev-denojs.
    /// </summary>
    public static Rune DevDenojs => new(0xE7C0);

    /// <summary>
    /// dev-devicon.
    /// </summary>
    public static Rune DevDevicon => new(0xE7C1);

    /// <summary>
    /// dev-digital_ocean.
    /// </summary>
    public static Rune DevDigitalOcean => new(0xE7AE);

    /// <summary>
    /// dev-digitalocean.
    /// </summary>
    public static Rune DevDigitalocean => new(0xE7AE);

    /// <summary>
    /// dev-discordjs.
    /// </summary>
    public static Rune DevDiscordjs => new(0xE7C2);

    /// <summary>
    /// dev-django.
    /// </summary>
    public static Rune DevDjango => new(0xE71D);

    /// <summary>
    /// dev-djangorest.
    /// </summary>
    public static Rune DevDjangorest => new(0xE7C3);

    /// <summary>
    /// dev-dlang.
    /// </summary>
    public static Rune DevDlang => new(0xE7AF);

    /// <summary>
    /// dev-docker.
    /// </summary>
    public static Rune DevDocker => new(0xE7B0);

    /// <summary>
    /// dev-doctrine.
    /// </summary>
    public static Rune DevDoctrine => new(0xE774);

    /// <summary>
    /// dev-dotnet.
    /// </summary>
    public static Rune DevDotnet => new(0xE77F);

    /// <summary>
    /// dev-dotnetcore.
    /// </summary>
    public static Rune DevDotnetcore => new(0xE7C6);

    /// <summary>
    /// dev-dreamweaver.
    /// </summary>
    public static Rune DevDreamweaver => new(0xE79C);

    /// <summary>
    /// dev-dropbox.
    /// </summary>
    public static Rune DevDropbox => new(0xE707);

    /// <summary>
    /// dev-dropwizard.
    /// </summary>
    public static Rune DevDropwizard => new(0xE7C7);

    /// <summary>
    /// dev-drupal.
    /// </summary>
    public static Rune DevDrupal => new(0xE742);

    /// <summary>
    /// dev-dynamodb.
    /// </summary>
    public static Rune DevDynamodb => new(0xE7C8);

    /// <summary>
    /// dev-eclipse.
    /// </summary>
    public static Rune DevEclipse => new(0xE79E);

    /// <summary>
    /// dev-ecto.
    /// </summary>
    public static Rune DevEcto => new(0xE7C9);

    /// <summary>
    /// dev-elasticsearch.
    /// </summary>
    public static Rune DevElasticsearch => new(0xE7CA);

    /// <summary>
    /// dev-electron.
    /// </summary>
    public static Rune DevElectron => new(0xE7CB);

    /// <summary>
    /// dev-eleventy.
    /// </summary>
    public static Rune DevEleventy => new(0xE7CC);

    /// <summary>
    /// dev-elixir.
    /// </summary>
    public static Rune DevElixir => new(0xE7CD);

    /// <summary>
    /// dev-elm.
    /// </summary>
    public static Rune DevElm => new(0xE7CE);

    /// <summary>
    /// dev-emacs.
    /// </summary>
    public static Rune DevEmacs => new(0xE7CF);

    /// <summary>
    /// dev-embeddedc.
    /// </summary>
    public static Rune DevEmbeddedc => new(0xE7D0);

    /// <summary>
    /// dev-ember.
    /// </summary>
    public static Rune DevEmber => new(0xE71B);

    /// <summary>
    /// dev-envoy.
    /// </summary>
    public static Rune DevEnvoy => new(0xE7D1);

    /// <summary>
    /// dev-erlang.
    /// </summary>
    public static Rune DevErlang => new(0xE7B1);

    /// <summary>
    /// dev-eslint.
    /// </summary>
    public static Rune DevEslint => new(0xE7D2);

    /// <summary>
    /// dev-express.
    /// </summary>
    public static Rune DevExpress => new(0xE7D3);

    /// <summary>
    /// dev-facebook.
    /// </summary>
    public static Rune DevFacebook => new(0xE7D4);

    /// <summary>
    /// dev-fastapi.
    /// </summary>
    public static Rune DevFastapi => new(0xE7D5);

    /// <summary>
    /// dev-fastify.
    /// </summary>
    public static Rune DevFastify => new(0xE7D6);

    /// <summary>
    /// dev-faunadb.
    /// </summary>
    public static Rune DevFaunadb => new(0xE7D7);

    /// <summary>
    /// dev-feathersjs.
    /// </summary>
    public static Rune DevFeathersjs => new(0xE7D8);

    /// <summary>
    /// dev-fedora.
    /// </summary>
    public static Rune DevFedora => new(0xE7D9);

    /// <summary>
    /// dev-figma.
    /// </summary>
    public static Rune DevFigma => new(0xE7DA);

    /// <summary>
    /// dev-filezilla.
    /// </summary>
    public static Rune DevFilezilla => new(0xE7DB);

    /// <summary>
    /// dev-firebase.
    /// </summary>
    public static Rune DevFirebase => new(0xE787);

    /// <summary>
    /// dev-firefox.
    /// </summary>
    public static Rune DevFirefox => new(0xE745);

    /// <summary>
    /// dev-flask.
    /// </summary>
    public static Rune DevFlask => new(0xE7DC);

    /// <summary>
    /// dev-flutter.
    /// </summary>
    public static Rune DevFlutter => new(0xE7DD);

    /// <summary>
    /// dev-fortran.
    /// </summary>
    public static Rune DevFortran => new(0xE7DE);

    /// <summary>
    /// dev-foundation.
    /// </summary>
    public static Rune DevFoundation => new(0xE7DF);

    /// <summary>
    /// dev-framermotion.
    /// </summary>
    public static Rune DevFramermotion => new(0xE7E0);

    /// <summary>
    /// dev-framework7.
    /// </summary>
    public static Rune DevFramework7 => new(0xE7E1);

    /// <summary>
    /// dev-fsharp.
    /// </summary>
    public static Rune DevFsharp => new(0xE7A7);

    /// <summary>
    /// dev-gatling.
    /// </summary>
    public static Rune DevGatling => new(0xE7E2);

    /// <summary>
    /// dev-gatsby.
    /// </summary>
    public static Rune DevGatsby => new(0xE7E3);

    /// <summary>
    /// dev-gazebo.
    /// </summary>
    public static Rune DevGazebo => new(0xE7E4);

    /// <summary>
    /// dev-gcc.
    /// </summary>
    public static Rune DevGcc => new(0xE7E5);

    /// <summary>
    /// dev-gentoo.
    /// </summary>
    public static Rune DevGentoo => new(0xE7E6);

    /// <summary>
    /// dev-ghost.
    /// </summary>
    public static Rune DevGhost => new(0xE71F);

    /// <summary>
    /// dev-ghost_small.
    /// </summary>
    public static Rune DevGhostSmall => new(0xE714);

    /// <summary>
    /// dev-gimp.
    /// </summary>
    public static Rune DevGimp => new(0xE7E7);

    /// <summary>
    /// dev-git.
    /// </summary>
    public static Rune DevGit => new(0xE702);

    /// <summary>
    /// dev-git_branch.
    /// </summary>
    public static Rune DevGitBranch => new(0xE725);

    /// <summary>
    /// dev-git_commit.
    /// </summary>
    public static Rune DevGitCommit => new(0xE729);

    /// <summary>
    /// dev-git_compare.
    /// </summary>
    public static Rune DevGitCompare => new(0xE728);

    /// <summary>
    /// dev-git_merge.
    /// </summary>
    public static Rune DevGitMerge => new(0xE727);

    /// <summary>
    /// dev-git_pull_request.
    /// </summary>
    public static Rune DevGitPullRequest => new(0xE726);

    /// <summary>
    /// dev-gitbook.
    /// </summary>
    public static Rune DevGitbook => new(0xE7E8);

    /// <summary>
    /// dev-github.
    /// </summary>
    public static Rune DevGithub => new(0xE709);

    /// <summary>
    /// dev-github_badge.
    /// </summary>
    public static Rune DevGithubBadge => new(0xE709);

    /// <summary>
    /// dev-github_full.
    /// </summary>
    public static Rune DevGithubFull => new(0xE717);

    /// <summary>
    /// dev-githubactions.
    /// </summary>
    public static Rune DevGithubactions => new(0xE7E9);

    /// <summary>
    /// dev-githubcodespaces.
    /// </summary>
    public static Rune DevGithubcodespaces => new(0xE7EA);

    /// <summary>
    /// dev-gitlab.
    /// </summary>
    public static Rune DevGitlab => new(0xE7EB);

    /// <summary>
    /// dev-gitpod.
    /// </summary>
    public static Rune DevGitpod => new(0xE7EC);

    /// <summary>
    /// dev-gitter.
    /// </summary>
    public static Rune DevGitter => new(0xE7ED);

    /// <summary>
    /// dev-gnu.
    /// </summary>
    public static Rune DevGnu => new(0xE779);

    /// <summary>
    /// dev-go.
    /// </summary>
    public static Rune DevGo => new(0xE724);

    /// <summary>
    /// dev-godot.
    /// </summary>
    public static Rune DevGodot => new(0xE7EE);

    /// <summary>
    /// dev-goland.
    /// </summary>
    public static Rune DevGoland => new(0xE7EF);

    /// <summary>
    /// dev-google.
    /// </summary>
    public static Rune DevGoogle => new(0xE7F0);

    /// <summary>
    /// dev-googlecloud.
    /// </summary>
    public static Rune DevGooglecloud => new(0xE7F1);

    /// <summary>
    /// dev-gradle.
    /// </summary>
    public static Rune DevGradle => new(0xE7F2);

    /// <summary>
    /// dev-grafana.
    /// </summary>
    public static Rune DevGrafana => new(0xE7F3);

    /// <summary>
    /// dev-grails.
    /// </summary>
    public static Rune DevGrails => new(0xE7B3);

    /// <summary>
    /// dev-graphql.
    /// </summary>
    public static Rune DevGraphql => new(0xE7F4);

    /// <summary>
    /// dev-groovy.
    /// </summary>
    public static Rune DevGroovy => new(0xE775);

    /// <summary>
    /// dev-grpc.
    /// </summary>
    public static Rune DevGrpc => new(0xE7F5);

    /// <summary>
    /// dev-grunt.
    /// </summary>
    public static Rune DevGrunt => new(0xE74C);

    /// <summary>
    /// dev-gulp.
    /// </summary>
    public static Rune DevGulp => new(0xE763);

    /// <summary>
    /// dev-hadoop.
    /// </summary>
    public static Rune DevHadoop => new(0xE7F6);

    /// <summary>
    /// dev-handlebars.
    /// </summary>
    public static Rune DevHandlebars => new(0xE7F7);

    /// <summary>
    /// dev-hardhat.
    /// </summary>
    public static Rune DevHardhat => new(0xE7F8);

    /// <summary>
    /// dev-harvester.
    /// </summary>
    public static Rune DevHarvester => new(0xE7F9);

    /// <summary>
    /// dev-haskell.
    /// </summary>
    public static Rune DevHaskell => new(0xE777);

    /// <summary>
    /// dev-haxe.
    /// </summary>
    public static Rune DevHaxe => new(0xE7FA);

    /// <summary>
    /// dev-helm.
    /// </summary>
    public static Rune DevHelm => new(0xE7FB);

    /// <summary>
    /// dev-heroku.
    /// </summary>
    public static Rune DevHeroku => new(0xE77B);

    /// <summary>
    /// dev-hibernate.
    /// </summary>
    public static Rune DevHibernate => new(0xE7FC);

    /// <summary>
    /// dev-homebrew.
    /// </summary>
    public static Rune DevHomebrew => new(0xE7FD);

    /// <summary>
    /// dev-html5.
    /// </summary>
    public static Rune DevHtml5 => new(0xE736);

    /// <summary>
    /// dev-hugo.
    /// </summary>
    public static Rune DevHugo => new(0xE7FE);

    /// <summary>
    /// dev-ie.
    /// </summary>
    public static Rune DevIe => new(0xE744);

    /// <summary>
    /// dev-ifttt.
    /// </summary>
    public static Rune DevIfttt => new(0xE7FF);

    /// <summary>
    /// dev-illustrator.
    /// </summary>
    public static Rune DevIllustrator => new(0xE7B4);

    /// <summary>
    /// dev-influxdb.
    /// </summary>
    public static Rune DevInfluxdb => new(0xE800);

    /// <summary>
    /// dev-inkscape.
    /// </summary>
    public static Rune DevInkscape => new(0xE801);

    /// <summary>
    /// dev-insomnia.
    /// </summary>
    public static Rune DevInsomnia => new(0xE802);

    /// <summary>
    /// dev-intellij.
    /// </summary>
    public static Rune DevIntellij => new(0xE7B5);

    /// <summary>
    /// dev-ionic.
    /// </summary>
    public static Rune DevIonic => new(0xE7A9);

    /// <summary>
    /// dev-jaegertracing.
    /// </summary>
    public static Rune DevJaegertracing => new(0xE803);

    /// <summary>
    /// dev-jamstack.
    /// </summary>
    public static Rune DevJamstack => new(0xE804);

    /// <summary>
    /// dev-jasmine.
    /// </summary>
    public static Rune DevJasmine => new(0xE805);

    /// <summary>
    /// dev-java.
    /// </summary>
    public static Rune DevJava => new(0xE738);

    /// <summary>
    /// dev-javascript.
    /// </summary>
    public static Rune DevJavascript => new(0xE781);

    /// <summary>
    /// dev-javascript_alt.
    /// </summary>
    public static Rune DevJavascriptAlt => new(0xE74E);

    /// <summary>
    /// dev-javascript_badge.
    /// </summary>
    public static Rune DevJavascriptBadge => new(0xE781);

    /// <summary>
    /// dev-jeet.
    /// </summary>
    public static Rune DevJeet => new(0xE806);

    /// <summary>
    /// dev-jekyll.
    /// </summary>
    public static Rune DevJekyll => new(0xE70D);

    /// <summary>
    /// dev-jekyll_small.
    /// </summary>
    public static Rune DevJekyllSmall => new(0xE70D);

    /// <summary>
    /// dev-jenkins.
    /// </summary>
    public static Rune DevJenkins => new(0xE767);

    /// <summary>
    /// dev-jest.
    /// </summary>
    public static Rune DevJest => new(0xE807);

    /// <summary>
    /// dev-jetbrains.
    /// </summary>
    public static Rune DevJetbrains => new(0xE808);

    /// <summary>
    /// dev-jetpackcompose.
    /// </summary>
    public static Rune DevJetpackcompose => new(0xE809);

    /// <summary>
    /// dev-jira.
    /// </summary>
    public static Rune DevJira => new(0xE75C);

    /// <summary>
    /// dev-jiraalign.
    /// </summary>
    public static Rune DevJiraalign => new(0xE80A);

    /// <summary>
    /// dev-jquery.
    /// </summary>
    public static Rune DevJquery => new(0xE750);

    /// <summary>
    /// dev-json.
    /// </summary>
    public static Rune DevJson => new(0xE80B);

    /// <summary>
    /// dev-jule.
    /// </summary>
    public static Rune DevJule => new(0xE80C);

    /// <summary>
    /// dev-julia.
    /// </summary>
    public static Rune DevJulia => new(0xE80D);

    /// <summary>
    /// dev-junit.
    /// </summary>
    public static Rune DevJunit => new(0xE80E);

    /// <summary>
    /// dev-jupyter.
    /// </summary>
    public static Rune DevJupyter => new(0xE80F);

    /// <summary>
    /// dev-k3os.
    /// </summary>
    public static Rune DevK3os => new(0xE810);

    /// <summary>
    /// dev-k3s.
    /// </summary>
    public static Rune DevK3s => new(0xE811);

    /// <summary>
    /// dev-k6.
    /// </summary>
    public static Rune DevK6 => new(0xE812);

    /// <summary>
    /// dev-kaggle.
    /// </summary>
    public static Rune DevKaggle => new(0xE813);

    /// <summary>
    /// dev-karatelabs.
    /// </summary>
    public static Rune DevKaratelabs => new(0xE814);

    /// <summary>
    /// dev-karma.
    /// </summary>
    public static Rune DevKarma => new(0xE815);

    /// <summary>
    /// dev-kdeneon.
    /// </summary>
    public static Rune DevKdeneon => new(0xE816);

    /// <summary>
    /// dev-keras.
    /// </summary>
    public static Rune DevKeras => new(0xE817);

    /// <summary>
    /// dev-kibana.
    /// </summary>
    public static Rune DevKibana => new(0xE818);

    /// <summary>
    /// dev-knexjs.
    /// </summary>
    public static Rune DevKnexjs => new(0xE819);

    /// <summary>
    /// dev-knockout.
    /// </summary>
    public static Rune DevKnockout => new(0xE81A);

    /// <summary>
    /// dev-kotlin.
    /// </summary>
    public static Rune DevKotlin => new(0xE81B);

    /// <summary>
    /// dev-krakenjs.
    /// </summary>
    public static Rune DevKrakenjs => new(0xE784);

    /// <summary>
    /// dev-krakenjs_badge.
    /// </summary>
    public static Rune DevKrakenjsBadge => new(0xE784);

    /// <summary>
    /// dev-ktor.
    /// </summary>
    public static Rune DevKtor => new(0xE81C);

    /// <summary>
    /// dev-kubernetes.
    /// </summary>
    public static Rune DevKubernetes => new(0xE81D);

    /// <summary>
    /// dev-labview.
    /// </summary>
    public static Rune DevLabview => new(0xE81E);

    /// <summary>
    /// dev-laravel.
    /// </summary>
    public static Rune DevLaravel => new(0xE73F);

    /// <summary>
    /// dev-latex.
    /// </summary>
    public static Rune DevLatex => new(0xE81F);

    /// <summary>
    /// dev-less.
    /// </summary>
    public static Rune DevLess => new(0xE758);

    /// <summary>
    /// dev-linkedin.
    /// </summary>
    public static Rune DevLinkedin => new(0xE820);

    /// <summary>
    /// dev-linux.
    /// </summary>
    public static Rune DevLinux => new(0xE712);

    /// <summary>
    /// dev-liquibase.
    /// </summary>
    public static Rune DevLiquibase => new(0xE821);

    /// <summary>
    /// dev-livewire.
    /// </summary>
    public static Rune DevLivewire => new(0xE822);

    /// <summary>
    /// dev-llvm.
    /// </summary>
    public static Rune DevLlvm => new(0xE823);

    /// <summary>
    /// dev-lodash.
    /// </summary>
    public static Rune DevLodash => new(0xE824);

    /// <summary>
    /// dev-logstash.
    /// </summary>
    public static Rune DevLogstash => new(0xE825);

    /// <summary>
    /// dev-lua.
    /// </summary>
    public static Rune DevLua => new(0xE826);

    /// <summary>
    /// dev-lumen.
    /// </summary>
    public static Rune DevLumen => new(0xE827);

    /// <summary>
    /// dev-magento.
    /// </summary>
    public static Rune DevMagento => new(0xE740);

    /// <summary>
    /// dev-mariadb.
    /// </summary>
    public static Rune DevMariadb => new(0xE828);

    /// <summary>
    /// dev-markdown.
    /// </summary>
    public static Rune DevMarkdown => new(0xE73E);

    /// <summary>
    /// dev-materializecss.
    /// </summary>
    public static Rune DevMaterializecss => new(0xE7B6);

    /// <summary>
    /// dev-materialui.
    /// </summary>
    public static Rune DevMaterialui => new(0xE829);

    /// <summary>
    /// dev-matlab.
    /// </summary>
    public static Rune DevMatlab => new(0xE82A);

    /// <summary>
    /// dev-matplotlib.
    /// </summary>
    public static Rune DevMatplotlib => new(0xE82B);

    /// <summary>
    /// dev-maven.
    /// </summary>
    public static Rune DevMaven => new(0xE82C);

    /// <summary>
    /// dev-maya.
    /// </summary>
    public static Rune DevMaya => new(0xE82D);

    /// <summary>
    /// dev-meteor.
    /// </summary>
    public static Rune DevMeteor => new(0xE7A5);

    /// <summary>
    /// dev-meteorfull.
    /// </summary>
    public static Rune DevMeteorfull => new(0xE7A6);

    /// <summary>
    /// dev-microsoftsqlserver.
    /// </summary>
    public static Rune DevMicrosoftsqlserver => new(0xE82E);

    /// <summary>
    /// dev-minitab.
    /// </summary>
    public static Rune DevMinitab => new(0xE82F);

    /// <summary>
    /// dev-mithril.
    /// </summary>
    public static Rune DevMithril => new(0xE830);

    /// <summary>
    /// dev-mobx.
    /// </summary>
    public static Rune DevMobx => new(0xE831);

    /// <summary>
    /// dev-mocha.
    /// </summary>
    public static Rune DevMocha => new(0xE832);

    /// <summary>
    /// dev-modx.
    /// </summary>
    public static Rune DevModx => new(0xE833);

    /// <summary>
    /// dev-moleculer.
    /// </summary>
    public static Rune DevMoleculer => new(0xE834);

    /// <summary>
    /// dev-mongodb.
    /// </summary>
    public static Rune DevMongodb => new(0xE7A4);

    /// <summary>
    /// dev-mongoose.
    /// </summary>
    public static Rune DevMongoose => new(0xE835);

    /// <summary>
    /// dev-moodle.
    /// </summary>
    public static Rune DevMoodle => new(0xE836);

    /// <summary>
    /// dev-mootools_badge.
    /// </summary>
    public static Rune DevMootoolsBadge => new(0xE78F);

    /// <summary>
    /// dev-mozilla.
    /// </summary>
    public static Rune DevMozilla => new(0xE786);

    /// <summary>
    /// dev-msdos.
    /// </summary>
    public static Rune DevMsdos => new(0xE837);

    /// <summary>
    /// dev-mysql.
    /// </summary>
    public static Rune DevMysql => new(0xE704);

    /// <summary>
    /// dev-nano.
    /// </summary>
    public static Rune DevNano => new(0xE838);

    /// <summary>
    /// dev-neo4j.
    /// </summary>
    public static Rune DevNeo4j => new(0xE839);

    /// <summary>
    /// dev-neovim.
    /// </summary>
    public static Rune DevNeovim => new(0xE83A);

    /// <summary>
    /// dev-nestjs.
    /// </summary>
    public static Rune DevNestjs => new(0xE83B);

    /// <summary>
    /// dev-netlify.
    /// </summary>
    public static Rune DevNetlify => new(0xE83C);

    /// <summary>
    /// dev-networkx.
    /// </summary>
    public static Rune DevNetworkx => new(0xE83D);

    /// <summary>
    /// dev-nextjs.
    /// </summary>
    public static Rune DevNextjs => new(0xE83E);

    /// <summary>
    /// dev-nginx.
    /// </summary>
    public static Rune DevNginx => new(0xE776);

    /// <summary>
    /// dev-ngrx.
    /// </summary>
    public static Rune DevNgrx => new(0xE83F);

    /// <summary>
    /// dev-nhibernate.
    /// </summary>
    public static Rune DevNhibernate => new(0xE840);

    /// <summary>
    /// dev-nim.
    /// </summary>
    public static Rune DevNim => new(0xE841);

    /// <summary>
    /// dev-nimble.
    /// </summary>
    public static Rune DevNimble => new(0xE842);

    /// <summary>
    /// dev-nixos.
    /// </summary>
    public static Rune DevNixos => new(0xE843);

    /// <summary>
    /// dev-nodejs.
    /// </summary>
    public static Rune DevNodejs => new(0xE719);

    /// <summary>
    /// dev-nodejs_small.
    /// </summary>
    public static Rune DevNodejsSmall => new(0xE718);

    /// <summary>
    /// dev-nodemon.
    /// </summary>
    public static Rune DevNodemon => new(0xE844);

    /// <summary>
    /// dev-nodewebkit.
    /// </summary>
    public static Rune DevNodewebkit => new(0xE845);

    /// <summary>
    /// dev-nomad.
    /// </summary>
    public static Rune DevNomad => new(0xE846);

    /// <summary>
    /// dev-norg.
    /// </summary>
    public static Rune DevNorg => new(0xE847);

    /// <summary>
    /// dev-notion.
    /// </summary>
    public static Rune DevNotion => new(0xE848);

    /// <summary>
    /// dev-npm.
    /// </summary>
    public static Rune DevNpm => new(0xE71E);

    /// <summary>
    /// dev-nuget.
    /// </summary>
    public static Rune DevNuget => new(0xE849);

    /// <summary>
    /// dev-numpy.
    /// </summary>
    public static Rune DevNumpy => new(0xE84A);

    /// <summary>
    /// dev-nuxtjs.
    /// </summary>
    public static Rune DevNuxtjs => new(0xE84B);

    /// <summary>
    /// dev-oauth.
    /// </summary>
    public static Rune DevOauth => new(0xE84C);

    /// <summary>
    /// dev-objectivec.
    /// </summary>
    public static Rune DevObjectivec => new(0xE84D);

    /// <summary>
    /// dev-ocaml.
    /// </summary>
    public static Rune DevOcaml => new(0xE84E);

    /// <summary>
    /// dev-ohmyzsh.
    /// </summary>
    public static Rune DevOhmyzsh => new(0xE84F);

    /// <summary>
    /// dev-okta.
    /// </summary>
    public static Rune DevOkta => new(0xE850);

    /// <summary>
    /// dev-openal.
    /// </summary>
    public static Rune DevOpenal => new(0xE851);

    /// <summary>
    /// dev-openapi.
    /// </summary>
    public static Rune DevOpenapi => new(0xE852);

    /// <summary>
    /// dev-opencl.
    /// </summary>
    public static Rune DevOpencl => new(0xE853);

    /// <summary>
    /// dev-opencv.
    /// </summary>
    public static Rune DevOpencv => new(0xE854);

    /// <summary>
    /// dev-opengl.
    /// </summary>
    public static Rune DevOpengl => new(0xE855);

    /// <summary>
    /// dev-openstack.
    /// </summary>
    public static Rune DevOpenstack => new(0xE856);

    /// <summary>
    /// dev-opensuse.
    /// </summary>
    public static Rune DevOpensuse => new(0xE857);

    /// <summary>
    /// dev-opentelemetry.
    /// </summary>
    public static Rune DevOpentelemetry => new(0xE858);

    /// <summary>
    /// dev-opera.
    /// </summary>
    public static Rune DevOpera => new(0xE746);

    /// <summary>
    /// dev-oracle.
    /// </summary>
    public static Rune DevOracle => new(0xE859);

    /// <summary>
    /// dev-ory.
    /// </summary>
    public static Rune DevOry => new(0xE85A);

    /// <summary>
    /// dev-p5js.
    /// </summary>
    public static Rune DevP5js => new(0xE85B);

    /// <summary>
    /// dev-packer.
    /// </summary>
    public static Rune DevPacker => new(0xE85C);

    /// <summary>
    /// dev-pandas.
    /// </summary>
    public static Rune DevPandas => new(0xE85D);

    /// <summary>
    /// dev-perl.
    /// </summary>
    public static Rune DevPerl => new(0xE769);

    /// <summary>
    /// dev-pfsense.
    /// </summary>
    public static Rune DevPfsense => new(0xE85E);

    /// <summary>
    /// dev-phalcon.
    /// </summary>
    public static Rune DevPhalcon => new(0xE85F);

    /// <summary>
    /// dev-phoenix.
    /// </summary>
    public static Rune DevPhoenix => new(0xE860);

    /// <summary>
    /// dev-photonengine.
    /// </summary>
    public static Rune DevPhotonengine => new(0xE861);

    /// <summary>
    /// dev-photoshop.
    /// </summary>
    public static Rune DevPhotoshop => new(0xE7B8);

    /// <summary>
    /// dev-php.
    /// </summary>
    public static Rune DevPhp => new(0xE73D);

    /// <summary>
    /// dev-phpstorm.
    /// </summary>
    public static Rune DevPhpstorm => new(0xE862);

    /// <summary>
    /// dev-playwright.
    /// </summary>
    public static Rune DevPlaywright => new(0xE863);

    /// <summary>
    /// dev-plotly.
    /// </summary>
    public static Rune DevPlotly => new(0xE864);

    /// <summary>
    /// dev-pnpm.
    /// </summary>
    public static Rune DevPnpm => new(0xE865);

    /// <summary>
    /// dev-podman.
    /// </summary>
    public static Rune DevPodman => new(0xE866);

    /// <summary>
    /// dev-poetry.
    /// </summary>
    public static Rune DevPoetry => new(0xE867);

    /// <summary>
    /// dev-polygon.
    /// </summary>
    public static Rune DevPolygon => new(0xE868);

    /// <summary>
    /// dev-portainer.
    /// </summary>
    public static Rune DevPortainer => new(0xE869);

    /// <summary>
    /// dev-postcss.
    /// </summary>
    public static Rune DevPostcss => new(0xE86A);

    /// <summary>
    /// dev-postgresql.
    /// </summary>
    public static Rune DevPostgresql => new(0xE76E);

    /// <summary>
    /// dev-postman.
    /// </summary>
    public static Rune DevPostman => new(0xE86B);

    /// <summary>
    /// dev-powershell.
    /// </summary>
    public static Rune DevPowershell => new(0xE86C);

    /// <summary>
    /// dev-premierepro.
    /// </summary>
    public static Rune DevPremierepro => new(0xE86D);

    /// <summary>
    /// dev-prisma.
    /// </summary>
    public static Rune DevPrisma => new(0xE86E);

    /// <summary>
    /// dev-processing.
    /// </summary>
    public static Rune DevProcessing => new(0xE86F);

    /// <summary>
    /// dev-prolog.
    /// </summary>
    public static Rune DevProlog => new(0xE7A1);

    /// <summary>
    /// dev-prometheus.
    /// </summary>
    public static Rune DevPrometheus => new(0xE870);

    /// <summary>
    /// dev-protractor.
    /// </summary>
    public static Rune DevProtractor => new(0xE871);

    /// <summary>
    /// dev-pulsar.
    /// </summary>
    public static Rune DevPulsar => new(0xE872);

    /// <summary>
    /// dev-pulumi.
    /// </summary>
    public static Rune DevPulumi => new(0xE873);

    /// <summary>
    /// dev-puppeteer.
    /// </summary>
    public static Rune DevPuppeteer => new(0xE874);

    /// <summary>
    /// dev-purescript.
    /// </summary>
    public static Rune DevPurescript => new(0xE875);

    /// <summary>
    /// dev-putty.
    /// </summary>
    public static Rune DevPutty => new(0xE876);

    /// <summary>
    /// dev-pycharm.
    /// </summary>
    public static Rune DevPycharm => new(0xE877);

    /// <summary>
    /// dev-pypi.
    /// </summary>
    public static Rune DevPypi => new(0xE878);

    /// <summary>
    /// dev-pyscript.
    /// </summary>
    public static Rune DevPyscript => new(0xE879);

    /// <summary>
    /// dev-pytest.
    /// </summary>
    public static Rune DevPytest => new(0xE87A);

    /// <summary>
    /// dev-python.
    /// </summary>
    public static Rune DevPython => new(0xE73C);

    /// <summary>
    /// dev-pytorch.
    /// </summary>
    public static Rune DevPytorch => new(0xE87B);

    /// <summary>
    /// dev-qodana.
    /// </summary>
    public static Rune DevQodana => new(0xE87C);

    /// <summary>
    /// dev-qt.
    /// </summary>
    public static Rune DevQt => new(0xE87D);

    /// <summary>
    /// dev-quarkus.
    /// </summary>
    public static Rune DevQuarkus => new(0xE87E);

    /// <summary>
    /// dev-quasar.
    /// </summary>
    public static Rune DevQuasar => new(0xE87F);

    /// <summary>
    /// dev-qwik.
    /// </summary>
    public static Rune DevQwik => new(0xE880);

    /// <summary>
    /// dev-r.
    /// </summary>
    public static Rune DevR => new(0xE881);

    /// <summary>
    /// dev-rabbitmq.
    /// </summary>
    public static Rune DevRabbitmq => new(0xE882);

    /// <summary>
    /// dev-rails.
    /// </summary>
    public static Rune DevRails => new(0xE73B);

    /// <summary>
    /// dev-railway.
    /// </summary>
    public static Rune DevRailway => new(0xE883);

    /// <summary>
    /// dev-rancher.
    /// </summary>
    public static Rune DevRancher => new(0xE884);

    /// <summary>
    /// dev-raspberry_pi.
    /// </summary>
    public static Rune DevRaspberryPi => new(0xE722);

    /// <summary>
    /// dev-reach.
    /// </summary>
    public static Rune DevReach => new(0xE885);

    /// <summary>
    /// dev-react.
    /// </summary>
    public static Rune DevReact => new(0xE7BA);

    /// <summary>
    /// dev-reactbootstrap.
    /// </summary>
    public static Rune DevReactbootstrap => new(0xE886);

    /// <summary>
    /// dev-reactnavigation.
    /// </summary>
    public static Rune DevReactnavigation => new(0xE887);

    /// <summary>
    /// dev-reactrouter.
    /// </summary>
    public static Rune DevReactrouter => new(0xE888);

    /// <summary>
    /// dev-readthedocs.
    /// </summary>
    public static Rune DevReadthedocs => new(0xE889);

    /// <summary>
    /// dev-realm.
    /// </summary>
    public static Rune DevRealm => new(0xE88A);

    /// <summary>
    /// dev-rect.
    /// </summary>
    public static Rune DevRect => new(0xE88B);

    /// <summary>
    /// dev-redhat.
    /// </summary>
    public static Rune DevRedhat => new(0xE7BB);

    /// <summary>
    /// dev-redis.
    /// </summary>
    public static Rune DevRedis => new(0xE76D);

    /// <summary>
    /// dev-redux.
    /// </summary>
    public static Rune DevRedux => new(0xE88C);

    /// <summary>
    /// dev-renpy.
    /// </summary>
    public static Rune DevRenpy => new(0xE88D);

    /// <summary>
    /// dev-replit.
    /// </summary>
    public static Rune DevReplit => new(0xE88E);

    /// <summary>
    /// dev-requirejs.
    /// </summary>
    public static Rune DevRequirejs => new(0xE770);

    /// <summary>
    /// dev-rider.
    /// </summary>
    public static Rune DevRider => new(0xE88F);

    /// <summary>
    /// dev-rocksdb.
    /// </summary>
    public static Rune DevRocksdb => new(0xE890);

    /// <summary>
    /// dev-rockylinux.
    /// </summary>
    public static Rune DevRockylinux => new(0xE891);

    /// <summary>
    /// dev-rollup.
    /// </summary>
    public static Rune DevRollup => new(0xE892);

    /// <summary>
    /// dev-ros.
    /// </summary>
    public static Rune DevRos => new(0xE893);

    /// <summary>
    /// dev-rspec.
    /// </summary>
    public static Rune DevRspec => new(0xE894);

    /// <summary>
    /// dev-rstudio.
    /// </summary>
    public static Rune DevRstudio => new(0xE895);

    /// <summary>
    /// dev-ruby.
    /// </summary>
    public static Rune DevRuby => new(0xE739);

    /// <summary>
    /// dev-ruby_on_rails.
    /// </summary>
    public static Rune DevRubyOnRails => new(0xE73B);

    /// <summary>
    /// dev-ruby_rough.
    /// </summary>
    public static Rune DevRubyRough => new(0xE791);

    /// <summary>
    /// dev-rubymine.
    /// </summary>
    public static Rune DevRubymine => new(0xE896);

    /// <summary>
    /// dev-rust.
    /// </summary>
    public static Rune DevRust => new(0xE7A8);

    /// <summary>
    /// dev-rxjs.
    /// </summary>
    public static Rune DevRxjs => new(0xE897);

    /// <summary>
    /// dev-safari.
    /// </summary>
    public static Rune DevSafari => new(0xE748);

    /// <summary>
    /// dev-salesforce.
    /// </summary>
    public static Rune DevSalesforce => new(0xE898);

    /// <summary>
    /// dev-sanity.
    /// </summary>
    public static Rune DevSanity => new(0xE899);

    /// <summary>
    /// dev-sass.
    /// </summary>
    public static Rune DevSass => new(0xE74B);

    /// <summary>
    /// dev-scala.
    /// </summary>
    public static Rune DevScala => new(0xE737);

    /// <summary>
    /// dev-scalingo.
    /// </summary>
    public static Rune DevScalingo => new(0xE89A);

    /// <summary>
    /// dev-scikitlearn.
    /// </summary>
    public static Rune DevScikitlearn => new(0xE89B);

    /// <summary>
    /// dev-sdl.
    /// </summary>
    public static Rune DevSdl => new(0xE89C);

    /// <summary>
    /// dev-selenium.
    /// </summary>
    public static Rune DevSelenium => new(0xE89D);

    /// <summary>
    /// dev-sema.
    /// </summary>
    public static Rune DevSema => new(0xE89E);

    /// <summary>
    /// dev-sentry.
    /// </summary>
    public static Rune DevSentry => new(0xE89F);

    /// <summary>
    /// dev-sequelize.
    /// </summary>
    public static Rune DevSequelize => new(0xE8A0);

    /// <summary>
    /// dev-shopware.
    /// </summary>
    public static Rune DevShopware => new(0xE8A1);

    /// <summary>
    /// dev-shotgrid.
    /// </summary>
    public static Rune DevShotgrid => new(0xE8A2);

    /// <summary>
    /// dev-sketch.
    /// </summary>
    public static Rune DevSketch => new(0xE8A3);

    /// <summary>
    /// dev-slack.
    /// </summary>
    public static Rune DevSlack => new(0xE8A4);

    /// <summary>
    /// dev-smashing_magazine.
    /// </summary>
    public static Rune DevSmashingMagazine => new(0xE72D);

    /// <summary>
    /// dev-socketio.
    /// </summary>
    public static Rune DevSocketio => new(0xE8A5);

    /// <summary>
    /// dev-solidity.
    /// </summary>
    public static Rune DevSolidity => new(0xE8A6);

    /// <summary>
    /// dev-solidjs.
    /// </summary>
    public static Rune DevSolidjs => new(0xE8A7);

    /// <summary>
    /// dev-sonarqube.
    /// </summary>
    public static Rune DevSonarqube => new(0xE8A8);

    /// <summary>
    /// dev-sourcetree.
    /// </summary>
    public static Rune DevSourcetree => new(0xE8A9);

    /// <summary>
    /// dev-spack.
    /// </summary>
    public static Rune DevSpack => new(0xE8AA);

    /// <summary>
    /// dev-splunk.
    /// </summary>
    public static Rune DevSplunk => new(0xE8AB);

    /// <summary>
    /// dev-spring.
    /// </summary>
    public static Rune DevSpring => new(0xE8AC);

    /// <summary>
    /// dev-spss.
    /// </summary>
    public static Rune DevSpss => new(0xE8AD);

    /// <summary>
    /// dev-spyder.
    /// </summary>
    public static Rune DevSpyder => new(0xE8AE);

    /// <summary>
    /// dev-sqlalchemy.
    /// </summary>
    public static Rune DevSqlalchemy => new(0xE8AF);

    /// <summary>
    /// dev-sqldeveloper.
    /// </summary>
    public static Rune DevSqldeveloper => new(0xE8B0);

    /// <summary>
    /// dev-sqlite.
    /// </summary>
    public static Rune DevSqlite => new(0xE7C4);

    /// <summary>
    /// dev-ssh.
    /// </summary>
    public static Rune DevSsh => new(0xE8B1);

    /// <summary>
    /// dev-stackoverflow.
    /// </summary>
    public static Rune DevStackoverflow => new(0xE710);

    /// <summary>
    /// dev-stata.
    /// </summary>
    public static Rune DevStata => new(0xE8B2);

    /// <summary>
    /// dev-storybook.
    /// </summary>
    public static Rune DevStorybook => new(0xE8B3);

    /// <summary>
    /// dev-streamlit.
    /// </summary>
    public static Rune DevStreamlit => new(0xE8B4);

    /// <summary>
    /// dev-stylus.
    /// </summary>
    public static Rune DevStylus => new(0xE759);

    /// <summary>
    /// dev-sublime.
    /// </summary>
    public static Rune DevSublime => new(0xE7AA);

    /// <summary>
    /// dev-subversion.
    /// </summary>
    public static Rune DevSubversion => new(0xE8B5);

    /// <summary>
    /// dev-supabase.
    /// </summary>
    public static Rune DevSupabase => new(0xE8B6);

    /// <summary>
    /// dev-svelte.
    /// </summary>
    public static Rune DevSvelte => new(0xE8B7);

    /// <summary>
    /// dev-swagger.
    /// </summary>
    public static Rune DevSwagger => new(0xE8B8);

    /// <summary>
    /// dev-swift.
    /// </summary>
    public static Rune DevSwift => new(0xE755);

    /// <summary>
    /// dev-swiper.
    /// </summary>
    public static Rune DevSwiper => new(0xE8B9);

    /// <summary>
    /// dev-symfony.
    /// </summary>
    public static Rune DevSymfony => new(0xE757);

    /// <summary>
    /// dev-symfony_badge.
    /// </summary>
    public static Rune DevSymfonyBadge => new(0xE757);

    /// <summary>
    /// dev-tailwindcss.
    /// </summary>
    public static Rune DevTailwindcss => new(0xE8BA);

    /// <summary>
    /// dev-tauri.
    /// </summary>
    public static Rune DevTauri => new(0xE8BB);

    /// <summary>
    /// dev-tensorflow.
    /// </summary>
    public static Rune DevTensorflow => new(0xE8BC);

    /// <summary>
    /// dev-terminal.
    /// </summary>
    public static Rune DevTerminal => new(0xE795);

    /// <summary>
    /// dev-terraform.
    /// </summary>
    public static Rune DevTerraform => new(0xE8BD);

    /// <summary>
    /// dev-tex.
    /// </summary>
    public static Rune DevTex => new(0xE8BE);

    /// <summary>
    /// dev-thealgorithms.
    /// </summary>
    public static Rune DevThealgorithms => new(0xE8BF);

    /// <summary>
    /// dev-threedsmax.
    /// </summary>
    public static Rune DevThreedsmax => new(0xE8C0);

    /// <summary>
    /// dev-threejs.
    /// </summary>
    public static Rune DevThreejs => new(0xE8C1);

    /// <summary>
    /// dev-titaniumsdk.
    /// </summary>
    public static Rune DevTitaniumsdk => new(0xE8C2);

    /// <summary>
    /// dev-tomcat.
    /// </summary>
    public static Rune DevTomcat => new(0xE8C3);

    /// <summary>
    /// dev-tortoisegit.
    /// </summary>
    public static Rune DevTortoisegit => new(0xE8C4);

    /// <summary>
    /// dev-towergit.
    /// </summary>
    public static Rune DevTowergit => new(0xE8C5);

    /// <summary>
    /// dev-traefikmesh.
    /// </summary>
    public static Rune DevTraefikmesh => new(0xE8C6);

    /// <summary>
    /// dev-traefikproxy.
    /// </summary>
    public static Rune DevTraefikproxy => new(0xE8C7);

    /// <summary>
    /// dev-travis.
    /// </summary>
    public static Rune DevTravis => new(0xE77E);

    /// <summary>
    /// dev-trello.
    /// </summary>
    public static Rune DevTrello => new(0xE75A);

    /// <summary>
    /// dev-trpc.
    /// </summary>
    public static Rune DevTrpc => new(0xE8C8);

    /// <summary>
    /// dev-twitter.
    /// </summary>
    public static Rune DevTwitter => new(0xE8C9);

    /// <summary>
    /// dev-typescript.
    /// </summary>
    public static Rune DevTypescript => new(0xE8CA);

    /// <summary>
    /// dev-typo3.
    /// </summary>
    public static Rune DevTypo3 => new(0xE772);

    /// <summary>
    /// dev-ubuntu.
    /// </summary>
    public static Rune DevUbuntu => new(0xE73A);

    /// <summary>
    /// dev-uml.
    /// </summary>
    public static Rune DevUml => new(0xE8CB);

    /// <summary>
    /// dev-unifiedmodelinglanguage.
    /// </summary>
    public static Rune DevUnifiedmodelinglanguage => new(0xE8CB);

    /// <summary>
    /// dev-unity.
    /// </summary>
    public static Rune DevUnity => new(0xE721);

    /// <summary>
    /// dev-unity_small.
    /// </summary>
    public static Rune DevUnitySmall => new(0xE721);

    /// <summary>
    /// dev-unix.
    /// </summary>
    public static Rune DevUnix => new(0xE8CC);

    /// <summary>
    /// dev-unrealengine.
    /// </summary>
    public static Rune DevUnrealengine => new(0xE8CD);

    /// <summary>
    /// dev-uwsgi.
    /// </summary>
    public static Rune DevUwsgi => new(0xE8CE);

    /// <summary>
    /// dev-v8.
    /// </summary>
    public static Rune DevV8 => new(0xE8CF);

    /// <summary>
    /// dev-vagrant.
    /// </summary>
    public static Rune DevVagrant => new(0xE8D0);

    /// <summary>
    /// dev-vala.
    /// </summary>
    public static Rune DevVala => new(0xE8D1);

    /// <summary>
    /// dev-vault.
    /// </summary>
    public static Rune DevVault => new(0xE8D2);

    /// <summary>
    /// dev-vercel.
    /// </summary>
    public static Rune DevVercel => new(0xE8D3);

    /// <summary>
    /// dev-vertx.
    /// </summary>
    public static Rune DevVertx => new(0xE8D4);

    /// <summary>
    /// dev-vim.
    /// </summary>
    public static Rune DevVim => new(0xE7C5);

    /// <summary>
    /// dev-visualbasic.
    /// </summary>
    public static Rune DevVisualbasic => new(0xE8D5);

    /// <summary>
    /// dev-visualstudio.
    /// </summary>
    public static Rune DevVisualstudio => new(0xE70C);

    /// <summary>
    /// dev-vite.
    /// </summary>
    public static Rune DevVite => new(0xE8D6);

    /// <summary>
    /// dev-vitejs.
    /// </summary>
    public static Rune DevVitejs => new(0xE8D7);

    /// <summary>
    /// dev-vitess.
    /// </summary>
    public static Rune DevVitess => new(0xE8D8);

    /// <summary>
    /// dev-vitest.
    /// </summary>
    public static Rune DevVitest => new(0xE8D9);

    /// <summary>
    /// dev-vscode.
    /// </summary>
    public static Rune DevVscode => new(0xE8DA);

    /// <summary>
    /// dev-vsphere.
    /// </summary>
    public static Rune DevVsphere => new(0xE8DB);

    /// <summary>
    /// dev-vuejs.
    /// </summary>
    public static Rune DevVuejs => new(0xE8DC);

    /// <summary>
    /// dev-vuestorefront.
    /// </summary>
    public static Rune DevVuestorefront => new(0xE8DD);

    /// <summary>
    /// dev-vuetify.
    /// </summary>
    public static Rune DevVuetify => new(0xE8DE);

    /// <summary>
    /// dev-vyper.
    /// </summary>
    public static Rune DevVyper => new(0xE8DF);

    /// <summary>
    /// dev-wasm.
    /// </summary>
    public static Rune DevWasm => new(0xE8E0);

    /// <summary>
    /// dev-webflow.
    /// </summary>
    public static Rune DevWebflow => new(0xE8E1);

    /// <summary>
    /// dev-weblate.
    /// </summary>
    public static Rune DevWeblate => new(0xE8E2);

    /// <summary>
    /// dev-webpack.
    /// </summary>
    public static Rune DevWebpack => new(0xE8E3);

    /// <summary>
    /// dev-webstorm.
    /// </summary>
    public static Rune DevWebstorm => new(0xE8E4);

    /// <summary>
    /// dev-windows.
    /// </summary>
    public static Rune DevWindows => new(0xE70F);

    /// <summary>
    /// dev-windows11.
    /// </summary>
    public static Rune DevWindows11 => new(0xE8E5);

    /// <summary>
    /// dev-woocommerce.
    /// </summary>
    public static Rune DevWoocommerce => new(0xE8E6);

    /// <summary>
    /// dev-wordpress.
    /// </summary>
    public static Rune DevWordpress => new(0xE70B);

    /// <summary>
    /// dev-xamarin.
    /// </summary>
    public static Rune DevXamarin => new(0xE8E7);

    /// <summary>
    /// dev-xcode.
    /// </summary>
    public static Rune DevXcode => new(0xE8E8);

    /// <summary>
    /// dev-xd.
    /// </summary>
    public static Rune DevXd => new(0xE8E9);

    /// <summary>
    /// dev-xml.
    /// </summary>
    public static Rune DevXml => new(0xE8EA);

    /// <summary>
    /// dev-yaml.
    /// </summary>
    public static Rune DevYaml => new(0xE8EB);

    /// <summary>
    /// dev-yarn.
    /// </summary>
    public static Rune DevYarn => new(0xE8EC);

    /// <summary>
    /// dev-yii.
    /// </summary>
    public static Rune DevYii => new(0xE782);

    /// <summary>
    /// dev-yugabytedb.
    /// </summary>
    public static Rune DevYugabytedb => new(0xE8ED);

    /// <summary>
    /// dev-yunohost.
    /// </summary>
    public static Rune DevYunohost => new(0xE8EE);

    /// <summary>
    /// dev-zend.
    /// </summary>
    public static Rune DevZend => new(0xE778);

    /// <summary>
    /// dev-zig.
    /// </summary>
    public static Rune DevZig => new(0xE8EF);

}
