// <auto-generated />

using System.Text;

namespace XenoAtom.Terminal.UI;

public static partial class NerdFont
{
    /// <summary>
    /// seti-apple.
    /// </summary>
    public static Rune SetiApple => new(0xE635);

    /// <summary>
    /// seti-argdown.
    /// </summary>
    public static Rune SetiArgdown => new(0xE636);

    /// <summary>
    /// seti-asm.
    /// </summary>
    public static Rune SetiAsm => new(0xE637);

    /// <summary>
    /// seti-audio.
    /// </summary>
    public static Rune SetiAudio => new(0xE638);

    /// <summary>
    /// seti-babel.
    /// </summary>
    public static Rune SetiBabel => new(0xE639);

    /// <summary>
    /// seti-bazel.
    /// </summary>
    public static Rune SetiBazel => new(0xE63A);

    /// <summary>
    /// seti-bicep.
    /// </summary>
    public static Rune SetiBicep => new(0xE63B);

    /// <summary>
    /// seti-bower.
    /// </summary>
    public static Rune SetiBower => new(0xE61A);

    /// <summary>
    /// seti-bsl.
    /// </summary>
    public static Rune SetiBsl => new(0xE63C);

    /// <summary>
    /// seti-c.
    /// </summary>
    public static Rune SetiC => new(0xE649);

    /// <summary>
    /// seti-c_sharp.
    /// </summary>
    public static Rune SetiCSharp => new(0xE648);

    /// <summary>
    /// seti-cake.
    /// </summary>
    public static Rune SetiCake => new(0xE63E);

    /// <summary>
    /// seti-cake_php.
    /// </summary>
    public static Rune SetiCakePhp => new(0xE63D);

    /// <summary>
    /// seti-checkbox.
    /// </summary>
    public static Rune SetiCheckbox => new(0xE63F);

    /// <summary>
    /// seti-checkbox_unchecked.
    /// </summary>
    public static Rune SetiCheckboxUnchecked => new(0xE640);

    /// <summary>
    /// seti-cjsx.
    /// </summary>
    public static Rune SetiCjsx => new(0xE61B);

    /// <summary>
    /// seti-clock.
    /// </summary>
    public static Rune SetiClock => new(0xE641);

    /// <summary>
    /// seti-clojure.
    /// </summary>
    public static Rune SetiClojure => new(0xE642);

    /// <summary>
    /// seti-code_climate.
    /// </summary>
    public static Rune SetiCodeClimate => new(0xE643);

    /// <summary>
    /// seti-code_search.
    /// </summary>
    public static Rune SetiCodeSearch => new(0xE644);

    /// <summary>
    /// seti-coffee.
    /// </summary>
    public static Rune SetiCoffee => new(0xE61B);

    /// <summary>
    /// seti-coldfusion.
    /// </summary>
    public static Rune SetiColdfusion => new(0xE645);

    /// <summary>
    /// seti-config.
    /// </summary>
    public static Rune SetiConfig => new(0xE615);

    /// <summary>
    /// seti-cpp.
    /// </summary>
    public static Rune SetiCpp => new(0xE646);

    /// <summary>
    /// seti-crystal.
    /// </summary>
    public static Rune SetiCrystal => new(0xE62F);

    /// <summary>
    /// seti-crystal_embedded.
    /// </summary>
    public static Rune SetiCrystalEmbedded => new(0xE647);

    /// <summary>
    /// seti-css.
    /// </summary>
    public static Rune SetiCss => new(0xE614);

    /// <summary>
    /// seti-csv.
    /// </summary>
    public static Rune SetiCsv => new(0xE64A);

    /// <summary>
    /// seti-cu.
    /// </summary>
    public static Rune SetiCu => new(0xE64B);

    /// <summary>
    /// seti-d.
    /// </summary>
    public static Rune SetiD => new(0xE651);

    /// <summary>
    /// seti-dart.
    /// </summary>
    public static Rune SetiDart => new(0xE64C);

    /// <summary>
    /// seti-db.
    /// </summary>
    public static Rune SetiDb => new(0xE64D);

    /// <summary>
    /// seti-default.
    /// </summary>
    public static Rune SetiDefault => new(0xE64E);

    /// <summary>
    /// seti-deprecation_cop.
    /// </summary>
    public static Rune SetiDeprecationCop => new(0xE64F);

    /// <summary>
    /// seti-docker.
    /// </summary>
    public static Rune SetiDocker => new(0xE650);

    /// <summary>
    /// seti-editorconfig.
    /// </summary>
    public static Rune SetiEditorconfig => new(0xE652);

    /// <summary>
    /// seti-ejs.
    /// </summary>
    public static Rune SetiEjs => new(0xE618);

    /// <summary>
    /// seti-elixir.
    /// </summary>
    public static Rune SetiElixir => new(0xE62D);

    /// <summary>
    /// seti-elixir_script.
    /// </summary>
    public static Rune SetiElixirScript => new(0xE653);

    /// <summary>
    /// seti-elm.
    /// </summary>
    public static Rune SetiElm => new(0xE62C);

    /// <summary>
    /// seti-error.
    /// </summary>
    public static Rune SetiError => new(0xE654);

    /// <summary>
    /// seti-eslint.
    /// </summary>
    public static Rune SetiEslint => new(0xE655);

    /// <summary>
    /// seti-ethereum.
    /// </summary>
    public static Rune SetiEthereum => new(0xE656);

    /// <summary>
    /// seti-f_sharp.
    /// </summary>
    public static Rune SetiFSharp => new(0xE65A);

    /// <summary>
    /// seti-favicon.
    /// </summary>
    public static Rune SetiFavicon => new(0xE623);

    /// <summary>
    /// seti-firebase.
    /// </summary>
    public static Rune SetiFirebase => new(0xE657);

    /// <summary>
    /// seti-firefox.
    /// </summary>
    public static Rune SetiFirefox => new(0xE658);

    /// <summary>
    /// seti-folder.
    /// </summary>
    public static Rune SetiFolder => new(0xE613);

    /// <summary>
    /// seti-font.
    /// </summary>
    public static Rune SetiFont => new(0xE659);

    /// <summary>
    /// seti-git.
    /// </summary>
    public static Rune SetiGit => new(0xE65D);

    /// <summary>
    /// seti-git_folder.
    /// </summary>
    public static Rune SetiGitFolder => new(0xE65D);

    /// <summary>
    /// seti-git_ignore.
    /// </summary>
    public static Rune SetiGitIgnore => new(0xE65D);

    /// <summary>
    /// seti-github.
    /// </summary>
    public static Rune SetiGithub => new(0xE65B);

    /// <summary>
    /// seti-gitlab.
    /// </summary>
    public static Rune SetiGitlab => new(0xE65C);

    /// <summary>
    /// seti-go.
    /// </summary>
    public static Rune SetiGo => new(0xE627);

    /// <summary>
    /// seti-go2.
    /// </summary>
    public static Rune SetiGo2 => new(0xE65E);

    /// <summary>
    /// seti-godot.
    /// </summary>
    public static Rune SetiGodot => new(0xE65F);

    /// <summary>
    /// seti-gradle.
    /// </summary>
    public static Rune SetiGradle => new(0xE660);

    /// <summary>
    /// seti-grails.
    /// </summary>
    public static Rune SetiGrails => new(0xE661);

    /// <summary>
    /// seti-graphql.
    /// </summary>
    public static Rune SetiGraphql => new(0xE662);

    /// <summary>
    /// seti-grunt.
    /// </summary>
    public static Rune SetiGrunt => new(0xE611);

    /// <summary>
    /// seti-gulp.
    /// </summary>
    public static Rune SetiGulp => new(0xE610);

    /// <summary>
    /// seti-hacklang.
    /// </summary>
    public static Rune SetiHacklang => new(0xE663);

    /// <summary>
    /// seti-haml.
    /// </summary>
    public static Rune SetiHaml => new(0xE664);

    /// <summary>
    /// seti-happenings.
    /// </summary>
    public static Rune SetiHappenings => new(0xE665);

    /// <summary>
    /// seti-haskell.
    /// </summary>
    public static Rune SetiHaskell => new(0xE61F);

    /// <summary>
    /// seti-haxe.
    /// </summary>
    public static Rune SetiHaxe => new(0xE666);

    /// <summary>
    /// seti-heroku.
    /// </summary>
    public static Rune SetiHeroku => new(0xE607);

    /// <summary>
    /// seti-hex.
    /// </summary>
    public static Rune SetiHex => new(0xE667);

    /// <summary>
    /// seti-home.
    /// </summary>
    public static Rune SetiHome => new(0xE617);

    /// <summary>
    /// seti-html.
    /// </summary>
    public static Rune SetiHtml => new(0xE60E);

    /// <summary>
    /// seti-ignored.
    /// </summary>
    public static Rune SetiIgnored => new(0xE668);

    /// <summary>
    /// seti-illustrator.
    /// </summary>
    public static Rune SetiIllustrator => new(0xE669);

    /// <summary>
    /// seti-image.
    /// </summary>
    public static Rune SetiImage => new(0xE60D);

    /// <summary>
    /// seti-info.
    /// </summary>
    public static Rune SetiInfo => new(0xE66A);

    /// <summary>
    /// seti-ionic.
    /// </summary>
    public static Rune SetiIonic => new(0xE66B);

    /// <summary>
    /// seti-jade.
    /// </summary>
    public static Rune SetiJade => new(0xE66C);

    /// <summary>
    /// seti-java.
    /// </summary>
    public static Rune SetiJava => new(0xE66D);

    /// <summary>
    /// seti-javascript.
    /// </summary>
    public static Rune SetiJavascript => new(0xE60C);

    /// <summary>
    /// seti-jenkins.
    /// </summary>
    public static Rune SetiJenkins => new(0xE66E);

    /// <summary>
    /// seti-jinja.
    /// </summary>
    public static Rune SetiJinja => new(0xE66F);

    /// <summary>
    /// seti-json.
    /// </summary>
    public static Rune SetiJson => new(0xE60B);

    /// <summary>
    /// seti-julia.
    /// </summary>
    public static Rune SetiJulia => new(0xE624);

    /// <summary>
    /// seti-karma.
    /// </summary>
    public static Rune SetiKarma => new(0xE622);

    /// <summary>
    /// seti-kotlin.
    /// </summary>
    public static Rune SetiKotlin => new(0xE634);

    /// <summary>
    /// seti-less.
    /// </summary>
    public static Rune SetiLess => new(0xE60B);

    /// <summary>
    /// seti-license.
    /// </summary>
    public static Rune SetiLicense => new(0xE60A);

    /// <summary>
    /// seti-liquid.
    /// </summary>
    public static Rune SetiLiquid => new(0xE670);

    /// <summary>
    /// seti-livescript.
    /// </summary>
    public static Rune SetiLivescript => new(0xE671);

    /// <summary>
    /// seti-lock.
    /// </summary>
    public static Rune SetiLock => new(0xE672);

    /// <summary>
    /// seti-lua.
    /// </summary>
    public static Rune SetiLua => new(0xE620);

    /// <summary>
    /// seti-makefile.
    /// </summary>
    public static Rune SetiMakefile => new(0xE673);

    /// <summary>
    /// seti-markdown.
    /// </summary>
    public static Rune SetiMarkdown => new(0xE609);

    /// <summary>
    /// seti-maven.
    /// </summary>
    public static Rune SetiMaven => new(0xE674);

    /// <summary>
    /// seti-mdo.
    /// </summary>
    public static Rune SetiMdo => new(0xE675);

    /// <summary>
    /// seti-mustache.
    /// </summary>
    public static Rune SetiMustache => new(0xE60F);

    /// <summary>
    /// seti-new_file.
    /// </summary>
    public static Rune SetiNewFile => new(0xE676);

    /// <summary>
    /// seti-nim.
    /// </summary>
    public static Rune SetiNim => new(0xE677);

    /// <summary>
    /// seti-notebook.
    /// </summary>
    public static Rune SetiNotebook => new(0xE678);

    /// <summary>
    /// seti-npm.
    /// </summary>
    public static Rune SetiNpm => new(0xE616);

    /// <summary>
    /// seti-npm_ignored.
    /// </summary>
    public static Rune SetiNpmIgnored => new(0xE616);

    /// <summary>
    /// seti-nunjucks.
    /// </summary>
    public static Rune SetiNunjucks => new(0xE679);

    /// <summary>
    /// seti-ocaml.
    /// </summary>
    public static Rune SetiOcaml => new(0xE67A);

    /// <summary>
    /// seti-odata.
    /// </summary>
    public static Rune SetiOdata => new(0xE67B);

    /// <summary>
    /// seti-pddl.
    /// </summary>
    public static Rune SetiPddl => new(0xE67C);

    /// <summary>
    /// seti-pdf.
    /// </summary>
    public static Rune SetiPdf => new(0xE67D);

    /// <summary>
    /// seti-perl.
    /// </summary>
    public static Rune SetiPerl => new(0xE67E);

    /// <summary>
    /// seti-photoshop.
    /// </summary>
    public static Rune SetiPhotoshop => new(0xE67F);

    /// <summary>
    /// seti-php.
    /// </summary>
    public static Rune SetiPhp => new(0xE608);

    /// <summary>
    /// seti-pipeline.
    /// </summary>
    public static Rune SetiPipeline => new(0xE680);

    /// <summary>
    /// seti-plan.
    /// </summary>
    public static Rune SetiPlan => new(0xE681);

    /// <summary>
    /// seti-platformio.
    /// </summary>
    public static Rune SetiPlatformio => new(0xE682);

    /// <summary>
    /// seti-play_arrow.
    /// </summary>
    public static Rune SetiPlayArrow => new(0xE602);

    /// <summary>
    /// seti-powershell.
    /// </summary>
    public static Rune SetiPowershell => new(0xE683);

    /// <summary>
    /// seti-prisma.
    /// </summary>
    public static Rune SetiPrisma => new(0xE684);

    /// <summary>
    /// seti-project.
    /// </summary>
    public static Rune SetiProject => new(0xE601);

    /// <summary>
    /// seti-prolog.
    /// </summary>
    public static Rune SetiProlog => new(0xE685);

    /// <summary>
    /// seti-pug.
    /// </summary>
    public static Rune SetiPug => new(0xE686);

    /// <summary>
    /// seti-puppet.
    /// </summary>
    public static Rune SetiPuppet => new(0xE631);

    /// <summary>
    /// seti-purescript.
    /// </summary>
    public static Rune SetiPurescript => new(0xE630);

    /// <summary>
    /// seti-python.
    /// </summary>
    public static Rune SetiPython => new(0xE606);

    /// <summary>
    /// seti-r.
    /// </summary>
    public static Rune SetiR => new(0xE68A);

    /// <summary>
    /// seti-rails.
    /// </summary>
    public static Rune SetiRails => new(0xE604);

    /// <summary>
    /// seti-react.
    /// </summary>
    public static Rune SetiReact => new(0xE625);

    /// <summary>
    /// seti-reasonml.
    /// </summary>
    public static Rune SetiReasonml => new(0xE687);

    /// <summary>
    /// seti-rescript.
    /// </summary>
    public static Rune SetiRescript => new(0xE688);

    /// <summary>
    /// seti-rollup.
    /// </summary>
    public static Rune SetiRollup => new(0xE689);

    /// <summary>
    /// seti-ruby.
    /// </summary>
    public static Rune SetiRuby => new(0xE605);

    /// <summary>
    /// seti-rust.
    /// </summary>
    public static Rune SetiRust => new(0xE68B);

    /// <summary>
    /// seti-salesforce.
    /// </summary>
    public static Rune SetiSalesforce => new(0xE68C);

    /// <summary>
    /// seti-sass.
    /// </summary>
    public static Rune SetiSass => new(0xE603);

    /// <summary>
    /// seti-sbt.
    /// </summary>
    public static Rune SetiSbt => new(0xE68D);

    /// <summary>
    /// seti-scala.
    /// </summary>
    public static Rune SetiScala => new(0xE68E);

    /// <summary>
    /// seti-search.
    /// </summary>
    public static Rune SetiSearch => new(0xE68F);

    /// <summary>
    /// seti-settings.
    /// </summary>
    public static Rune SetiSettings => new(0xE690);

    /// <summary>
    /// seti-shell.
    /// </summary>
    public static Rune SetiShell => new(0xE691);

    /// <summary>
    /// seti-slim.
    /// </summary>
    public static Rune SetiSlim => new(0xE692);

    /// <summary>
    /// seti-smarty.
    /// </summary>
    public static Rune SetiSmarty => new(0xE693);

    /// <summary>
    /// seti-spring.
    /// </summary>
    public static Rune SetiSpring => new(0xE694);

    /// <summary>
    /// seti-stylelint.
    /// </summary>
    public static Rune SetiStylelint => new(0xE695);

    /// <summary>
    /// seti-stylus.
    /// </summary>
    public static Rune SetiStylus => new(0xE600);

    /// <summary>
    /// seti-sublime.
    /// </summary>
    public static Rune SetiSublime => new(0xE696);

    /// <summary>
    /// seti-svelte.
    /// </summary>
    public static Rune SetiSvelte => new(0xE697);

    /// <summary>
    /// seti-svg.
    /// </summary>
    public static Rune SetiSvg => new(0xE698);

    /// <summary>
    /// seti-swift.
    /// </summary>
    public static Rune SetiSwift => new(0xE699);

    /// <summary>
    /// seti-terraform.
    /// </summary>
    public static Rune SetiTerraform => new(0xE69A);

    /// <summary>
    /// seti-tex.
    /// </summary>
    public static Rune SetiTex => new(0xE69B);

    /// <summary>
    /// seti-text.
    /// </summary>
    public static Rune SetiText => new(0xE64E);

    /// <summary>
    /// seti-time_cop.
    /// </summary>
    public static Rune SetiTimeCop => new(0xE641);

    /// <summary>
    /// seti-todo.
    /// </summary>
    public static Rune SetiTodo => new(0xE69C);

    /// <summary>
    /// seti-tsconfig.
    /// </summary>
    public static Rune SetiTsconfig => new(0xE69D);

    /// <summary>
    /// seti-twig.
    /// </summary>
    public static Rune SetiTwig => new(0xE61C);

    /// <summary>
    /// seti-typescript.
    /// </summary>
    public static Rune SetiTypescript => new(0xE628);

    /// <summary>
    /// seti-vala.
    /// </summary>
    public static Rune SetiVala => new(0xE69E);

    /// <summary>
    /// seti-video.
    /// </summary>
    public static Rune SetiVideo => new(0xE69F);

    /// <summary>
    /// seti-vue.
    /// </summary>
    public static Rune SetiVue => new(0xE6A0);

    /// <summary>
    /// seti-wasm.
    /// </summary>
    public static Rune SetiWasm => new(0xE6A1);

    /// <summary>
    /// seti-wat.
    /// </summary>
    public static Rune SetiWat => new(0xE6A2);

    /// <summary>
    /// seti-webpack.
    /// </summary>
    public static Rune SetiWebpack => new(0xE6A3);

    /// <summary>
    /// seti-wgt.
    /// </summary>
    public static Rune SetiWgt => new(0xE6A4);

    /// <summary>
    /// seti-word.
    /// </summary>
    public static Rune SetiWord => new(0xE6A5);

    /// <summary>
    /// seti-xls.
    /// </summary>
    public static Rune SetiXls => new(0xE6A6);

    /// <summary>
    /// seti-xml.
    /// </summary>
    public static Rune SetiXml => new(0xE619);

    /// <summary>
    /// seti-yarn.
    /// </summary>
    public static Rune SetiYarn => new(0xE6A7);

    /// <summary>
    /// seti-yml.
    /// </summary>
    public static Rune SetiYml => new(0xE6A8);

    /// <summary>
    /// seti-zig.
    /// </summary>
    public static Rune SetiZig => new(0xE6A9);

    /// <summary>
    /// seti-zip.
    /// </summary>
    public static Rune SetiZip => new(0xE6AA);

}
