// <auto-generated />

using System.Text;

namespace XenoAtom.Terminal.UI;

public static partial class NerdFont
{
    /// <summary>
    /// indentation-line.
    /// </summary>
    public static Rune IndentationLine => new(0xE621);

}
