// <auto-generated />

using System.Text;

namespace XenoAtom.Terminal.UI;

/// <summary>
/// Provides generated Nerd Font glyph runes grouped across multiple partial files.
/// </summary>
/// <remarks>
/// Generated from https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/glyphnames.json.
/// Source version: 3.4.0.
/// Source date: 2025-04-24 16:34:47+00:00.
/// These properties return <see cref="Rune"/> values so they can be used directly in string interpolation and text rendering APIs.
/// </remarks>
public static partial class NerdFont
{
}
