// <auto-generated />

using System.Collections.Generic;
using System.Text;

namespace XenoAtom.Terminal.UI;

/// <summary>
/// Provides generated Nerd Font glyph runes grouped across multiple partial files.
/// </summary>
/// <remarks>
/// Generated from https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/glyphnames.json.
/// Source version: 3.4.0.
/// Source date: 2025-04-24 16:34:47+00:00.
/// These properties return <see cref="Rune"/> values so they can be used directly in string interpolation and text rendering APIs.
/// </remarks>
public static partial class NerdFont
{
    /// <summary>
    /// Gets the original Nerd Fonts glyph names available for lookup.
    /// </summary>
    public static IReadOnlyList<string> Names => NerdFontLookup.Names;

    /// <summary>
    /// Gets the glyph rune for an original Nerd Fonts glyph name.
    /// </summary>
    /// <param name="name">The original Nerd Fonts glyph name, for example <c>cod-account</c>.</param>
    /// <param name="rune">When this method returns, contains the glyph rune if <paramref name="name"/> was found; otherwise, the default value.</param>
    /// <returns><c>true</c> if <paramref name="name"/> was found; otherwise, <c>false</c>.</returns>
    public static bool TryGetRune(string name, out Rune rune)
    {
        if (name is null)
        {
            rune = default;
            return false;
        }

        return NerdFontLookup.TryGetRune(name, out rune);
    }
}
