// <auto-generated />

using System.Text;

namespace XenoAtom.Terminal.UI;

public static partial class NerdFont
{
    /// <summary>
    /// ple-backslash_separator.
    /// </summary>
    public static Rune PleBackslashSeparator => new(0xE0B9);

    /// <summary>
    /// ple-backslash_separator_redundant.
    /// </summary>
    public static Rune PleBackslashSeparatorRedundant => new(0xE0BF);

    /// <summary>
    /// ple-column_number.
    /// </summary>
    public static Rune PleColumnNumber => new(0xE0A3);

    /// <summary>
    /// ple-current_column.
    /// </summary>
    public static Rune PleCurrentColumn => new(0xE0A3);

    /// <summary>
    /// ple-flame_thick.
    /// </summary>
    public static Rune PleFlameThick => new(0xE0C0);

    /// <summary>
    /// ple-flame_thick_mirrored.
    /// </summary>
    public static Rune PleFlameThickMirrored => new(0xE0C2);

    /// <summary>
    /// ple-flame_thin.
    /// </summary>
    public static Rune PleFlameThin => new(0xE0C1);

    /// <summary>
    /// ple-flame_thin_mirrored.
    /// </summary>
    public static Rune PleFlameThinMirrored => new(0xE0C3);

    /// <summary>
    /// ple-forwardslash_separator.
    /// </summary>
    public static Rune PleForwardslashSeparator => new(0xE0BB);

    /// <summary>
    /// ple-forwardslash_separator_redundant.
    /// </summary>
    public static Rune PleForwardslashSeparatorRedundant => new(0xE0BD);

    /// <summary>
    /// ple-honeycomb.
    /// </summary>
    public static Rune PleHoneycomb => new(0xE0CC);

    /// <summary>
    /// ple-honeycomb_outline.
    /// </summary>
    public static Rune PleHoneycombOutline => new(0xE0CD);

    /// <summary>
    /// ple-ice_waveform.
    /// </summary>
    public static Rune PleIceWaveform => new(0xE0C8);

    /// <summary>
    /// ple-ice_waveform_mirrored.
    /// </summary>
    public static Rune PleIceWaveformMirrored => new(0xE0CA);

    /// <summary>
    /// ple-left_half_circle_thick.
    /// </summary>
    public static Rune PleLeftHalfCircleThick => new(0xE0B6);

    /// <summary>
    /// ple-left_half_circle_thin.
    /// </summary>
    public static Rune PleLeftHalfCircleThin => new(0xE0B7);

    /// <summary>
    /// ple-left_hard_divider_inverse.
    /// </summary>
    public static Rune PleLeftHardDividerInverse => new(0xE0D7);

    /// <summary>
    /// ple-lego_block_facing.
    /// </summary>
    public static Rune PleLegoBlockFacing => new(0xE0D0);

    /// <summary>
    /// ple-lego_block_sideways.
    /// </summary>
    public static Rune PleLegoBlockSideways => new(0xE0D1);

    /// <summary>
    /// ple-lego_separator.
    /// </summary>
    public static Rune PleLegoSeparator => new(0xE0CE);

    /// <summary>
    /// ple-lego_separator_thin.
    /// </summary>
    public static Rune PleLegoSeparatorThin => new(0xE0CF);

    /// <summary>
    /// ple-lower_left_triangle.
    /// </summary>
    public static Rune PleLowerLeftTriangle => new(0xE0B8);

    /// <summary>
    /// ple-lower_right_triangle.
    /// </summary>
    public static Rune PleLowerRightTriangle => new(0xE0BA);

    /// <summary>
    /// ple-pixelated_squares_big.
    /// </summary>
    public static Rune PlePixelatedSquaresBig => new(0xE0C6);

    /// <summary>
    /// ple-pixelated_squares_big_mirrored.
    /// </summary>
    public static Rune PlePixelatedSquaresBigMirrored => new(0xE0C7);

    /// <summary>
    /// ple-pixelated_squares_small.
    /// </summary>
    public static Rune PlePixelatedSquaresSmall => new(0xE0C4);

    /// <summary>
    /// ple-pixelated_squares_small_mirrored.
    /// </summary>
    public static Rune PlePixelatedSquaresSmallMirrored => new(0xE0C5);

    /// <summary>
    /// ple-right_half_circle_thick.
    /// </summary>
    public static Rune PleRightHalfCircleThick => new(0xE0B4);

    /// <summary>
    /// ple-right_half_circle_thin.
    /// </summary>
    public static Rune PleRightHalfCircleThin => new(0xE0B5);

    /// <summary>
    /// ple-right_hard_divider_inverse.
    /// </summary>
    public static Rune PleRightHardDividerInverse => new(0xE0D6);

    /// <summary>
    /// ple-trapezoid_top_bottom.
    /// </summary>
    public static Rune PleTrapezoidTopBottom => new(0xE0D2);

    /// <summary>
    /// ple-trapezoid_top_bottom_mirrored.
    /// </summary>
    public static Rune PleTrapezoidTopBottomMirrored => new(0xE0D4);

    /// <summary>
    /// ple-upper_left_triangle.
    /// </summary>
    public static Rune PleUpperLeftTriangle => new(0xE0BC);

    /// <summary>
    /// ple-upper_right_triangle.
    /// </summary>
    public static Rune PleUpperRightTriangle => new(0xE0BE);

}
