// <auto-generated />

using System.Text;

namespace XenoAtom.Terminal.UI;

public static partial class NerdFont
{
    internal static bool IsWideRuneCandidate(Rune rune)
    {
        var value = (uint)rune.Value;
        if (value < 0xE000u)
        {
            return value is >= 0x23FBu and <= 0x23FEu or 0x2665u or 0x26A1u or 0x2B58u;
        }
        if (value < 0xF000u)
        {
            return value is >= 0xE000u and <= 0xE00Au or >= 0xE0A0u and <= 0xE0A3u or >= 0xE0B0u and <= 0xE0C8u or 0xE0CAu or >= 0xE0CCu and <= 0xE0D2u or 0xE0D4u or >= 0xE0D6u and <= 0xE0D7u or >= 0xE200u and <= 0xE2A9u or >= 0xE300u and <= 0xE3E3u or >= 0xE5FAu and <= 0xE6B8u or >= 0xE700u and <= 0xE8EFu or >= 0xEA60u and <= 0xEA88u or >= 0xEA8Au and <= 0xEA8Cu or >= 0xEA8Fu and <= 0xEAC7u or 0xEAC9u or >= 0xEACCu and <= 0xEAFAu or >= 0xEAFCu and <= 0xEB09u or >= 0xEB0Bu and <= 0xEB4Eu or >= 0xEB50u and <= 0xEC1Eu or >= 0xED00u and <= 0xEFCEu;
        }
        if (value < 0x10000u)
        {
            return value is >= 0xF000u and <= 0xF381u or >= 0xF400u and <= 0xF533u;
        }
        if (value < 0x110000u)
        {
            return value is >= 0xF0001u and <= 0xF0387u or >= 0xF0389u and <= 0xF043Cu or >= 0xF043Eu and <= 0xF0508u or >= 0xF050Au and <= 0xF05FBu or >= 0xF05FDu and <= 0xF0764u or >= 0xF0767u and <= 0xF08CFu or >= 0xF08D1u and <= 0xF0B38u or >= 0xF0B3Au and <= 0xF0C9Du or >= 0xF0CA0u and <= 0xF1087u or >= 0xF1089u and <= 0xF108Bu or >= 0xF108Du and <= 0xF1090u or >= 0xF1092u and <= 0xF13A5u or >= 0xF13A7u and <= 0xF189Fu or >= 0xF18A1u and <= 0xF18EFu or >= 0xF18F1u and <= 0xF1AF0u;
        }

        return false;
    }
}
