// <auto-generated />

using System.Text;

namespace XenoAtom.Terminal.UI;

public static partial class NerdFont
{
    /// <summary>
    /// linux-almalinux.
    /// </summary>
    public static Rune LinuxAlmalinux => new(0xF31D);

    /// <summary>
    /// linux-alpine.
    /// </summary>
    public static Rune LinuxAlpine => new(0xF300);

    /// <summary>
    /// linux-aosc.
    /// </summary>
    public static Rune LinuxAosc => new(0xF301);

    /// <summary>
    /// linux-apple.
    /// </summary>
    public static Rune LinuxApple => new(0xF302);

    /// <summary>
    /// linux-archcraft.
    /// </summary>
    public static Rune LinuxArchcraft => new(0xF345);

    /// <summary>
    /// linux-archlabs.
    /// </summary>
    public static Rune LinuxArchlabs => new(0xF31E);

    /// <summary>
    /// linux-archlinux.
    /// </summary>
    public static Rune LinuxArchlinux => new(0xF303);

    /// <summary>
    /// linux-arcolinux.
    /// </summary>
    public static Rune LinuxArcolinux => new(0xF346);

    /// <summary>
    /// linux-arduino.
    /// </summary>
    public static Rune LinuxArduino => new(0xF34B);

    /// <summary>
    /// linux-artix.
    /// </summary>
    public static Rune LinuxArtix => new(0xF31F);

    /// <summary>
    /// linux-awesome.
    /// </summary>
    public static Rune LinuxAwesome => new(0xF354);

    /// <summary>
    /// linux-biglinux.
    /// </summary>
    public static Rune LinuxBiglinux => new(0xF347);

    /// <summary>
    /// linux-bspwm.
    /// </summary>
    public static Rune LinuxBspwm => new(0xF355);

    /// <summary>
    /// linux-budgie.
    /// </summary>
    public static Rune LinuxBudgie => new(0xF320);

    /// <summary>
    /// linux-centos.
    /// </summary>
    public static Rune LinuxCentos => new(0xF304);

    /// <summary>
    /// linux-cinnamon.
    /// </summary>
    public static Rune LinuxCinnamon => new(0xF35F);

    /// <summary>
    /// linux-codeberg.
    /// </summary>
    public static Rune LinuxCodeberg => new(0xF330);

    /// <summary>
    /// linux-coreos.
    /// </summary>
    public static Rune LinuxCoreos => new(0xF305);

    /// <summary>
    /// linux-crystal.
    /// </summary>
    public static Rune LinuxCrystal => new(0xF348);

    /// <summary>
    /// linux-debian.
    /// </summary>
    public static Rune LinuxDebian => new(0xF306);

    /// <summary>
    /// linux-deepin.
    /// </summary>
    public static Rune LinuxDeepin => new(0xF321);

    /// <summary>
    /// linux-devuan.
    /// </summary>
    public static Rune LinuxDevuan => new(0xF307);

    /// <summary>
    /// linux-docker.
    /// </summary>
    public static Rune LinuxDocker => new(0xF308);

    /// <summary>
    /// linux-dwm.
    /// </summary>
    public static Rune LinuxDwm => new(0xF356);

    /// <summary>
    /// linux-elementary.
    /// </summary>
    public static Rune LinuxElementary => new(0xF309);

    /// <summary>
    /// linux-endeavour.
    /// </summary>
    public static Rune LinuxEndeavour => new(0xF322);

    /// <summary>
    /// linux-enlightenment.
    /// </summary>
    public static Rune LinuxEnlightenment => new(0xF357);

    /// <summary>
    /// linux-fdroid.
    /// </summary>
    public static Rune LinuxFdroid => new(0xF36A);

    /// <summary>
    /// linux-fedora.
    /// </summary>
    public static Rune LinuxFedora => new(0xF30A);

    /// <summary>
    /// linux-fedora_inverse.
    /// </summary>
    public static Rune LinuxFedoraInverse => new(0xF30B);

    /// <summary>
    /// linux-ferris.
    /// </summary>
    public static Rune LinuxFerris => new(0xF323);

    /// <summary>
    /// linux-flathub.
    /// </summary>
    public static Rune LinuxFlathub => new(0xF324);

    /// <summary>
    /// linux-fluxbox.
    /// </summary>
    public static Rune LinuxFluxbox => new(0xF358);

    /// <summary>
    /// linux-forgejo.
    /// </summary>
    public static Rune LinuxForgejo => new(0xF335);

    /// <summary>
    /// linux-fosdem.
    /// </summary>
    public static Rune LinuxFosdem => new(0xF36B);

    /// <summary>
    /// linux-freebsd.
    /// </summary>
    public static Rune LinuxFreebsd => new(0xF30C);

    /// <summary>
    /// linux-freecad.
    /// </summary>
    public static Rune LinuxFreecad => new(0xF336);

    /// <summary>
    /// linux-freedesktop.
    /// </summary>
    public static Rune LinuxFreedesktop => new(0xF360);

    /// <summary>
    /// linux-garuda.
    /// </summary>
    public static Rune LinuxGaruda => new(0xF337);

    /// <summary>
    /// linux-gentoo.
    /// </summary>
    public static Rune LinuxGentoo => new(0xF30D);

    /// <summary>
    /// linux-gimp.
    /// </summary>
    public static Rune LinuxGimp => new(0xF338);

    /// <summary>
    /// linux-gitea.
    /// </summary>
    public static Rune LinuxGitea => new(0xF339);

    /// <summary>
    /// linux-gnome.
    /// </summary>
    public static Rune LinuxGnome => new(0xF361);

    /// <summary>
    /// linux-gnu_guix.
    /// </summary>
    public static Rune LinuxGnuGuix => new(0xF325);

    /// <summary>
    /// linux-gtk.
    /// </summary>
    public static Rune LinuxGtk => new(0xF362);

    /// <summary>
    /// linux-hyperbola.
    /// </summary>
    public static Rune LinuxHyperbola => new(0xF33A);

    /// <summary>
    /// linux-hyprland.
    /// </summary>
    public static Rune LinuxHyprland => new(0xF359);

    /// <summary>
    /// linux-i3.
    /// </summary>
    public static Rune LinuxI3 => new(0xF35A);

    /// <summary>
    /// linux-illumos.
    /// </summary>
    public static Rune LinuxIllumos => new(0xF326);

    /// <summary>
    /// linux-inkscape.
    /// </summary>
    public static Rune LinuxInkscape => new(0xF33B);

    /// <summary>
    /// linux-jwm.
    /// </summary>
    public static Rune LinuxJwm => new(0xF35B);

    /// <summary>
    /// linux-kali_linux.
    /// </summary>
    public static Rune LinuxKaliLinux => new(0xF327);

    /// <summary>
    /// linux-kde.
    /// </summary>
    public static Rune LinuxKde => new(0xF373);

    /// <summary>
    /// linux-kde_neon.
    /// </summary>
    public static Rune LinuxKdeNeon => new(0xF331);

    /// <summary>
    /// linux-kde_plasma.
    /// </summary>
    public static Rune LinuxKdePlasma => new(0xF332);

    /// <summary>
    /// linux-kdenlive.
    /// </summary>
    public static Rune LinuxKdenlive => new(0xF33C);

    /// <summary>
    /// linux-kicad.
    /// </summary>
    public static Rune LinuxKicad => new(0xF34C);

    /// <summary>
    /// linux-krita.
    /// </summary>
    public static Rune LinuxKrita => new(0xF33D);

    /// <summary>
    /// linux-kubuntu.
    /// </summary>
    public static Rune LinuxKubuntu => new(0xF333);

    /// <summary>
    /// linux-kubuntu_inverse.
    /// </summary>
    public static Rune LinuxKubuntuInverse => new(0xF334);

    /// <summary>
    /// linux-leap.
    /// </summary>
    public static Rune LinuxLeap => new(0xF37E);

    /// <summary>
    /// linux-libreoffice.
    /// </summary>
    public static Rune LinuxLibreoffice => new(0xF376);

    /// <summary>
    /// linux-libreofficebase.
    /// </summary>
    public static Rune LinuxLibreofficebase => new(0xF377);

    /// <summary>
    /// linux-libreofficecalc.
    /// </summary>
    public static Rune LinuxLibreofficecalc => new(0xF378);

    /// <summary>
    /// linux-libreofficedraw.
    /// </summary>
    public static Rune LinuxLibreofficedraw => new(0xF379);

    /// <summary>
    /// linux-libreofficeimpress.
    /// </summary>
    public static Rune LinuxLibreofficeimpress => new(0xF37A);

    /// <summary>
    /// linux-libreofficemath.
    /// </summary>
    public static Rune LinuxLibreofficemath => new(0xF37B);

    /// <summary>
    /// linux-libreofficewriter.
    /// </summary>
    public static Rune LinuxLibreofficewriter => new(0xF37C);

    /// <summary>
    /// linux-linuxmint.
    /// </summary>
    public static Rune LinuxLinuxmint => new(0xF30E);

    /// <summary>
    /// linux-linuxmint_inverse.
    /// </summary>
    public static Rune LinuxLinuxmintInverse => new(0xF30F);

    /// <summary>
    /// linux-locos.
    /// </summary>
    public static Rune LinuxLocos => new(0xF349);

    /// <summary>
    /// linux-lxde.
    /// </summary>
    public static Rune LinuxLxde => new(0xF363);

    /// <summary>
    /// linux-lxle.
    /// </summary>
    public static Rune LinuxLxle => new(0xF33E);

    /// <summary>
    /// linux-lxqt.
    /// </summary>
    public static Rune LinuxLxqt => new(0xF364);

    /// <summary>
    /// linux-mageia.
    /// </summary>
    public static Rune LinuxMageia => new(0xF310);

    /// <summary>
    /// linux-mandriva.
    /// </summary>
    public static Rune LinuxMandriva => new(0xF311);

    /// <summary>
    /// linux-manjaro.
    /// </summary>
    public static Rune LinuxManjaro => new(0xF312);

    /// <summary>
    /// linux-mate.
    /// </summary>
    public static Rune LinuxMate => new(0xF365);

    /// <summary>
    /// linux-mpv.
    /// </summary>
    public static Rune LinuxMpv => new(0xF36E);

    /// <summary>
    /// linux-mxlinux.
    /// </summary>
    public static Rune LinuxMxlinux => new(0xF33F);

    /// <summary>
    /// linux-neovim.
    /// </summary>
    public static Rune LinuxNeovim => new(0xF36F);

    /// <summary>
    /// linux-nixos.
    /// </summary>
    public static Rune LinuxNixos => new(0xF313);

    /// <summary>
    /// linux-nobara.
    /// </summary>
    public static Rune LinuxNobara => new(0xF380);

    /// <summary>
    /// linux-octoprint.
    /// </summary>
    public static Rune LinuxOctoprint => new(0xF34D);

    /// <summary>
    /// linux-openbsd.
    /// </summary>
    public static Rune LinuxOpenbsd => new(0xF328);

    /// <summary>
    /// linux-openscad.
    /// </summary>
    public static Rune LinuxOpenscad => new(0xF34E);

    /// <summary>
    /// linux-opensuse.
    /// </summary>
    public static Rune LinuxOpensuse => new(0xF314);

    /// <summary>
    /// linux-osh.
    /// </summary>
    public static Rune LinuxOsh => new(0xF34F);

    /// <summary>
    /// linux-oshwa.
    /// </summary>
    public static Rune LinuxOshwa => new(0xF350);

    /// <summary>
    /// linux-osi.
    /// </summary>
    public static Rune LinuxOsi => new(0xF36C);

    /// <summary>
    /// linux-parabola.
    /// </summary>
    public static Rune LinuxParabola => new(0xF340);

    /// <summary>
    /// linux-parrot.
    /// </summary>
    public static Rune LinuxParrot => new(0xF329);

    /// <summary>
    /// linux-pop_os.
    /// </summary>
    public static Rune LinuxPopOs => new(0xF32A);

    /// <summary>
    /// linux-postmarketos.
    /// </summary>
    public static Rune LinuxPostmarketos => new(0xF374);

    /// <summary>
    /// linux-prusaslicer.
    /// </summary>
    public static Rune LinuxPrusaslicer => new(0xF351);

    /// <summary>
    /// linux-puppy.
    /// </summary>
    public static Rune LinuxPuppy => new(0xF341);

    /// <summary>
    /// linux-qt.
    /// </summary>
    public static Rune LinuxQt => new(0xF375);

    /// <summary>
    /// linux-qtile.
    /// </summary>
    public static Rune LinuxQtile => new(0xF35C);

    /// <summary>
    /// linux-qubesos.
    /// </summary>
    public static Rune LinuxQubesos => new(0xF342);

    /// <summary>
    /// linux-raspberry_pi.
    /// </summary>
    public static Rune LinuxRaspberryPi => new(0xF315);

    /// <summary>
    /// linux-redhat.
    /// </summary>
    public static Rune LinuxRedhat => new(0xF316);

    /// <summary>
    /// linux-reprap.
    /// </summary>
    public static Rune LinuxReprap => new(0xF352);

    /// <summary>
    /// linux-riscv.
    /// </summary>
    public static Rune LinuxRiscv => new(0xF353);

    /// <summary>
    /// linux-river.
    /// </summary>
    public static Rune LinuxRiver => new(0xF381);

    /// <summary>
    /// linux-rocky_linux.
    /// </summary>
    public static Rune LinuxRockyLinux => new(0xF32B);

    /// <summary>
    /// linux-sabayon.
    /// </summary>
    public static Rune LinuxSabayon => new(0xF317);

    /// <summary>
    /// linux-slackware.
    /// </summary>
    public static Rune LinuxSlackware => new(0xF318);

    /// <summary>
    /// linux-slackware_inverse.
    /// </summary>
    public static Rune LinuxSlackwareInverse => new(0xF319);

    /// <summary>
    /// linux-snappy.
    /// </summary>
    public static Rune LinuxSnappy => new(0xF32C);

    /// <summary>
    /// linux-solus.
    /// </summary>
    public static Rune LinuxSolus => new(0xF32D);

    /// <summary>
    /// linux-sway.
    /// </summary>
    public static Rune LinuxSway => new(0xF35D);

    /// <summary>
    /// linux-tails.
    /// </summary>
    public static Rune LinuxTails => new(0xF343);

    /// <summary>
    /// linux-thunderbird.
    /// </summary>
    public static Rune LinuxThunderbird => new(0xF370);

    /// <summary>
    /// linux-tor.
    /// </summary>
    public static Rune LinuxTor => new(0xF371);

    /// <summary>
    /// linux-trisquel.
    /// </summary>
    public static Rune LinuxTrisquel => new(0xF344);

    /// <summary>
    /// linux-tumbleweed.
    /// </summary>
    public static Rune LinuxTumbleweed => new(0xF37D);

    /// <summary>
    /// linux-tux.
    /// </summary>
    public static Rune LinuxTux => new(0xF31A);

    /// <summary>
    /// linux-typst.
    /// </summary>
    public static Rune LinuxTypst => new(0xF37F);

    /// <summary>
    /// linux-ubuntu.
    /// </summary>
    public static Rune LinuxUbuntu => new(0xF31B);

    /// <summary>
    /// linux-ubuntu_inverse.
    /// </summary>
    public static Rune LinuxUbuntuInverse => new(0xF31C);

    /// <summary>
    /// linux-vanilla.
    /// </summary>
    public static Rune LinuxVanilla => new(0xF366);

    /// <summary>
    /// linux-void.
    /// </summary>
    public static Rune LinuxVoid => new(0xF32E);

    /// <summary>
    /// linux-vscodium.
    /// </summary>
    public static Rune LinuxVscodium => new(0xF372);

    /// <summary>
    /// linux-wayland.
    /// </summary>
    public static Rune LinuxWayland => new(0xF367);

    /// <summary>
    /// linux-wikimedia.
    /// </summary>
    public static Rune LinuxWikimedia => new(0xF36D);

    /// <summary>
    /// linux-xerolinux.
    /// </summary>
    public static Rune LinuxXerolinux => new(0xF34A);

    /// <summary>
    /// linux-xfce.
    /// </summary>
    public static Rune LinuxXfce => new(0xF368);

    /// <summary>
    /// linux-xmonad.
    /// </summary>
    public static Rune LinuxXmonad => new(0xF35E);

    /// <summary>
    /// linux-xorg.
    /// </summary>
    public static Rune LinuxXorg => new(0xF369);

    /// <summary>
    /// linux-zorin.
    /// </summary>
    public static Rune LinuxZorin => new(0xF32F);

}
