// <auto-generated />

using System.Text;

namespace XenoAtom.Terminal.UI;

public static partial class NerdFont
{
    /// <summary>
    /// cod-account.
    /// </summary>
    public static Rune CodAccount => new(0xEB99);

    /// <summary>
    /// cod-activate_breakpoints.
    /// </summary>
    public static Rune CodActivateBreakpoints => new(0xEA97);

    /// <summary>
    /// cod-add.
    /// </summary>
    public static Rune CodAdd => new(0xEA60);

    /// <summary>
    /// cod-archive.
    /// </summary>
    public static Rune CodArchive => new(0xEA98);

    /// <summary>
    /// cod-arrow_both.
    /// </summary>
    public static Rune CodArrowBoth => new(0xEA99);

    /// <summary>
    /// cod-arrow_circle_down.
    /// </summary>
    public static Rune CodArrowCircleDown => new(0xEBFC);

    /// <summary>
    /// cod-arrow_circle_left.
    /// </summary>
    public static Rune CodArrowCircleLeft => new(0xEBFD);

    /// <summary>
    /// cod-arrow_circle_right.
    /// </summary>
    public static Rune CodArrowCircleRight => new(0xEBFE);

    /// <summary>
    /// cod-arrow_circle_up.
    /// </summary>
    public static Rune CodArrowCircleUp => new(0xEBFF);

    /// <summary>
    /// cod-arrow_down.
    /// </summary>
    public static Rune CodArrowDown => new(0xEA9A);

    /// <summary>
    /// cod-arrow_left.
    /// </summary>
    public static Rune CodArrowLeft => new(0xEA9B);

    /// <summary>
    /// cod-arrow_right.
    /// </summary>
    public static Rune CodArrowRight => new(0xEA9C);

    /// <summary>
    /// cod-arrow_small_down.
    /// </summary>
    public static Rune CodArrowSmallDown => new(0xEA9D);

    /// <summary>
    /// cod-arrow_small_left.
    /// </summary>
    public static Rune CodArrowSmallLeft => new(0xEA9E);

    /// <summary>
    /// cod-arrow_small_right.
    /// </summary>
    public static Rune CodArrowSmallRight => new(0xEA9F);

    /// <summary>
    /// cod-arrow_small_up.
    /// </summary>
    public static Rune CodArrowSmallUp => new(0xEAA0);

    /// <summary>
    /// cod-arrow_swap.
    /// </summary>
    public static Rune CodArrowSwap => new(0xEBCB);

    /// <summary>
    /// cod-arrow_up.
    /// </summary>
    public static Rune CodArrowUp => new(0xEAA1);

    /// <summary>
    /// cod-azure.
    /// </summary>
    public static Rune CodAzure => new(0xEBD8);

    /// <summary>
    /// cod-azure_devops.
    /// </summary>
    public static Rune CodAzureDevops => new(0xEBE8);

    /// <summary>
    /// cod-beaker.
    /// </summary>
    public static Rune CodBeaker => new(0xEA79);

    /// <summary>
    /// cod-beaker_stop.
    /// </summary>
    public static Rune CodBeakerStop => new(0xEBE1);

    /// <summary>
    /// cod-bell.
    /// </summary>
    public static Rune CodBell => new(0xEAA2);

    /// <summary>
    /// cod-bell_dot.
    /// </summary>
    public static Rune CodBellDot => new(0xEB9A);

    /// <summary>
    /// cod-bell_slash.
    /// </summary>
    public static Rune CodBellSlash => new(0xEC08);

    /// <summary>
    /// cod-bell_slash_dot.
    /// </summary>
    public static Rune CodBellSlashDot => new(0xEC09);

    /// <summary>
    /// cod-blank.
    /// </summary>
    public static Rune CodBlank => new(0xEC03);

    /// <summary>
    /// cod-bold.
    /// </summary>
    public static Rune CodBold => new(0xEAA3);

    /// <summary>
    /// cod-book.
    /// </summary>
    public static Rune CodBook => new(0xEAA4);

    /// <summary>
    /// cod-bookmark.
    /// </summary>
    public static Rune CodBookmark => new(0xEAA5);

    /// <summary>
    /// cod-bracket_dot.
    /// </summary>
    public static Rune CodBracketDot => new(0xEBE5);

    /// <summary>
    /// cod-bracket_error.
    /// </summary>
    public static Rune CodBracketError => new(0xEBE6);

    /// <summary>
    /// cod-briefcase.
    /// </summary>
    public static Rune CodBriefcase => new(0xEAAC);

    /// <summary>
    /// cod-broadcast.
    /// </summary>
    public static Rune CodBroadcast => new(0xEAAD);

    /// <summary>
    /// cod-browser.
    /// </summary>
    public static Rune CodBrowser => new(0xEAAE);

    /// <summary>
    /// cod-bug.
    /// </summary>
    public static Rune CodBug => new(0xEAAF);

    /// <summary>
    /// cod-calendar.
    /// </summary>
    public static Rune CodCalendar => new(0xEAB0);

    /// <summary>
    /// cod-call_incoming.
    /// </summary>
    public static Rune CodCallIncoming => new(0xEB92);

    /// <summary>
    /// cod-call_outgoing.
    /// </summary>
    public static Rune CodCallOutgoing => new(0xEB93);

    /// <summary>
    /// cod-case_sensitive.
    /// </summary>
    public static Rune CodCaseSensitive => new(0xEAB1);

    /// <summary>
    /// cod-check.
    /// </summary>
    public static Rune CodCheck => new(0xEAB2);

    /// <summary>
    /// cod-check_all.
    /// </summary>
    public static Rune CodCheckAll => new(0xEBB1);

    /// <summary>
    /// cod-checklist.
    /// </summary>
    public static Rune CodChecklist => new(0xEAB3);

    /// <summary>
    /// cod-chevron_down.
    /// </summary>
    public static Rune CodChevronDown => new(0xEAB4);

    /// <summary>
    /// cod-chevron_left.
    /// </summary>
    public static Rune CodChevronLeft => new(0xEAB5);

    /// <summary>
    /// cod-chevron_right.
    /// </summary>
    public static Rune CodChevronRight => new(0xEAB6);

    /// <summary>
    /// cod-chevron_up.
    /// </summary>
    public static Rune CodChevronUp => new(0xEAB7);

    /// <summary>
    /// cod-chip.
    /// </summary>
    public static Rune CodChip => new(0xEC19);

    /// <summary>
    /// cod-chrome_close.
    /// </summary>
    public static Rune CodChromeClose => new(0xEAB8);

    /// <summary>
    /// cod-chrome_maximize.
    /// </summary>
    public static Rune CodChromeMaximize => new(0xEAB9);

    /// <summary>
    /// cod-chrome_minimize.
    /// </summary>
    public static Rune CodChromeMinimize => new(0xEABA);

    /// <summary>
    /// cod-chrome_restore.
    /// </summary>
    public static Rune CodChromeRestore => new(0xEABB);

    /// <summary>
    /// cod-circle.
    /// </summary>
    public static Rune CodCircle => new(0xEABC);

    /// <summary>
    /// cod-circle_filled.
    /// </summary>
    public static Rune CodCircleFilled => new(0xEA71);

    /// <summary>
    /// cod-circle_large.
    /// </summary>
    public static Rune CodCircleLarge => new(0xEBB5);

    /// <summary>
    /// cod-circle_large_filled.
    /// </summary>
    public static Rune CodCircleLargeFilled => new(0xEBB4);

    /// <summary>
    /// cod-circle_slash.
    /// </summary>
    public static Rune CodCircleSlash => new(0xEABD);

    /// <summary>
    /// cod-circle_small.
    /// </summary>
    public static Rune CodCircleSmall => new(0xEC07);

    /// <summary>
    /// cod-circle_small_filled.
    /// </summary>
    public static Rune CodCircleSmallFilled => new(0xEB8A);

    /// <summary>
    /// cod-circuit_board.
    /// </summary>
    public static Rune CodCircuitBoard => new(0xEABE);

    /// <summary>
    /// cod-clear_all.
    /// </summary>
    public static Rune CodClearAll => new(0xEABF);

    /// <summary>
    /// cod-clippy.
    /// </summary>
    public static Rune CodClippy => new(0xEAC0);

    /// <summary>
    /// cod-close.
    /// </summary>
    public static Rune CodClose => new(0xEA76);

    /// <summary>
    /// cod-close_all.
    /// </summary>
    public static Rune CodCloseAll => new(0xEAC1);

    /// <summary>
    /// cod-cloud.
    /// </summary>
    public static Rune CodCloud => new(0xEBAA);

    /// <summary>
    /// cod-cloud_download.
    /// </summary>
    public static Rune CodCloudDownload => new(0xEAC2);

    /// <summary>
    /// cod-cloud_upload.
    /// </summary>
    public static Rune CodCloudUpload => new(0xEAC3);

    /// <summary>
    /// cod-code.
    /// </summary>
    public static Rune CodCode => new(0xEAC4);

    /// <summary>
    /// cod-coffee.
    /// </summary>
    public static Rune CodCoffee => new(0xEC15);

    /// <summary>
    /// cod-collapse_all.
    /// </summary>
    public static Rune CodCollapseAll => new(0xEAC5);

    /// <summary>
    /// cod-color_mode.
    /// </summary>
    public static Rune CodColorMode => new(0xEAC6);

    /// <summary>
    /// cod-combine.
    /// </summary>
    public static Rune CodCombine => new(0xEBB6);

    /// <summary>
    /// cod-comment.
    /// </summary>
    public static Rune CodComment => new(0xEA6B);

    /// <summary>
    /// cod-comment_discussion.
    /// </summary>
    public static Rune CodCommentDiscussion => new(0xEAC7);

    /// <summary>
    /// cod-comment_draft.
    /// </summary>
    public static Rune CodCommentDraft => new(0xEC0E);

    /// <summary>
    /// cod-comment_unresolved.
    /// </summary>
    public static Rune CodCommentUnresolved => new(0xEC0A);

    /// <summary>
    /// cod-compass.
    /// </summary>
    public static Rune CodCompass => new(0xEBD5);

    /// <summary>
    /// cod-compass_active.
    /// </summary>
    public static Rune CodCompassActive => new(0xEBD7);

    /// <summary>
    /// cod-compass_dot.
    /// </summary>
    public static Rune CodCompassDot => new(0xEBD6);

    /// <summary>
    /// cod-copilot.
    /// </summary>
    public static Rune CodCopilot => new(0xEC1E);

    /// <summary>
    /// cod-copy.
    /// </summary>
    public static Rune CodCopy => new(0xEBCC);

    /// <summary>
    /// cod-credit_card.
    /// </summary>
    public static Rune CodCreditCard => new(0xEAC9);

    /// <summary>
    /// cod-dash.
    /// </summary>
    public static Rune CodDash => new(0xEACC);

    /// <summary>
    /// cod-dashboard.
    /// </summary>
    public static Rune CodDashboard => new(0xEACD);

    /// <summary>
    /// cod-database.
    /// </summary>
    public static Rune CodDatabase => new(0xEACE);

    /// <summary>
    /// cod-debug.
    /// </summary>
    public static Rune CodDebug => new(0xEAD8);

    /// <summary>
    /// cod-debug_all.
    /// </summary>
    public static Rune CodDebugAll => new(0xEBDC);

    /// <summary>
    /// cod-debug_alt.
    /// </summary>
    public static Rune CodDebugAlt => new(0xEB91);

    /// <summary>
    /// cod-debug_alt_small.
    /// </summary>
    public static Rune CodDebugAltSmall => new(0xEBA8);

    /// <summary>
    /// cod-debug_breakpoint_conditional.
    /// </summary>
    public static Rune CodDebugBreakpointConditional => new(0xEAA7);

    /// <summary>
    /// cod-debug_breakpoint_conditional_unverified.
    /// </summary>
    public static Rune CodDebugBreakpointConditionalUnverified => new(0xEAA6);

    /// <summary>
    /// cod-debug_breakpoint_data.
    /// </summary>
    public static Rune CodDebugBreakpointData => new(0xEAA9);

    /// <summary>
    /// cod-debug_breakpoint_data_unverified.
    /// </summary>
    public static Rune CodDebugBreakpointDataUnverified => new(0xEAA8);

    /// <summary>
    /// cod-debug_breakpoint_function.
    /// </summary>
    public static Rune CodDebugBreakpointFunction => new(0xEB88);

    /// <summary>
    /// cod-debug_breakpoint_function_unverified.
    /// </summary>
    public static Rune CodDebugBreakpointFunctionUnverified => new(0xEB87);

    /// <summary>
    /// cod-debug_breakpoint_log.
    /// </summary>
    public static Rune CodDebugBreakpointLog => new(0xEAAB);

    /// <summary>
    /// cod-debug_breakpoint_log_unverified.
    /// </summary>
    public static Rune CodDebugBreakpointLogUnverified => new(0xEAAA);

    /// <summary>
    /// cod-debug_breakpoint_unsupported.
    /// </summary>
    public static Rune CodDebugBreakpointUnsupported => new(0xEB8C);

    /// <summary>
    /// cod-debug_console.
    /// </summary>
    public static Rune CodDebugConsole => new(0xEB9B);

    /// <summary>
    /// cod-debug_continue.
    /// </summary>
    public static Rune CodDebugContinue => new(0xEACF);

    /// <summary>
    /// cod-debug_continue_small.
    /// </summary>
    public static Rune CodDebugContinueSmall => new(0xEBE0);

    /// <summary>
    /// cod-debug_coverage.
    /// </summary>
    public static Rune CodDebugCoverage => new(0xEBDD);

    /// <summary>
    /// cod-debug_disconnect.
    /// </summary>
    public static Rune CodDebugDisconnect => new(0xEAD0);

    /// <summary>
    /// cod-debug_line_by_line.
    /// </summary>
    public static Rune CodDebugLineByLine => new(0xEBD0);

    /// <summary>
    /// cod-debug_pause.
    /// </summary>
    public static Rune CodDebugPause => new(0xEAD1);

    /// <summary>
    /// cod-debug_rerun.
    /// </summary>
    public static Rune CodDebugRerun => new(0xEBC0);

    /// <summary>
    /// cod-debug_restart.
    /// </summary>
    public static Rune CodDebugRestart => new(0xEAD2);

    /// <summary>
    /// cod-debug_restart_frame.
    /// </summary>
    public static Rune CodDebugRestartFrame => new(0xEB90);

    /// <summary>
    /// cod-debug_reverse_continue.
    /// </summary>
    public static Rune CodDebugReverseContinue => new(0xEB8E);

    /// <summary>
    /// cod-debug_stackframe.
    /// </summary>
    public static Rune CodDebugStackframe => new(0xEB8B);

    /// <summary>
    /// cod-debug_stackframe_active.
    /// </summary>
    public static Rune CodDebugStackframeActive => new(0xEB89);

    /// <summary>
    /// cod-debug_start.
    /// </summary>
    public static Rune CodDebugStart => new(0xEAD3);

    /// <summary>
    /// cod-debug_step_back.
    /// </summary>
    public static Rune CodDebugStepBack => new(0xEB8F);

    /// <summary>
    /// cod-debug_step_into.
    /// </summary>
    public static Rune CodDebugStepInto => new(0xEAD4);

    /// <summary>
    /// cod-debug_step_out.
    /// </summary>
    public static Rune CodDebugStepOut => new(0xEAD5);

    /// <summary>
    /// cod-debug_step_over.
    /// </summary>
    public static Rune CodDebugStepOver => new(0xEAD6);

    /// <summary>
    /// cod-debug_stop.
    /// </summary>
    public static Rune CodDebugStop => new(0xEAD7);

    /// <summary>
    /// cod-desktop_download.
    /// </summary>
    public static Rune CodDesktopDownload => new(0xEA78);

    /// <summary>
    /// cod-device_camera.
    /// </summary>
    public static Rune CodDeviceCamera => new(0xEADA);

    /// <summary>
    /// cod-device_camera_video.
    /// </summary>
    public static Rune CodDeviceCameraVideo => new(0xEAD9);

    /// <summary>
    /// cod-device_mobile.
    /// </summary>
    public static Rune CodDeviceMobile => new(0xEADB);

    /// <summary>
    /// cod-diff.
    /// </summary>
    public static Rune CodDiff => new(0xEAE1);

    /// <summary>
    /// cod-diff_added.
    /// </summary>
    public static Rune CodDiffAdded => new(0xEADC);

    /// <summary>
    /// cod-diff_ignored.
    /// </summary>
    public static Rune CodDiffIgnored => new(0xEADD);

    /// <summary>
    /// cod-diff_modified.
    /// </summary>
    public static Rune CodDiffModified => new(0xEADE);

    /// <summary>
    /// cod-diff_removed.
    /// </summary>
    public static Rune CodDiffRemoved => new(0xEADF);

    /// <summary>
    /// cod-diff_renamed.
    /// </summary>
    public static Rune CodDiffRenamed => new(0xEAE0);

    /// <summary>
    /// cod-discard.
    /// </summary>
    public static Rune CodDiscard => new(0xEAE2);

    /// <summary>
    /// cod-edit.
    /// </summary>
    public static Rune CodEdit => new(0xEA73);

    /// <summary>
    /// cod-editor_layout.
    /// </summary>
    public static Rune CodEditorLayout => new(0xEAE3);

    /// <summary>
    /// cod-ellipsis.
    /// </summary>
    public static Rune CodEllipsis => new(0xEA7C);

    /// <summary>
    /// cod-empty_window.
    /// </summary>
    public static Rune CodEmptyWindow => new(0xEAE4);

    /// <summary>
    /// cod-error.
    /// </summary>
    public static Rune CodError => new(0xEA87);

    /// <summary>
    /// cod-error_small.
    /// </summary>
    public static Rune CodErrorSmall => new(0xEBFB);

    /// <summary>
    /// cod-exclude.
    /// </summary>
    public static Rune CodExclude => new(0xEAE5);

    /// <summary>
    /// cod-expand_all.
    /// </summary>
    public static Rune CodExpandAll => new(0xEB95);

    /// <summary>
    /// cod-export.
    /// </summary>
    public static Rune CodExport => new(0xEBAC);

    /// <summary>
    /// cod-extensions.
    /// </summary>
    public static Rune CodExtensions => new(0xEAE6);

    /// <summary>
    /// cod-eye.
    /// </summary>
    public static Rune CodEye => new(0xEA70);

    /// <summary>
    /// cod-eye_closed.
    /// </summary>
    public static Rune CodEyeClosed => new(0xEAE7);

    /// <summary>
    /// cod-feedback.
    /// </summary>
    public static Rune CodFeedback => new(0xEB96);

    /// <summary>
    /// cod-file.
    /// </summary>
    public static Rune CodFile => new(0xEA7B);

    /// <summary>
    /// cod-file_binary.
    /// </summary>
    public static Rune CodFileBinary => new(0xEAE8);

    /// <summary>
    /// cod-file_code.
    /// </summary>
    public static Rune CodFileCode => new(0xEAE9);

    /// <summary>
    /// cod-file_media.
    /// </summary>
    public static Rune CodFileMedia => new(0xEAEA);

    /// <summary>
    /// cod-file_pdf.
    /// </summary>
    public static Rune CodFilePdf => new(0xEAEB);

    /// <summary>
    /// cod-file_submodule.
    /// </summary>
    public static Rune CodFileSubmodule => new(0xEAEC);

    /// <summary>
    /// cod-file_symlink_directory.
    /// </summary>
    public static Rune CodFileSymlinkDirectory => new(0xEAED);

    /// <summary>
    /// cod-file_symlink_file.
    /// </summary>
    public static Rune CodFileSymlinkFile => new(0xEAEE);

    /// <summary>
    /// cod-file_zip.
    /// </summary>
    public static Rune CodFileZip => new(0xEAEF);

    /// <summary>
    /// cod-files.
    /// </summary>
    public static Rune CodFiles => new(0xEAF0);

    /// <summary>
    /// cod-filter.
    /// </summary>
    public static Rune CodFilter => new(0xEAF1);

    /// <summary>
    /// cod-filter_filled.
    /// </summary>
    public static Rune CodFilterFilled => new(0xEBCE);

    /// <summary>
    /// cod-flame.
    /// </summary>
    public static Rune CodFlame => new(0xEAF2);

    /// <summary>
    /// cod-fold.
    /// </summary>
    public static Rune CodFold => new(0xEAF5);

    /// <summary>
    /// cod-fold_down.
    /// </summary>
    public static Rune CodFoldDown => new(0xEAF3);

    /// <summary>
    /// cod-fold_up.
    /// </summary>
    public static Rune CodFoldUp => new(0xEAF4);

    /// <summary>
    /// cod-folder.
    /// </summary>
    public static Rune CodFolder => new(0xEA83);

    /// <summary>
    /// cod-folder_active.
    /// </summary>
    public static Rune CodFolderActive => new(0xEAF6);

    /// <summary>
    /// cod-folder_library.
    /// </summary>
    public static Rune CodFolderLibrary => new(0xEBDF);

    /// <summary>
    /// cod-folder_opened.
    /// </summary>
    public static Rune CodFolderOpened => new(0xEAF7);

    /// <summary>
    /// cod-game.
    /// </summary>
    public static Rune CodGame => new(0xEC17);

    /// <summary>
    /// cod-gear.
    /// </summary>
    public static Rune CodGear => new(0xEAF8);

    /// <summary>
    /// cod-gift.
    /// </summary>
    public static Rune CodGift => new(0xEAF9);

    /// <summary>
    /// cod-gist_secret.
    /// </summary>
    public static Rune CodGistSecret => new(0xEAFA);

    /// <summary>
    /// cod-git_commit.
    /// </summary>
    public static Rune CodGitCommit => new(0xEAFC);

    /// <summary>
    /// cod-git_compare.
    /// </summary>
    public static Rune CodGitCompare => new(0xEAFD);

    /// <summary>
    /// cod-git_fetch.
    /// </summary>
    public static Rune CodGitFetch => new(0xEC1D);

    /// <summary>
    /// cod-git_merge.
    /// </summary>
    public static Rune CodGitMerge => new(0xEAFE);

    /// <summary>
    /// cod-git_pull_request.
    /// </summary>
    public static Rune CodGitPullRequest => new(0xEA64);

    /// <summary>
    /// cod-git_pull_request_closed.
    /// </summary>
    public static Rune CodGitPullRequestClosed => new(0xEBDA);

    /// <summary>
    /// cod-git_pull_request_create.
    /// </summary>
    public static Rune CodGitPullRequestCreate => new(0xEBBC);

    /// <summary>
    /// cod-git_pull_request_draft.
    /// </summary>
    public static Rune CodGitPullRequestDraft => new(0xEBDB);

    /// <summary>
    /// cod-git_pull_request_go_to_changes.
    /// </summary>
    public static Rune CodGitPullRequestGoToChanges => new(0xEC0B);

    /// <summary>
    /// cod-git_pull_request_new_changes.
    /// </summary>
    public static Rune CodGitPullRequestNewChanges => new(0xEC0C);

    /// <summary>
    /// cod-github.
    /// </summary>
    public static Rune CodGithub => new(0xEA84);

    /// <summary>
    /// cod-github_action.
    /// </summary>
    public static Rune CodGithubAction => new(0xEAFF);

    /// <summary>
    /// cod-github_alt.
    /// </summary>
    public static Rune CodGithubAlt => new(0xEB00);

    /// <summary>
    /// cod-github_inverted.
    /// </summary>
    public static Rune CodGithubInverted => new(0xEBA1);

    /// <summary>
    /// cod-globe.
    /// </summary>
    public static Rune CodGlobe => new(0xEB01);

    /// <summary>
    /// cod-go_to_file.
    /// </summary>
    public static Rune CodGoToFile => new(0xEA94);

    /// <summary>
    /// cod-grabber.
    /// </summary>
    public static Rune CodGrabber => new(0xEB02);

    /// <summary>
    /// cod-graph.
    /// </summary>
    public static Rune CodGraph => new(0xEB03);

    /// <summary>
    /// cod-graph_left.
    /// </summary>
    public static Rune CodGraphLeft => new(0xEBAD);

    /// <summary>
    /// cod-graph_line.
    /// </summary>
    public static Rune CodGraphLine => new(0xEBE2);

    /// <summary>
    /// cod-graph_scatter.
    /// </summary>
    public static Rune CodGraphScatter => new(0xEBE3);

    /// <summary>
    /// cod-gripper.
    /// </summary>
    public static Rune CodGripper => new(0xEB04);

    /// <summary>
    /// cod-group_by_ref_type.
    /// </summary>
    public static Rune CodGroupByRefType => new(0xEB97);

    /// <summary>
    /// cod-heart.
    /// </summary>
    public static Rune CodHeart => new(0xEB05);

    /// <summary>
    /// cod-heart_filled.
    /// </summary>
    public static Rune CodHeartFilled => new(0xEC04);

    /// <summary>
    /// cod-history.
    /// </summary>
    public static Rune CodHistory => new(0xEA82);

    /// <summary>
    /// cod-home.
    /// </summary>
    public static Rune CodHome => new(0xEB06);

    /// <summary>
    /// cod-horizontal_rule.
    /// </summary>
    public static Rune CodHorizontalRule => new(0xEB07);

    /// <summary>
    /// cod-hubot.
    /// </summary>
    public static Rune CodHubot => new(0xEB08);

    /// <summary>
    /// cod-inbox.
    /// </summary>
    public static Rune CodInbox => new(0xEB09);

    /// <summary>
    /// cod-indent.
    /// </summary>
    public static Rune CodIndent => new(0xEBF9);

    /// <summary>
    /// cod-info.
    /// </summary>
    public static Rune CodInfo => new(0xEA74);

    /// <summary>
    /// cod-insert.
    /// </summary>
    public static Rune CodInsert => new(0xEC11);

    /// <summary>
    /// cod-inspect.
    /// </summary>
    public static Rune CodInspect => new(0xEBD1);

    /// <summary>
    /// cod-issue_draft.
    /// </summary>
    public static Rune CodIssueDraft => new(0xEBD9);

    /// <summary>
    /// cod-issue_reopened.
    /// </summary>
    public static Rune CodIssueReopened => new(0xEB0B);

    /// <summary>
    /// cod-issues.
    /// </summary>
    public static Rune CodIssues => new(0xEB0C);

    /// <summary>
    /// cod-italic.
    /// </summary>
    public static Rune CodItalic => new(0xEB0D);

    /// <summary>
    /// cod-jersey.
    /// </summary>
    public static Rune CodJersey => new(0xEB0E);

    /// <summary>
    /// cod-json.
    /// </summary>
    public static Rune CodJson => new(0xEB0F);

    /// <summary>
    /// cod-kebab_vertical.
    /// </summary>
    public static Rune CodKebabVertical => new(0xEB10);

    /// <summary>
    /// cod-key.
    /// </summary>
    public static Rune CodKey => new(0xEB11);

    /// <summary>
    /// cod-law.
    /// </summary>
    public static Rune CodLaw => new(0xEB12);

    /// <summary>
    /// cod-layers.
    /// </summary>
    public static Rune CodLayers => new(0xEBD2);

    /// <summary>
    /// cod-layers_active.
    /// </summary>
    public static Rune CodLayersActive => new(0xEBD4);

    /// <summary>
    /// cod-layers_dot.
    /// </summary>
    public static Rune CodLayersDot => new(0xEBD3);

    /// <summary>
    /// cod-layout.
    /// </summary>
    public static Rune CodLayout => new(0xEBEB);

    /// <summary>
    /// cod-layout_activitybar_left.
    /// </summary>
    public static Rune CodLayoutActivitybarLeft => new(0xEBEC);

    /// <summary>
    /// cod-layout_activitybar_right.
    /// </summary>
    public static Rune CodLayoutActivitybarRight => new(0xEBED);

    /// <summary>
    /// cod-layout_centered.
    /// </summary>
    public static Rune CodLayoutCentered => new(0xEBF7);

    /// <summary>
    /// cod-layout_menubar.
    /// </summary>
    public static Rune CodLayoutMenubar => new(0xEBF6);

    /// <summary>
    /// cod-layout_panel.
    /// </summary>
    public static Rune CodLayoutPanel => new(0xEBF2);

    /// <summary>
    /// cod-layout_panel_center.
    /// </summary>
    public static Rune CodLayoutPanelCenter => new(0xEBEF);

    /// <summary>
    /// cod-layout_panel_justify.
    /// </summary>
    public static Rune CodLayoutPanelJustify => new(0xEBF0);

    /// <summary>
    /// cod-layout_panel_left.
    /// </summary>
    public static Rune CodLayoutPanelLeft => new(0xEBEE);

    /// <summary>
    /// cod-layout_panel_off.
    /// </summary>
    public static Rune CodLayoutPanelOff => new(0xEC01);

    /// <summary>
    /// cod-layout_panel_right.
    /// </summary>
    public static Rune CodLayoutPanelRight => new(0xEBF1);

    /// <summary>
    /// cod-layout_sidebar_left.
    /// </summary>
    public static Rune CodLayoutSidebarLeft => new(0xEBF3);

    /// <summary>
    /// cod-layout_sidebar_left_off.
    /// </summary>
    public static Rune CodLayoutSidebarLeftOff => new(0xEC02);

    /// <summary>
    /// cod-layout_sidebar_right.
    /// </summary>
    public static Rune CodLayoutSidebarRight => new(0xEBF4);

    /// <summary>
    /// cod-layout_sidebar_right_off.
    /// </summary>
    public static Rune CodLayoutSidebarRightOff => new(0xEC00);

    /// <summary>
    /// cod-layout_statusbar.
    /// </summary>
    public static Rune CodLayoutStatusbar => new(0xEBF5);

    /// <summary>
    /// cod-library.
    /// </summary>
    public static Rune CodLibrary => new(0xEB9C);

    /// <summary>
    /// cod-lightbulb.
    /// </summary>
    public static Rune CodLightbulb => new(0xEA61);

    /// <summary>
    /// cod-lightbulb_autofix.
    /// </summary>
    public static Rune CodLightbulbAutofix => new(0xEB13);

    /// <summary>
    /// cod-link.
    /// </summary>
    public static Rune CodLink => new(0xEB15);

    /// <summary>
    /// cod-link_external.
    /// </summary>
    public static Rune CodLinkExternal => new(0xEB14);

    /// <summary>
    /// cod-list_filter.
    /// </summary>
    public static Rune CodListFilter => new(0xEB83);

    /// <summary>
    /// cod-list_flat.
    /// </summary>
    public static Rune CodListFlat => new(0xEB84);

    /// <summary>
    /// cod-list_ordered.
    /// </summary>
    public static Rune CodListOrdered => new(0xEB16);

    /// <summary>
    /// cod-list_selection.
    /// </summary>
    public static Rune CodListSelection => new(0xEB85);

    /// <summary>
    /// cod-list_tree.
    /// </summary>
    public static Rune CodListTree => new(0xEB86);

    /// <summary>
    /// cod-list_unordered.
    /// </summary>
    public static Rune CodListUnordered => new(0xEB17);

    /// <summary>
    /// cod-live_share.
    /// </summary>
    public static Rune CodLiveShare => new(0xEB18);

    /// <summary>
    /// cod-loading.
    /// </summary>
    public static Rune CodLoading => new(0xEB19);

    /// <summary>
    /// cod-location.
    /// </summary>
    public static Rune CodLocation => new(0xEB1A);

    /// <summary>
    /// cod-lock.
    /// </summary>
    public static Rune CodLock => new(0xEA75);

    /// <summary>
    /// cod-lock_small.
    /// </summary>
    public static Rune CodLockSmall => new(0xEBE7);

    /// <summary>
    /// cod-magnet.
    /// </summary>
    public static Rune CodMagnet => new(0xEBAE);

    /// <summary>
    /// cod-mail.
    /// </summary>
    public static Rune CodMail => new(0xEB1C);

    /// <summary>
    /// cod-mail_read.
    /// </summary>
    public static Rune CodMailRead => new(0xEB1B);

    /// <summary>
    /// cod-map.
    /// </summary>
    public static Rune CodMap => new(0xEC05);

    /// <summary>
    /// cod-map_filled.
    /// </summary>
    public static Rune CodMapFilled => new(0xEC06);

    /// <summary>
    /// cod-markdown.
    /// </summary>
    public static Rune CodMarkdown => new(0xEB1D);

    /// <summary>
    /// cod-megaphone.
    /// </summary>
    public static Rune CodMegaphone => new(0xEB1E);

    /// <summary>
    /// cod-mention.
    /// </summary>
    public static Rune CodMention => new(0xEB1F);

    /// <summary>
    /// cod-menu.
    /// </summary>
    public static Rune CodMenu => new(0xEB94);

    /// <summary>
    /// cod-merge.
    /// </summary>
    public static Rune CodMerge => new(0xEBAB);

    /// <summary>
    /// cod-mic.
    /// </summary>
    public static Rune CodMic => new(0xEC12);

    /// <summary>
    /// cod-mic_filled.
    /// </summary>
    public static Rune CodMicFilled => new(0xEC1C);

    /// <summary>
    /// cod-milestone.
    /// </summary>
    public static Rune CodMilestone => new(0xEB20);

    /// <summary>
    /// cod-mirror.
    /// </summary>
    public static Rune CodMirror => new(0xEA69);

    /// <summary>
    /// cod-mortar_board.
    /// </summary>
    public static Rune CodMortarBoard => new(0xEB21);

    /// <summary>
    /// cod-move.
    /// </summary>
    public static Rune CodMove => new(0xEB22);

    /// <summary>
    /// cod-multiple_windows.
    /// </summary>
    public static Rune CodMultipleWindows => new(0xEB23);

    /// <summary>
    /// cod-music.
    /// </summary>
    public static Rune CodMusic => new(0xEC1B);

    /// <summary>
    /// cod-mute.
    /// </summary>
    public static Rune CodMute => new(0xEB24);

    /// <summary>
    /// cod-new_file.
    /// </summary>
    public static Rune CodNewFile => new(0xEA7F);

    /// <summary>
    /// cod-new_folder.
    /// </summary>
    public static Rune CodNewFolder => new(0xEA80);

    /// <summary>
    /// cod-newline.
    /// </summary>
    public static Rune CodNewline => new(0xEBEA);

    /// <summary>
    /// cod-no_newline.
    /// </summary>
    public static Rune CodNoNewline => new(0xEB25);

    /// <summary>
    /// cod-note.
    /// </summary>
    public static Rune CodNote => new(0xEB26);

    /// <summary>
    /// cod-notebook.
    /// </summary>
    public static Rune CodNotebook => new(0xEBAF);

    /// <summary>
    /// cod-notebook_template.
    /// </summary>
    public static Rune CodNotebookTemplate => new(0xEBBF);

    /// <summary>
    /// cod-octoface.
    /// </summary>
    public static Rune CodOctoface => new(0xEB27);

    /// <summary>
    /// cod-open_preview.
    /// </summary>
    public static Rune CodOpenPreview => new(0xEB28);

    /// <summary>
    /// cod-organization.
    /// </summary>
    public static Rune CodOrganization => new(0xEA7E);

    /// <summary>
    /// cod-output.
    /// </summary>
    public static Rune CodOutput => new(0xEB9D);

    /// <summary>
    /// cod-package.
    /// </summary>
    public static Rune CodPackage => new(0xEB29);

    /// <summary>
    /// cod-paintcan.
    /// </summary>
    public static Rune CodPaintcan => new(0xEB2A);

    /// <summary>
    /// cod-pass.
    /// </summary>
    public static Rune CodPass => new(0xEBA4);

    /// <summary>
    /// cod-pass_filled.
    /// </summary>
    public static Rune CodPassFilled => new(0xEBB3);

    /// <summary>
    /// cod-person.
    /// </summary>
    public static Rune CodPerson => new(0xEA67);

    /// <summary>
    /// cod-person_add.
    /// </summary>
    public static Rune CodPersonAdd => new(0xEBCD);

    /// <summary>
    /// cod-piano.
    /// </summary>
    public static Rune CodPiano => new(0xEC1A);

    /// <summary>
    /// cod-pie_chart.
    /// </summary>
    public static Rune CodPieChart => new(0xEBE4);

    /// <summary>
    /// cod-pin.
    /// </summary>
    public static Rune CodPin => new(0xEB2B);

    /// <summary>
    /// cod-pinned.
    /// </summary>
    public static Rune CodPinned => new(0xEBA0);

    /// <summary>
    /// cod-pinned_dirty.
    /// </summary>
    public static Rune CodPinnedDirty => new(0xEBB2);

    /// <summary>
    /// cod-play.
    /// </summary>
    public static Rune CodPlay => new(0xEB2C);

    /// <summary>
    /// cod-play_circle.
    /// </summary>
    public static Rune CodPlayCircle => new(0xEBA6);

    /// <summary>
    /// cod-plug.
    /// </summary>
    public static Rune CodPlug => new(0xEB2D);

    /// <summary>
    /// cod-preserve_case.
    /// </summary>
    public static Rune CodPreserveCase => new(0xEB2E);

    /// <summary>
    /// cod-preview.
    /// </summary>
    public static Rune CodPreview => new(0xEB2F);

    /// <summary>
    /// cod-primitive_square.
    /// </summary>
    public static Rune CodPrimitiveSquare => new(0xEA72);

    /// <summary>
    /// cod-project.
    /// </summary>
    public static Rune CodProject => new(0xEB30);

    /// <summary>
    /// cod-pulse.
    /// </summary>
    public static Rune CodPulse => new(0xEB31);

    /// <summary>
    /// cod-question.
    /// </summary>
    public static Rune CodQuestion => new(0xEB32);

    /// <summary>
    /// cod-quote.
    /// </summary>
    public static Rune CodQuote => new(0xEB33);

    /// <summary>
    /// cod-radio_tower.
    /// </summary>
    public static Rune CodRadioTower => new(0xEB34);

    /// <summary>
    /// cod-reactions.
    /// </summary>
    public static Rune CodReactions => new(0xEB35);

    /// <summary>
    /// cod-record.
    /// </summary>
    public static Rune CodRecord => new(0xEBA7);

    /// <summary>
    /// cod-record_keys.
    /// </summary>
    public static Rune CodRecordKeys => new(0xEA65);

    /// <summary>
    /// cod-record_small.
    /// </summary>
    public static Rune CodRecordSmall => new(0xEBFA);

    /// <summary>
    /// cod-redo.
    /// </summary>
    public static Rune CodRedo => new(0xEBB0);

    /// <summary>
    /// cod-references.
    /// </summary>
    public static Rune CodReferences => new(0xEB36);

    /// <summary>
    /// cod-refresh.
    /// </summary>
    public static Rune CodRefresh => new(0xEB37);

    /// <summary>
    /// cod-regex.
    /// </summary>
    public static Rune CodRegex => new(0xEB38);

    /// <summary>
    /// cod-remote.
    /// </summary>
    public static Rune CodRemote => new(0xEB3A);

    /// <summary>
    /// cod-remote_explorer.
    /// </summary>
    public static Rune CodRemoteExplorer => new(0xEB39);

    /// <summary>
    /// cod-remove.
    /// </summary>
    public static Rune CodRemove => new(0xEB3B);

    /// <summary>
    /// cod-replace.
    /// </summary>
    public static Rune CodReplace => new(0xEB3D);

    /// <summary>
    /// cod-replace_all.
    /// </summary>
    public static Rune CodReplaceAll => new(0xEB3C);

    /// <summary>
    /// cod-reply.
    /// </summary>
    public static Rune CodReply => new(0xEA7D);

    /// <summary>
    /// cod-repo.
    /// </summary>
    public static Rune CodRepo => new(0xEA62);

    /// <summary>
    /// cod-repo_clone.
    /// </summary>
    public static Rune CodRepoClone => new(0xEB3E);

    /// <summary>
    /// cod-repo_force_push.
    /// </summary>
    public static Rune CodRepoForcePush => new(0xEB3F);

    /// <summary>
    /// cod-repo_forked.
    /// </summary>
    public static Rune CodRepoForked => new(0xEA63);

    /// <summary>
    /// cod-repo_pull.
    /// </summary>
    public static Rune CodRepoPull => new(0xEB40);

    /// <summary>
    /// cod-repo_push.
    /// </summary>
    public static Rune CodRepoPush => new(0xEB41);

    /// <summary>
    /// cod-report.
    /// </summary>
    public static Rune CodReport => new(0xEB42);

    /// <summary>
    /// cod-request_changes.
    /// </summary>
    public static Rune CodRequestChanges => new(0xEB43);

    /// <summary>
    /// cod-rocket.
    /// </summary>
    public static Rune CodRocket => new(0xEB44);

    /// <summary>
    /// cod-root_folder.
    /// </summary>
    public static Rune CodRootFolder => new(0xEB46);

    /// <summary>
    /// cod-root_folder_opened.
    /// </summary>
    public static Rune CodRootFolderOpened => new(0xEB45);

    /// <summary>
    /// cod-rss.
    /// </summary>
    public static Rune CodRss => new(0xEB47);

    /// <summary>
    /// cod-ruby.
    /// </summary>
    public static Rune CodRuby => new(0xEB48);

    /// <summary>
    /// cod-run_above.
    /// </summary>
    public static Rune CodRunAbove => new(0xEBBD);

    /// <summary>
    /// cod-run_all.
    /// </summary>
    public static Rune CodRunAll => new(0xEB9E);

    /// <summary>
    /// cod-run_below.
    /// </summary>
    public static Rune CodRunBelow => new(0xEBBE);

    /// <summary>
    /// cod-run_errors.
    /// </summary>
    public static Rune CodRunErrors => new(0xEBDE);

    /// <summary>
    /// cod-save.
    /// </summary>
    public static Rune CodSave => new(0xEB4B);

    /// <summary>
    /// cod-save_all.
    /// </summary>
    public static Rune CodSaveAll => new(0xEB49);

    /// <summary>
    /// cod-save_as.
    /// </summary>
    public static Rune CodSaveAs => new(0xEB4A);

    /// <summary>
    /// cod-screen_full.
    /// </summary>
    public static Rune CodScreenFull => new(0xEB4C);

    /// <summary>
    /// cod-screen_normal.
    /// </summary>
    public static Rune CodScreenNormal => new(0xEB4D);

    /// <summary>
    /// cod-search.
    /// </summary>
    public static Rune CodSearch => new(0xEA6D);

    /// <summary>
    /// cod-search_fuzzy.
    /// </summary>
    public static Rune CodSearchFuzzy => new(0xEC0D);

    /// <summary>
    /// cod-search_stop.
    /// </summary>
    public static Rune CodSearchStop => new(0xEB4E);

    /// <summary>
    /// cod-send.
    /// </summary>
    public static Rune CodSend => new(0xEC0F);

    /// <summary>
    /// cod-server.
    /// </summary>
    public static Rune CodServer => new(0xEB50);

    /// <summary>
    /// cod-server_environment.
    /// </summary>
    public static Rune CodServerEnvironment => new(0xEBA3);

    /// <summary>
    /// cod-server_process.
    /// </summary>
    public static Rune CodServerProcess => new(0xEBA2);

    /// <summary>
    /// cod-settings.
    /// </summary>
    public static Rune CodSettings => new(0xEB52);

    /// <summary>
    /// cod-settings_gear.
    /// </summary>
    public static Rune CodSettingsGear => new(0xEB51);

    /// <summary>
    /// cod-shield.
    /// </summary>
    public static Rune CodShield => new(0xEB53);

    /// <summary>
    /// cod-sign_in.
    /// </summary>
    public static Rune CodSignIn => new(0xEA6F);

    /// <summary>
    /// cod-sign_out.
    /// </summary>
    public static Rune CodSignOut => new(0xEA6E);

    /// <summary>
    /// cod-smiley.
    /// </summary>
    public static Rune CodSmiley => new(0xEB54);

    /// <summary>
    /// cod-snake.
    /// </summary>
    public static Rune CodSnake => new(0xEC16);

    /// <summary>
    /// cod-sort_precedence.
    /// </summary>
    public static Rune CodSortPrecedence => new(0xEB55);

    /// <summary>
    /// cod-source_control.
    /// </summary>
    public static Rune CodSourceControl => new(0xEA68);

    /// <summary>
    /// cod-sparkle.
    /// </summary>
    public static Rune CodSparkle => new(0xEC10);

    /// <summary>
    /// cod-split_horizontal.
    /// </summary>
    public static Rune CodSplitHorizontal => new(0xEB56);

    /// <summary>
    /// cod-split_vertical.
    /// </summary>
    public static Rune CodSplitVertical => new(0xEB57);

    /// <summary>
    /// cod-squirrel.
    /// </summary>
    public static Rune CodSquirrel => new(0xEB58);

    /// <summary>
    /// cod-star_empty.
    /// </summary>
    public static Rune CodStarEmpty => new(0xEA6A);

    /// <summary>
    /// cod-star_full.
    /// </summary>
    public static Rune CodStarFull => new(0xEB59);

    /// <summary>
    /// cod-star_half.
    /// </summary>
    public static Rune CodStarHalf => new(0xEB5A);

    /// <summary>
    /// cod-stop_circle.
    /// </summary>
    public static Rune CodStopCircle => new(0xEBA5);

    /// <summary>
    /// cod-symbol_array.
    /// </summary>
    public static Rune CodSymbolArray => new(0xEA8A);

    /// <summary>
    /// cod-symbol_boolean.
    /// </summary>
    public static Rune CodSymbolBoolean => new(0xEA8F);

    /// <summary>
    /// cod-symbol_class.
    /// </summary>
    public static Rune CodSymbolClass => new(0xEB5B);

    /// <summary>
    /// cod-symbol_color.
    /// </summary>
    public static Rune CodSymbolColor => new(0xEB5C);

    /// <summary>
    /// cod-symbol_constant.
    /// </summary>
    public static Rune CodSymbolConstant => new(0xEB5D);

    /// <summary>
    /// cod-symbol_enum.
    /// </summary>
    public static Rune CodSymbolEnum => new(0xEA95);

    /// <summary>
    /// cod-symbol_enum_member.
    /// </summary>
    public static Rune CodSymbolEnumMember => new(0xEB5E);

    /// <summary>
    /// cod-symbol_event.
    /// </summary>
    public static Rune CodSymbolEvent => new(0xEA86);

    /// <summary>
    /// cod-symbol_field.
    /// </summary>
    public static Rune CodSymbolField => new(0xEB5F);

    /// <summary>
    /// cod-symbol_file.
    /// </summary>
    public static Rune CodSymbolFile => new(0xEB60);

    /// <summary>
    /// cod-symbol_interface.
    /// </summary>
    public static Rune CodSymbolInterface => new(0xEB61);

    /// <summary>
    /// cod-symbol_key.
    /// </summary>
    public static Rune CodSymbolKey => new(0xEA93);

    /// <summary>
    /// cod-symbol_keyword.
    /// </summary>
    public static Rune CodSymbolKeyword => new(0xEB62);

    /// <summary>
    /// cod-symbol_method.
    /// </summary>
    public static Rune CodSymbolMethod => new(0xEA8C);

    /// <summary>
    /// cod-symbol_misc.
    /// </summary>
    public static Rune CodSymbolMisc => new(0xEB63);

    /// <summary>
    /// cod-symbol_namespace.
    /// </summary>
    public static Rune CodSymbolNamespace => new(0xEA8B);

    /// <summary>
    /// cod-symbol_numeric.
    /// </summary>
    public static Rune CodSymbolNumeric => new(0xEA90);

    /// <summary>
    /// cod-symbol_operator.
    /// </summary>
    public static Rune CodSymbolOperator => new(0xEB64);

    /// <summary>
    /// cod-symbol_parameter.
    /// </summary>
    public static Rune CodSymbolParameter => new(0xEA92);

    /// <summary>
    /// cod-symbol_property.
    /// </summary>
    public static Rune CodSymbolProperty => new(0xEB65);

    /// <summary>
    /// cod-symbol_ruler.
    /// </summary>
    public static Rune CodSymbolRuler => new(0xEA96);

    /// <summary>
    /// cod-symbol_snippet.
    /// </summary>
    public static Rune CodSymbolSnippet => new(0xEB66);

    /// <summary>
    /// cod-symbol_string.
    /// </summary>
    public static Rune CodSymbolString => new(0xEB8D);

    /// <summary>
    /// cod-symbol_structure.
    /// </summary>
    public static Rune CodSymbolStructure => new(0xEA91);

    /// <summary>
    /// cod-symbol_variable.
    /// </summary>
    public static Rune CodSymbolVariable => new(0xEA88);

    /// <summary>
    /// cod-sync.
    /// </summary>
    public static Rune CodSync => new(0xEA77);

    /// <summary>
    /// cod-sync_ignored.
    /// </summary>
    public static Rune CodSyncIgnored => new(0xEB9F);

    /// <summary>
    /// cod-table.
    /// </summary>
    public static Rune CodTable => new(0xEBB7);

    /// <summary>
    /// cod-tag.
    /// </summary>
    public static Rune CodTag => new(0xEA66);

    /// <summary>
    /// cod-target.
    /// </summary>
    public static Rune CodTarget => new(0xEBF8);

    /// <summary>
    /// cod-tasklist.
    /// </summary>
    public static Rune CodTasklist => new(0xEB67);

    /// <summary>
    /// cod-telescope.
    /// </summary>
    public static Rune CodTelescope => new(0xEB68);

    /// <summary>
    /// cod-terminal.
    /// </summary>
    public static Rune CodTerminal => new(0xEA85);

    /// <summary>
    /// cod-terminal_bash.
    /// </summary>
    public static Rune CodTerminalBash => new(0xEBCA);

    /// <summary>
    /// cod-terminal_cmd.
    /// </summary>
    public static Rune CodTerminalCmd => new(0xEBC4);

    /// <summary>
    /// cod-terminal_debian.
    /// </summary>
    public static Rune CodTerminalDebian => new(0xEBC5);

    /// <summary>
    /// cod-terminal_linux.
    /// </summary>
    public static Rune CodTerminalLinux => new(0xEBC6);

    /// <summary>
    /// cod-terminal_powershell.
    /// </summary>
    public static Rune CodTerminalPowershell => new(0xEBC7);

    /// <summary>
    /// cod-terminal_tmux.
    /// </summary>
    public static Rune CodTerminalTmux => new(0xEBC8);

    /// <summary>
    /// cod-terminal_ubuntu.
    /// </summary>
    public static Rune CodTerminalUbuntu => new(0xEBC9);

    /// <summary>
    /// cod-text_size.
    /// </summary>
    public static Rune CodTextSize => new(0xEB69);

    /// <summary>
    /// cod-three_bars.
    /// </summary>
    public static Rune CodThreeBars => new(0xEB6A);

    /// <summary>
    /// cod-thumbsdown.
    /// </summary>
    public static Rune CodThumbsdown => new(0xEB6B);

    /// <summary>
    /// cod-thumbsdown_filled.
    /// </summary>
    public static Rune CodThumbsdownFilled => new(0xEC13);

    /// <summary>
    /// cod-thumbsup.
    /// </summary>
    public static Rune CodThumbsup => new(0xEB6C);

    /// <summary>
    /// cod-thumbsup_filled.
    /// </summary>
    public static Rune CodThumbsupFilled => new(0xEC14);

    /// <summary>
    /// cod-tools.
    /// </summary>
    public static Rune CodTools => new(0xEB6D);

    /// <summary>
    /// cod-trash.
    /// </summary>
    public static Rune CodTrash => new(0xEA81);

    /// <summary>
    /// cod-triangle_down.
    /// </summary>
    public static Rune CodTriangleDown => new(0xEB6E);

    /// <summary>
    /// cod-triangle_left.
    /// </summary>
    public static Rune CodTriangleLeft => new(0xEB6F);

    /// <summary>
    /// cod-triangle_right.
    /// </summary>
    public static Rune CodTriangleRight => new(0xEB70);

    /// <summary>
    /// cod-triangle_up.
    /// </summary>
    public static Rune CodTriangleUp => new(0xEB71);

    /// <summary>
    /// cod-twitter.
    /// </summary>
    public static Rune CodTwitter => new(0xEB72);

    /// <summary>
    /// cod-type_hierarchy.
    /// </summary>
    public static Rune CodTypeHierarchy => new(0xEBB9);

    /// <summary>
    /// cod-type_hierarchy_sub.
    /// </summary>
    public static Rune CodTypeHierarchySub => new(0xEBBA);

    /// <summary>
    /// cod-type_hierarchy_super.
    /// </summary>
    public static Rune CodTypeHierarchySuper => new(0xEBBB);

    /// <summary>
    /// cod-unfold.
    /// </summary>
    public static Rune CodUnfold => new(0xEB73);

    /// <summary>
    /// cod-ungroup_by_ref_type.
    /// </summary>
    public static Rune CodUngroupByRefType => new(0xEB98);

    /// <summary>
    /// cod-unlock.
    /// </summary>
    public static Rune CodUnlock => new(0xEB74);

    /// <summary>
    /// cod-unmute.
    /// </summary>
    public static Rune CodUnmute => new(0xEB75);

    /// <summary>
    /// cod-unverified.
    /// </summary>
    public static Rune CodUnverified => new(0xEB76);

    /// <summary>
    /// cod-variable_group.
    /// </summary>
    public static Rune CodVariableGroup => new(0xEBB8);

    /// <summary>
    /// cod-verified.
    /// </summary>
    public static Rune CodVerified => new(0xEB77);

    /// <summary>
    /// cod-verified_filled.
    /// </summary>
    public static Rune CodVerifiedFilled => new(0xEBE9);

    /// <summary>
    /// cod-versions.
    /// </summary>
    public static Rune CodVersions => new(0xEB78);

    /// <summary>
    /// cod-vm.
    /// </summary>
    public static Rune CodVm => new(0xEA7A);

    /// <summary>
    /// cod-vm_active.
    /// </summary>
    public static Rune CodVmActive => new(0xEB79);

    /// <summary>
    /// cod-vm_connect.
    /// </summary>
    public static Rune CodVmConnect => new(0xEBA9);

    /// <summary>
    /// cod-vm_outline.
    /// </summary>
    public static Rune CodVmOutline => new(0xEB7A);

    /// <summary>
    /// cod-vm_running.
    /// </summary>
    public static Rune CodVmRunning => new(0xEB7B);

    /// <summary>
    /// cod-vr.
    /// </summary>
    public static Rune CodVr => new(0xEC18);

    /// <summary>
    /// cod-wand.
    /// </summary>
    public static Rune CodWand => new(0xEBCF);

    /// <summary>
    /// cod-warning.
    /// </summary>
    public static Rune CodWarning => new(0xEA6C);

    /// <summary>
    /// cod-watch.
    /// </summary>
    public static Rune CodWatch => new(0xEB7C);

    /// <summary>
    /// cod-whitespace.
    /// </summary>
    public static Rune CodWhitespace => new(0xEB7D);

    /// <summary>
    /// cod-whole_word.
    /// </summary>
    public static Rune CodWholeWord => new(0xEB7E);

    /// <summary>
    /// cod-window.
    /// </summary>
    public static Rune CodWindow => new(0xEB7F);

    /// <summary>
    /// cod-word_wrap.
    /// </summary>
    public static Rune CodWordWrap => new(0xEB80);

    /// <summary>
    /// cod-workspace_trusted.
    /// </summary>
    public static Rune CodWorkspaceTrusted => new(0xEBC1);

    /// <summary>
    /// cod-workspace_unknown.
    /// </summary>
    public static Rune CodWorkspaceUnknown => new(0xEBC3);

    /// <summary>
    /// cod-workspace_untrusted.
    /// </summary>
    public static Rune CodWorkspaceUntrusted => new(0xEBC2);

    /// <summary>
    /// cod-zoom_in.
    /// </summary>
    public static Rune CodZoomIn => new(0xEB81);

    /// <summary>
    /// cod-zoom_out.
    /// </summary>
    public static Rune CodZoomOut => new(0xEB82);

}
