// <auto-generated />

using System.Text;

namespace XenoAtom.Terminal.UI;

public static partial class NerdFont
{
    /// <summary>
    /// custom-ada.
    /// </summary>
    public static Rune CustomAda => new(0xE6B5);

    /// <summary>
    /// custom-asm.
    /// </summary>
    public static Rune CustomAsm => new(0xE6AB);

    /// <summary>
    /// custom-astro.
    /// </summary>
    public static Rune CustomAstro => new(0xE6B3);

    /// <summary>
    /// custom-bazel.
    /// </summary>
    public static Rune CustomBazel => new(0xE63A);

    /// <summary>
    /// custom-c.
    /// </summary>
    public static Rune CustomC => new(0xE61E);

    /// <summary>
    /// custom-chuck.
    /// </summary>
    public static Rune CustomChuck => new(0xE6B6);

    /// <summary>
    /// custom-common_lisp.
    /// </summary>
    public static Rune CustomCommonLisp => new(0xE6B0);

    /// <summary>
    /// custom-cpp.
    /// </summary>
    public static Rune CustomCpp => new(0xE61D);

    /// <summary>
    /// custom-crystal.
    /// </summary>
    public static Rune CustomCrystal => new(0xE62F);

    /// <summary>
    /// custom-css.
    /// </summary>
    public static Rune CustomCss => new(0xE6B8);

    /// <summary>
    /// custom-default.
    /// </summary>
    public static Rune CustomDefault => new(0xE612);

    /// <summary>
    /// custom-electron.
    /// </summary>
    public static Rune CustomElectron => new(0xE62E);

    /// <summary>
    /// custom-elixir.
    /// </summary>
    public static Rune CustomElixir => new(0xE62D);

    /// <summary>
    /// custom-elm.
    /// </summary>
    public static Rune CustomElm => new(0xE62C);

    /// <summary>
    /// custom-emacs.
    /// </summary>
    public static Rune CustomEmacs => new(0xE632);

    /// <summary>
    /// custom-fennel.
    /// </summary>
    public static Rune CustomFennel => new(0xE6AF);

    /// <summary>
    /// custom-firebase.
    /// </summary>
    public static Rune CustomFirebase => new(0xE657);

    /// <summary>
    /// custom-folder.
    /// </summary>
    public static Rune CustomFolder => new(0xE5FF);

    /// <summary>
    /// custom-folder_config.
    /// </summary>
    public static Rune CustomFolderConfig => new(0xE5FC);

    /// <summary>
    /// custom-folder_git.
    /// </summary>
    public static Rune CustomFolderGit => new(0xE5FB);

    /// <summary>
    /// custom-folder_git_branch.
    /// </summary>
    public static Rune CustomFolderGitBranch => new(0xE5FB);

    /// <summary>
    /// custom-folder_github.
    /// </summary>
    public static Rune CustomFolderGithub => new(0xE5FD);

    /// <summary>
    /// custom-folder_npm.
    /// </summary>
    public static Rune CustomFolderNpm => new(0xE5FA);

    /// <summary>
    /// custom-folder_oct.
    /// </summary>
    public static Rune CustomFolderOct => new(0xE6AD);

    /// <summary>
    /// custom-folder_open.
    /// </summary>
    public static Rune CustomFolderOpen => new(0xE5FE);

    /// <summary>
    /// custom-go.
    /// </summary>
    public static Rune CustomGo => new(0xE626);

    /// <summary>
    /// custom-home.
    /// </summary>
    public static Rune CustomHome => new(0xE617);

    /// <summary>
    /// custom-kotlin.
    /// </summary>
    public static Rune CustomKotlin => new(0xE634);

    /// <summary>
    /// custom-msdos.
    /// </summary>
    public static Rune CustomMsdos => new(0xE629);

    /// <summary>
    /// custom-neovim.
    /// </summary>
    public static Rune CustomNeovim => new(0xE6AE);

    /// <summary>
    /// custom-orgmode.
    /// </summary>
    public static Rune CustomOrgmode => new(0xE633);

    /// <summary>
    /// custom-play_arrow.
    /// </summary>
    public static Rune CustomPlayArrow => new(0xE602);

    /// <summary>
    /// custom-prettier.
    /// </summary>
    public static Rune CustomPrettier => new(0xE6B4);

    /// <summary>
    /// custom-puppet.
    /// </summary>
    public static Rune CustomPuppet => new(0xE631);

    /// <summary>
    /// custom-purescript.
    /// </summary>
    public static Rune CustomPurescript => new(0xE630);

    /// <summary>
    /// custom-ruby.
    /// </summary>
    public static Rune CustomRuby => new(0xE605);

    /// <summary>
    /// custom-scheme.
    /// </summary>
    public static Rune CustomScheme => new(0xE6B1);

    /// <summary>
    /// custom-toml.
    /// </summary>
    public static Rune CustomToml => new(0xE6B2);

    /// <summary>
    /// custom-v_lang.
    /// </summary>
    public static Rune CustomVLang => new(0xE6AC);

    /// <summary>
    /// custom-vim.
    /// </summary>
    public static Rune CustomVim => new(0xE62B);

    /// <summary>
    /// custom-vitruvian.
    /// </summary>
    public static Rune CustomVitruvian => new(0xE6B7);

    /// <summary>
    /// custom-windows.
    /// </summary>
    public static Rune CustomWindows => new(0xE62A);

}
