// <auto-generated />

using System.Text;

namespace XenoAtom.Terminal.UI;

public static partial class NerdFont
{
    /// <summary>
    /// fae-apple_fruit.
    /// </summary>
    public static Rune FaeAppleFruit => new(0xE29E);

    /// <summary>
    /// fae-atom.
    /// </summary>
    public static Rune FaeAtom => new(0xE27F);

    /// <summary>
    /// fae-bacteria.
    /// </summary>
    public static Rune FaeBacteria => new(0xE280);

    /// <summary>
    /// fae-banana.
    /// </summary>
    public static Rune FaeBanana => new(0xE281);

    /// <summary>
    /// fae-bath.
    /// </summary>
    public static Rune FaeBath => new(0xE282);

    /// <summary>
    /// fae-bed.
    /// </summary>
    public static Rune FaeBed => new(0xE283);

    /// <summary>
    /// fae-benzene.
    /// </summary>
    public static Rune FaeBenzene => new(0xE284);

    /// <summary>
    /// fae-bigger.
    /// </summary>
    public static Rune FaeBigger => new(0xE285);

    /// <summary>
    /// fae-biohazard.
    /// </summary>
    public static Rune FaeBiohazard => new(0xE286);

    /// <summary>
    /// fae-blogger_circle.
    /// </summary>
    public static Rune FaeBloggerCircle => new(0xE287);

    /// <summary>
    /// fae-blogger_square.
    /// </summary>
    public static Rune FaeBloggerSquare => new(0xE288);

    /// <summary>
    /// fae-bones.
    /// </summary>
    public static Rune FaeBones => new(0xE289);

    /// <summary>
    /// fae-book_open.
    /// </summary>
    public static Rune FaeBookOpen => new(0xE28A);

    /// <summary>
    /// fae-book_open_o.
    /// </summary>
    public static Rune FaeBookOpenO => new(0xE28B);

    /// <summary>
    /// fae-brain.
    /// </summary>
    public static Rune FaeBrain => new(0xE28C);

    /// <summary>
    /// fae-bread.
    /// </summary>
    public static Rune FaeBread => new(0xE28D);

    /// <summary>
    /// fae-butterfly.
    /// </summary>
    public static Rune FaeButterfly => new(0xE28E);

    /// <summary>
    /// fae-carot.
    /// </summary>
    public static Rune FaeCarot => new(0xE28F);

    /// <summary>
    /// fae-cc_by.
    /// </summary>
    public static Rune FaeCcBy => new(0xE290);

    /// <summary>
    /// fae-cc_cc.
    /// </summary>
    public static Rune FaeCcCc => new(0xE291);

    /// <summary>
    /// fae-cc_nc.
    /// </summary>
    public static Rune FaeCcNc => new(0xE292);

    /// <summary>
    /// fae-cc_nc_eu.
    /// </summary>
    public static Rune FaeCcNcEu => new(0xE293);

    /// <summary>
    /// fae-cc_nc_jp.
    /// </summary>
    public static Rune FaeCcNcJp => new(0xE294);

    /// <summary>
    /// fae-cc_nd.
    /// </summary>
    public static Rune FaeCcNd => new(0xE295);

    /// <summary>
    /// fae-cc_remix.
    /// </summary>
    public static Rune FaeCcRemix => new(0xE296);

    /// <summary>
    /// fae-cc_sa.
    /// </summary>
    public static Rune FaeCcSa => new(0xE297);

    /// <summary>
    /// fae-cc_share.
    /// </summary>
    public static Rune FaeCcShare => new(0xE298);

    /// <summary>
    /// fae-cc_zero.
    /// </summary>
    public static Rune FaeCcZero => new(0xE299);

    /// <summary>
    /// fae-checklist_o.
    /// </summary>
    public static Rune FaeChecklistO => new(0xE29A);

    /// <summary>
    /// fae-cheese.
    /// </summary>
    public static Rune FaeCheese => new(0xE264);

    /// <summary>
    /// fae-cherry.
    /// </summary>
    public static Rune FaeCherry => new(0xE29B);

    /// <summary>
    /// fae-chess_bishop.
    /// </summary>
    public static Rune FaeChessBishop => new(0xE29C);

    /// <summary>
    /// fae-chess_horse.
    /// </summary>
    public static Rune FaeChessHorse => new(0xE25F);

    /// <summary>
    /// fae-chess_king.
    /// </summary>
    public static Rune FaeChessKing => new(0xE260);

    /// <summary>
    /// fae-chess_pawn.
    /// </summary>
    public static Rune FaeChessPawn => new(0xE261);

    /// <summary>
    /// fae-chess_queen.
    /// </summary>
    public static Rune FaeChessQueen => new(0xE262);

    /// <summary>
    /// fae-chess_tower.
    /// </summary>
    public static Rune FaeChessTower => new(0xE263);

    /// <summary>
    /// fae-chicken_thigh.
    /// </summary>
    public static Rune FaeChickenThigh => new(0xE29F);

    /// <summary>
    /// fae-chilli.
    /// </summary>
    public static Rune FaeChilli => new(0xE265);

    /// <summary>
    /// fae-chip.
    /// </summary>
    public static Rune FaeChip => new(0xE266);

    /// <summary>
    /// fae-cicling.
    /// </summary>
    public static Rune FaeCicling => new(0xE267);

    /// <summary>
    /// fae-cloud.
    /// </summary>
    public static Rune FaeCloud => new(0xE268);

    /// <summary>
    /// fae-cockroach.
    /// </summary>
    public static Rune FaeCockroach => new(0xE269);

    /// <summary>
    /// fae-coffe_beans.
    /// </summary>
    public static Rune FaeCoffeBeans => new(0xE26A);

    /// <summary>
    /// fae-coins.
    /// </summary>
    public static Rune FaeCoins => new(0xE26B);

    /// <summary>
    /// fae-comb.
    /// </summary>
    public static Rune FaeComb => new(0xE26C);

    /// <summary>
    /// fae-comet.
    /// </summary>
    public static Rune FaeComet => new(0xE26D);

    /// <summary>
    /// fae-crown.
    /// </summary>
    public static Rune FaeCrown => new(0xE26E);

    /// <summary>
    /// fae-cup_coffe.
    /// </summary>
    public static Rune FaeCupCoffe => new(0xE26F);

    /// <summary>
    /// fae-dice.
    /// </summary>
    public static Rune FaeDice => new(0xE270);

    /// <summary>
    /// fae-disco.
    /// </summary>
    public static Rune FaeDisco => new(0xE271);

    /// <summary>
    /// fae-dna.
    /// </summary>
    public static Rune FaeDna => new(0xE272);

    /// <summary>
    /// fae-donut.
    /// </summary>
    public static Rune FaeDonut => new(0xE273);

    /// <summary>
    /// fae-dress.
    /// </summary>
    public static Rune FaeDress => new(0xE274);

    /// <summary>
    /// fae-drop.
    /// </summary>
    public static Rune FaeDrop => new(0xE275);

    /// <summary>
    /// fae-ello.
    /// </summary>
    public static Rune FaeEllo => new(0xE276);

    /// <summary>
    /// fae-envelope_open.
    /// </summary>
    public static Rune FaeEnvelopeOpen => new(0xE277);

    /// <summary>
    /// fae-envelope_open_o.
    /// </summary>
    public static Rune FaeEnvelopeOpenO => new(0xE278);

    /// <summary>
    /// fae-equal.
    /// </summary>
    public static Rune FaeEqual => new(0xE279);

    /// <summary>
    /// fae-equal_bigger.
    /// </summary>
    public static Rune FaeEqualBigger => new(0xE27A);

    /// <summary>
    /// fae-feedly.
    /// </summary>
    public static Rune FaeFeedly => new(0xE27B);

    /// <summary>
    /// fae-file_export.
    /// </summary>
    public static Rune FaeFileExport => new(0xE27C);

    /// <summary>
    /// fae-file_import.
    /// </summary>
    public static Rune FaeFileImport => new(0xE27D);

    /// <summary>
    /// fae-fingerprint.
    /// </summary>
    public static Rune FaeFingerprint => new(0xE23F);

    /// <summary>
    /// fae-floppy.
    /// </summary>
    public static Rune FaeFloppy => new(0xE240);

    /// <summary>
    /// fae-footprint.
    /// </summary>
    public static Rune FaeFootprint => new(0xE241);

    /// <summary>
    /// fae-freecodecamp.
    /// </summary>
    public static Rune FaeFreecodecamp => new(0xE242);

    /// <summary>
    /// fae-galaxy.
    /// </summary>
    public static Rune FaeGalaxy => new(0xE243);

    /// <summary>
    /// fae-galery.
    /// </summary>
    public static Rune FaeGalery => new(0xE244);

    /// <summary>
    /// fae-gift_card.
    /// </summary>
    public static Rune FaeGiftCard => new(0xE2A0);

    /// <summary>
    /// fae-glass.
    /// </summary>
    public static Rune FaeGlass => new(0xE245);

    /// <summary>
    /// fae-google_drive.
    /// </summary>
    public static Rune FaeGoogleDrive => new(0xE246);

    /// <summary>
    /// fae-google_play.
    /// </summary>
    public static Rune FaeGooglePlay => new(0xE247);

    /// <summary>
    /// fae-gps.
    /// </summary>
    public static Rune FaeGps => new(0xE248);

    /// <summary>
    /// fae-grav.
    /// </summary>
    public static Rune FaeGrav => new(0xE249);

    /// <summary>
    /// fae-guitar.
    /// </summary>
    public static Rune FaeGuitar => new(0xE24A);

    /// <summary>
    /// fae-gut.
    /// </summary>
    public static Rune FaeGut => new(0xE24B);

    /// <summary>
    /// fae-halter.
    /// </summary>
    public static Rune FaeHalter => new(0xE24C);

    /// <summary>
    /// fae-hamburger.
    /// </summary>
    public static Rune FaeHamburger => new(0xE24D);

    /// <summary>
    /// fae-hat.
    /// </summary>
    public static Rune FaeHat => new(0xE24E);

    /// <summary>
    /// fae-hexagon.
    /// </summary>
    public static Rune FaeHexagon => new(0xE24F);

    /// <summary>
    /// fae-high_heel.
    /// </summary>
    public static Rune FaeHighHeel => new(0xE250);

    /// <summary>
    /// fae-hotdog.
    /// </summary>
    public static Rune FaeHotdog => new(0xE251);

    /// <summary>
    /// fae-ice_cream.
    /// </summary>
    public static Rune FaeIceCream => new(0xE252);

    /// <summary>
    /// fae-id_card.
    /// </summary>
    public static Rune FaeIdCard => new(0xE253);

    /// <summary>
    /// fae-imdb.
    /// </summary>
    public static Rune FaeImdb => new(0xE254);

    /// <summary>
    /// fae-infinity.
    /// </summary>
    public static Rune FaeInfinity => new(0xE255);

    /// <summary>
    /// fae-injection.
    /// </summary>
    public static Rune FaeInjection => new(0xE2A1);

    /// <summary>
    /// fae-isle.
    /// </summary>
    public static Rune FaeIsle => new(0xE2A2);

    /// <summary>
    /// fae-java.
    /// </summary>
    public static Rune FaeJava => new(0xE256);

    /// <summary>
    /// fae-layers.
    /// </summary>
    public static Rune FaeLayers => new(0xE257);

    /// <summary>
    /// fae-lips.
    /// </summary>
    public static Rune FaeLips => new(0xE258);

    /// <summary>
    /// fae-lipstick.
    /// </summary>
    public static Rune FaeLipstick => new(0xE259);

    /// <summary>
    /// fae-liver.
    /// </summary>
    public static Rune FaeLiver => new(0xE25A);

    /// <summary>
    /// fae-lollipop.
    /// </summary>
    public static Rune FaeLollipop => new(0xE2A3);

    /// <summary>
    /// fae-loyalty_card.
    /// </summary>
    public static Rune FaeLoyaltyCard => new(0xE2A4);

    /// <summary>
    /// fae-lung.
    /// </summary>
    public static Rune FaeLung => new(0xE25B);

    /// <summary>
    /// fae-makeup_brushes.
    /// </summary>
    public static Rune FaeMakeupBrushes => new(0xE25C);

    /// <summary>
    /// fae-maximize.
    /// </summary>
    public static Rune FaeMaximize => new(0xE25D);

    /// <summary>
    /// fae-meat.
    /// </summary>
    public static Rune FaeMeat => new(0xE2A5);

    /// <summary>
    /// fae-medicine.
    /// </summary>
    public static Rune FaeMedicine => new(0xE221);

    /// <summary>
    /// fae-microscope.
    /// </summary>
    public static Rune FaeMicroscope => new(0xE222);

    /// <summary>
    /// fae-milk_bottle.
    /// </summary>
    public static Rune FaeMilkBottle => new(0xE223);

    /// <summary>
    /// fae-minimize.
    /// </summary>
    public static Rune FaeMinimize => new(0xE224);

    /// <summary>
    /// fae-molecule.
    /// </summary>
    public static Rune FaeMolecule => new(0xE225);

    /// <summary>
    /// fae-moon_cloud.
    /// </summary>
    public static Rune FaeMoonCloud => new(0xE226);

    /// <summary>
    /// fae-mountains.
    /// </summary>
    public static Rune FaeMountains => new(0xE2A6);

    /// <summary>
    /// fae-mushroom.
    /// </summary>
    public static Rune FaeMushroom => new(0xE227);

    /// <summary>
    /// fae-mustache.
    /// </summary>
    public static Rune FaeMustache => new(0xE228);

    /// <summary>
    /// fae-mysql.
    /// </summary>
    public static Rune FaeMysql => new(0xE229);

    /// <summary>
    /// fae-nintendo.
    /// </summary>
    public static Rune FaeNintendo => new(0xE22A);

    /// <summary>
    /// fae-orange.
    /// </summary>
    public static Rune FaeOrange => new(0xE2A7);

    /// <summary>
    /// fae-palette_color.
    /// </summary>
    public static Rune FaePaletteColor => new(0xE22B);

    /// <summary>
    /// fae-peach.
    /// </summary>
    public static Rune FaePeach => new(0xE2A8);

    /// <summary>
    /// fae-pear.
    /// </summary>
    public static Rune FaePear => new(0xE2A9);

    /// <summary>
    /// fae-pi.
    /// </summary>
    public static Rune FaePi => new(0xE22C);

    /// <summary>
    /// fae-pizza.
    /// </summary>
    public static Rune FaePizza => new(0xE22D);

    /// <summary>
    /// fae-planet.
    /// </summary>
    public static Rune FaePlanet => new(0xE22E);

    /// <summary>
    /// fae-plant.
    /// </summary>
    public static Rune FaePlant => new(0xE22F);

    /// <summary>
    /// fae-playstation.
    /// </summary>
    public static Rune FaePlaystation => new(0xE230);

    /// <summary>
    /// fae-poison.
    /// </summary>
    public static Rune FaePoison => new(0xE231);

    /// <summary>
    /// fae-popcorn.
    /// </summary>
    public static Rune FaePopcorn => new(0xE232);

    /// <summary>
    /// fae-popsicle.
    /// </summary>
    public static Rune FaePopsicle => new(0xE233);

    /// <summary>
    /// fae-pulse.
    /// </summary>
    public static Rune FaePulse => new(0xE234);

    /// <summary>
    /// fae-python.
    /// </summary>
    public static Rune FaePython => new(0xE235);

    /// <summary>
    /// fae-quora_circle.
    /// </summary>
    public static Rune FaeQuoraCircle => new(0xE236);

    /// <summary>
    /// fae-quora_square.
    /// </summary>
    public static Rune FaeQuoraSquare => new(0xE237);

    /// <summary>
    /// fae-radioactive.
    /// </summary>
    public static Rune FaeRadioactive => new(0xE238);

    /// <summary>
    /// fae-raining.
    /// </summary>
    public static Rune FaeRaining => new(0xE239);

    /// <summary>
    /// fae-real_heart.
    /// </summary>
    public static Rune FaeRealHeart => new(0xE23A);

    /// <summary>
    /// fae-refrigerator.
    /// </summary>
    public static Rune FaeRefrigerator => new(0xE23B);

    /// <summary>
    /// fae-restore.
    /// </summary>
    public static Rune FaeRestore => new(0xE23C);

    /// <summary>
    /// fae-ring.
    /// </summary>
    public static Rune FaeRing => new(0xE23D);

    /// <summary>
    /// fae-ruby.
    /// </summary>
    public static Rune FaeRuby => new(0xE23E);

    /// <summary>
    /// fae-ruby_o.
    /// </summary>
    public static Rune FaeRubyO => new(0xE21E);

    /// <summary>
    /// fae-ruler.
    /// </summary>
    public static Rune FaeRuler => new(0xE21F);

    /// <summary>
    /// fae-shirt.
    /// </summary>
    public static Rune FaeShirt => new(0xE218);

    /// <summary>
    /// fae-slash.
    /// </summary>
    public static Rune FaeSlash => new(0xE216);

    /// <summary>
    /// fae-smaller.
    /// </summary>
    public static Rune FaeSmaller => new(0xE200);

    /// <summary>
    /// fae-snowing.
    /// </summary>
    public static Rune FaeSnowing => new(0xE201);

    /// <summary>
    /// fae-soda.
    /// </summary>
    public static Rune FaeSoda => new(0xE202);

    /// <summary>
    /// fae-sofa.
    /// </summary>
    public static Rune FaeSofa => new(0xE203);

    /// <summary>
    /// fae-soup.
    /// </summary>
    public static Rune FaeSoup => new(0xE204);

    /// <summary>
    /// fae-spermatozoon.
    /// </summary>
    public static Rune FaeSpermatozoon => new(0xE205);

    /// <summary>
    /// fae-spin_double.
    /// </summary>
    public static Rune FaeSpinDouble => new(0xE206);

    /// <summary>
    /// fae-stomach.
    /// </summary>
    public static Rune FaeStomach => new(0xE207);

    /// <summary>
    /// fae-storm.
    /// </summary>
    public static Rune FaeStorm => new(0xE208);

    /// <summary>
    /// fae-sun_cloud.
    /// </summary>
    public static Rune FaeSunCloud => new(0xE21D);

    /// <summary>
    /// fae-sushi.
    /// </summary>
    public static Rune FaeSushi => new(0xE21A);

    /// <summary>
    /// fae-tacos.
    /// </summary>
    public static Rune FaeTacos => new(0xE219);

    /// <summary>
    /// fae-telegram.
    /// </summary>
    public static Rune FaeTelegram => new(0xE217);

    /// <summary>
    /// fae-telegram_circle.
    /// </summary>
    public static Rune FaeTelegramCircle => new(0xE215);

    /// <summary>
    /// fae-telescope.
    /// </summary>
    public static Rune FaeTelescope => new(0xE209);

    /// <summary>
    /// fae-thermometer.
    /// </summary>
    public static Rune FaeThermometer => new(0xE20A);

    /// <summary>
    /// fae-thermometer_high.
    /// </summary>
    public static Rune FaeThermometerHigh => new(0xE20B);

    /// <summary>
    /// fae-thermometer_low.
    /// </summary>
    public static Rune FaeThermometerLow => new(0xE20C);

    /// <summary>
    /// fae-thin_close.
    /// </summary>
    public static Rune FaeThinClose => new(0xE20D);

    /// <summary>
    /// fae-toilet.
    /// </summary>
    public static Rune FaeToilet => new(0xE20E);

    /// <summary>
    /// fae-tools.
    /// </summary>
    public static Rune FaeTools => new(0xE20F);

    /// <summary>
    /// fae-tooth.
    /// </summary>
    public static Rune FaeTooth => new(0xE210);

    /// <summary>
    /// fae-tree.
    /// </summary>
    public static Rune FaeTree => new(0xE21C);

    /// <summary>
    /// fae-triangle_ruler.
    /// </summary>
    public static Rune FaeTriangleRuler => new(0xE21B);

    /// <summary>
    /// fae-umbrella.
    /// </summary>
    public static Rune FaeUmbrella => new(0xE220);

    /// <summary>
    /// fae-uterus.
    /// </summary>
    public static Rune FaeUterus => new(0xE211);

    /// <summary>
    /// fae-virus.
    /// </summary>
    public static Rune FaeVirus => new(0xE214);

    /// <summary>
    /// fae-w3c.
    /// </summary>
    public static Rune FaeW3c => new(0xE212);

    /// <summary>
    /// fae-walking.
    /// </summary>
    public static Rune FaeWalking => new(0xE213);

    /// <summary>
    /// fae-wallet.
    /// </summary>
    public static Rune FaeWallet => new(0xE25E);

    /// <summary>
    /// fae-wind.
    /// </summary>
    public static Rune FaeWind => new(0xE27E);

    /// <summary>
    /// fae-xbox.
    /// </summary>
    public static Rune FaeXbox => new(0xE29D);

}
