// <auto-generated />

using System.Text;

namespace XenoAtom.Terminal.UI;

public static partial class NerdFont
{
    /// <summary>
    /// oct-accessibility.
    /// </summary>
    public static Rune OctAccessibility => new(0xF406);

    /// <summary>
    /// oct-accessibility_inset.
    /// </summary>
    public static Rune OctAccessibilityInset => new(0xF40B);

    /// <summary>
    /// oct-alert.
    /// </summary>
    public static Rune OctAlert => new(0xF421);

    /// <summary>
    /// oct-alert_fill.
    /// </summary>
    public static Rune OctAlertFill => new(0xF40C);

    /// <summary>
    /// oct-apps.
    /// </summary>
    public static Rune OctApps => new(0xF40E);

    /// <summary>
    /// oct-archive.
    /// </summary>
    public static Rune OctArchive => new(0xF411);

    /// <summary>
    /// oct-arrow_both.
    /// </summary>
    public static Rune OctArrowBoth => new(0xF416);

    /// <summary>
    /// oct-arrow_down.
    /// </summary>
    public static Rune OctArrowDown => new(0xF433);

    /// <summary>
    /// oct-arrow_down_left.
    /// </summary>
    public static Rune OctArrowDownLeft => new(0xF424);

    /// <summary>
    /// oct-arrow_down_right.
    /// </summary>
    public static Rune OctArrowDownRight => new(0xF43E);

    /// <summary>
    /// oct-arrow_left.
    /// </summary>
    public static Rune OctArrowLeft => new(0xF434);

    /// <summary>
    /// oct-arrow_right.
    /// </summary>
    public static Rune OctArrowRight => new(0xF432);

    /// <summary>
    /// oct-arrow_switch.
    /// </summary>
    public static Rune OctArrowSwitch => new(0xF443);

    /// <summary>
    /// oct-arrow_up.
    /// </summary>
    public static Rune OctArrowUp => new(0xF431);

    /// <summary>
    /// oct-arrow_up_left.
    /// </summary>
    public static Rune OctArrowUpLeft => new(0xF45C);

    /// <summary>
    /// oct-arrow_up_right.
    /// </summary>
    public static Rune OctArrowUpRight => new(0xF46C);

    /// <summary>
    /// oct-beaker.
    /// </summary>
    public static Rune OctBeaker => new(0xF499);

    /// <summary>
    /// oct-bell.
    /// </summary>
    public static Rune OctBell => new(0xF49A);

    /// <summary>
    /// oct-bell_fill.
    /// </summary>
    public static Rune OctBellFill => new(0xF476);

    /// <summary>
    /// oct-bell_slash.
    /// </summary>
    public static Rune OctBellSlash => new(0xF478);

    /// <summary>
    /// oct-blocked.
    /// </summary>
    public static Rune OctBlocked => new(0xF479);

    /// <summary>
    /// oct-bold.
    /// </summary>
    public static Rune OctBold => new(0xF49D);

    /// <summary>
    /// oct-book.
    /// </summary>
    public static Rune OctBook => new(0xF405);

    /// <summary>
    /// oct-bookmark.
    /// </summary>
    public static Rune OctBookmark => new(0xF461);

    /// <summary>
    /// oct-bookmark_fill.
    /// </summary>
    public static Rune OctBookmarkFill => new(0xF47A);

    /// <summary>
    /// oct-bookmark_slash.
    /// </summary>
    public static Rune OctBookmarkSlash => new(0xF533);

    /// <summary>
    /// oct-bookmark_slash_fill.
    /// </summary>
    public static Rune OctBookmarkSlashFill => new(0xF493);

    /// <summary>
    /// oct-briefcase.
    /// </summary>
    public static Rune OctBriefcase => new(0xF491);

    /// <summary>
    /// oct-broadcast.
    /// </summary>
    public static Rune OctBroadcast => new(0xF43C);

    /// <summary>
    /// oct-browser.
    /// </summary>
    public static Rune OctBrowser => new(0xF488);

    /// <summary>
    /// oct-bug.
    /// </summary>
    public static Rune OctBug => new(0xF46F);

    /// <summary>
    /// oct-cache.
    /// </summary>
    public static Rune OctCache => new(0xF49B);

    /// <summary>
    /// oct-calendar.
    /// </summary>
    public static Rune OctCalendar => new(0xF455);

    /// <summary>
    /// oct-check.
    /// </summary>
    public static Rune OctCheck => new(0xF42E);

    /// <summary>
    /// oct-check_circle.
    /// </summary>
    public static Rune OctCheckCircle => new(0xF49E);

    /// <summary>
    /// oct-check_circle_fill.
    /// </summary>
    public static Rune OctCheckCircleFill => new(0xF4A4);

    /// <summary>
    /// oct-checkbox.
    /// </summary>
    public static Rune OctCheckbox => new(0xF4A7);

    /// <summary>
    /// oct-checklist.
    /// </summary>
    public static Rune OctChecklist => new(0xF45E);

    /// <summary>
    /// oct-chevron_down.
    /// </summary>
    public static Rune OctChevronDown => new(0xF47C);

    /// <summary>
    /// oct-chevron_left.
    /// </summary>
    public static Rune OctChevronLeft => new(0xF47D);

    /// <summary>
    /// oct-chevron_right.
    /// </summary>
    public static Rune OctChevronRight => new(0xF460);

    /// <summary>
    /// oct-chevron_up.
    /// </summary>
    public static Rune OctChevronUp => new(0xF47B);

    /// <summary>
    /// oct-circle.
    /// </summary>
    public static Rune OctCircle => new(0xF4AA);

    /// <summary>
    /// oct-circle_slash.
    /// </summary>
    public static Rune OctCircleSlash => new(0xF468);

    /// <summary>
    /// oct-clock.
    /// </summary>
    public static Rune OctClock => new(0xF43A);

    /// <summary>
    /// oct-clock_fill.
    /// </summary>
    public static Rune OctClockFill => new(0xF4AB);

    /// <summary>
    /// oct-cloud.
    /// </summary>
    public static Rune OctCloud => new(0xF4AC);

    /// <summary>
    /// oct-cloud_offline.
    /// </summary>
    public static Rune OctCloudOffline => new(0xF4AD);

    /// <summary>
    /// oct-code.
    /// </summary>
    public static Rune OctCode => new(0xF44F);

    /// <summary>
    /// oct-code_of_conduct.
    /// </summary>
    public static Rune OctCodeOfConduct => new(0xF4AE);

    /// <summary>
    /// oct-code_review.
    /// </summary>
    public static Rune OctCodeReview => new(0xF4AF);

    /// <summary>
    /// oct-code_square.
    /// </summary>
    public static Rune OctCodeSquare => new(0xF4B0);

    /// <summary>
    /// oct-codescan.
    /// </summary>
    public static Rune OctCodescan => new(0xF4B1);

    /// <summary>
    /// oct-codescan_checkmark.
    /// </summary>
    public static Rune OctCodescanCheckmark => new(0xF4B2);

    /// <summary>
    /// oct-codespaces.
    /// </summary>
    public static Rune OctCodespaces => new(0xF4B3);

    /// <summary>
    /// oct-columns.
    /// </summary>
    public static Rune OctColumns => new(0xF4B4);

    /// <summary>
    /// oct-command_palette.
    /// </summary>
    public static Rune OctCommandPalette => new(0xF4B5);

    /// <summary>
    /// oct-comment.
    /// </summary>
    public static Rune OctComment => new(0xF41F);

    /// <summary>
    /// oct-comment_discussion.
    /// </summary>
    public static Rune OctCommentDiscussion => new(0xF442);

    /// <summary>
    /// oct-commit.
    /// </summary>
    public static Rune OctCommit => new(0xF4B6);

    /// <summary>
    /// oct-container.
    /// </summary>
    public static Rune OctContainer => new(0xF4B7);

    /// <summary>
    /// oct-copilot.
    /// </summary>
    public static Rune OctCopilot => new(0xF4B8);

    /// <summary>
    /// oct-copilot_error.
    /// </summary>
    public static Rune OctCopilotError => new(0xF4B9);

    /// <summary>
    /// oct-copilot_warning.
    /// </summary>
    public static Rune OctCopilotWarning => new(0xF4BA);

    /// <summary>
    /// oct-copy.
    /// </summary>
    public static Rune OctCopy => new(0xF4BB);

    /// <summary>
    /// oct-cpu.
    /// </summary>
    public static Rune OctCpu => new(0xF4BC);

    /// <summary>
    /// oct-credit_card.
    /// </summary>
    public static Rune OctCreditCard => new(0xF439);

    /// <summary>
    /// oct-cross_reference.
    /// </summary>
    public static Rune OctCrossReference => new(0xF4BD);

    /// <summary>
    /// oct-dash.
    /// </summary>
    public static Rune OctDash => new(0xF48B);

    /// <summary>
    /// oct-database.
    /// </summary>
    public static Rune OctDatabase => new(0xF472);

    /// <summary>
    /// oct-dependabot.
    /// </summary>
    public static Rune OctDependabot => new(0xF4BE);

    /// <summary>
    /// oct-desktop_download.
    /// </summary>
    public static Rune OctDesktopDownload => new(0xF498);

    /// <summary>
    /// oct-device_camera.
    /// </summary>
    public static Rune OctDeviceCamera => new(0xF446);

    /// <summary>
    /// oct-device_camera_video.
    /// </summary>
    public static Rune OctDeviceCameraVideo => new(0xF447);

    /// <summary>
    /// oct-device_desktop.
    /// </summary>
    public static Rune OctDeviceDesktop => new(0xF4A9);

    /// <summary>
    /// oct-device_mobile.
    /// </summary>
    public static Rune OctDeviceMobile => new(0xF42C);

    /// <summary>
    /// oct-diamond.
    /// </summary>
    public static Rune OctDiamond => new(0xF4BF);

    /// <summary>
    /// oct-diff.
    /// </summary>
    public static Rune OctDiff => new(0xF440);

    /// <summary>
    /// oct-diff_added.
    /// </summary>
    public static Rune OctDiffAdded => new(0xF457);

    /// <summary>
    /// oct-diff_ignored.
    /// </summary>
    public static Rune OctDiffIgnored => new(0xF474);

    /// <summary>
    /// oct-diff_modified.
    /// </summary>
    public static Rune OctDiffModified => new(0xF459);

    /// <summary>
    /// oct-diff_removed.
    /// </summary>
    public static Rune OctDiffRemoved => new(0xF458);

    /// <summary>
    /// oct-diff_renamed.
    /// </summary>
    public static Rune OctDiffRenamed => new(0xF45A);

    /// <summary>
    /// oct-discussion_closed.
    /// </summary>
    public static Rune OctDiscussionClosed => new(0xF4C0);

    /// <summary>
    /// oct-discussion_duplicate.
    /// </summary>
    public static Rune OctDiscussionDuplicate => new(0xF4C1);

    /// <summary>
    /// oct-discussion_outdated.
    /// </summary>
    public static Rune OctDiscussionOutdated => new(0xF4C2);

    /// <summary>
    /// oct-dot.
    /// </summary>
    public static Rune OctDot => new(0xF4C3);

    /// <summary>
    /// oct-dot_fill.
    /// </summary>
    public static Rune OctDotFill => new(0xF444);

    /// <summary>
    /// oct-download.
    /// </summary>
    public static Rune OctDownload => new(0xF409);

    /// <summary>
    /// oct-duplicate.
    /// </summary>
    public static Rune OctDuplicate => new(0xF4C4);

    /// <summary>
    /// oct-ellipsis.
    /// </summary>
    public static Rune OctEllipsis => new(0xF475);

    /// <summary>
    /// oct-eye.
    /// </summary>
    public static Rune OctEye => new(0xF441);

    /// <summary>
    /// oct-eye_closed.
    /// </summary>
    public static Rune OctEyeClosed => new(0xF4C5);

    /// <summary>
    /// oct-feed_discussion.
    /// </summary>
    public static Rune OctFeedDiscussion => new(0xF4C6);

    /// <summary>
    /// oct-feed_forked.
    /// </summary>
    public static Rune OctFeedForked => new(0xF4C7);

    /// <summary>
    /// oct-feed_heart.
    /// </summary>
    public static Rune OctFeedHeart => new(0xF4C8);

    /// <summary>
    /// oct-feed_merged.
    /// </summary>
    public static Rune OctFeedMerged => new(0xF4C9);

    /// <summary>
    /// oct-feed_person.
    /// </summary>
    public static Rune OctFeedPerson => new(0xF4CA);

    /// <summary>
    /// oct-feed_repo.
    /// </summary>
    public static Rune OctFeedRepo => new(0xF4CB);

    /// <summary>
    /// oct-feed_rocket.
    /// </summary>
    public static Rune OctFeedRocket => new(0xF4CC);

    /// <summary>
    /// oct-feed_star.
    /// </summary>
    public static Rune OctFeedStar => new(0xF4CD);

    /// <summary>
    /// oct-feed_tag.
    /// </summary>
    public static Rune OctFeedTag => new(0xF4CE);

    /// <summary>
    /// oct-feed_trophy.
    /// </summary>
    public static Rune OctFeedTrophy => new(0xF4CF);

    /// <summary>
    /// oct-file.
    /// </summary>
    public static Rune OctFile => new(0xF4A5);

    /// <summary>
    /// oct-file_added.
    /// </summary>
    public static Rune OctFileAdded => new(0xF4D0);

    /// <summary>
    /// oct-file_badge.
    /// </summary>
    public static Rune OctFileBadge => new(0xF4D1);

    /// <summary>
    /// oct-file_binary.
    /// </summary>
    public static Rune OctFileBinary => new(0xF471);

    /// <summary>
    /// oct-file_code.
    /// </summary>
    public static Rune OctFileCode => new(0xF40D);

    /// <summary>
    /// oct-file_diff.
    /// </summary>
    public static Rune OctFileDiff => new(0xF4D2);

    /// <summary>
    /// oct-file_directory.
    /// </summary>
    public static Rune OctFileDirectory => new(0xF413);

    /// <summary>
    /// oct-file_directory_fill.
    /// </summary>
    public static Rune OctFileDirectoryFill => new(0xF4D3);

    /// <summary>
    /// oct-file_directory_open_fill.
    /// </summary>
    public static Rune OctFileDirectoryOpenFill => new(0xF4D4);

    /// <summary>
    /// oct-file_media.
    /// </summary>
    public static Rune OctFileMedia => new(0xF40F);

    /// <summary>
    /// oct-file_moved.
    /// </summary>
    public static Rune OctFileMoved => new(0xF4D5);

    /// <summary>
    /// oct-file_removed.
    /// </summary>
    public static Rune OctFileRemoved => new(0xF4D6);

    /// <summary>
    /// oct-file_submodule.
    /// </summary>
    public static Rune OctFileSubmodule => new(0xF414);

    /// <summary>
    /// oct-file_symlink_directory.
    /// </summary>
    public static Rune OctFileSymlinkDirectory => new(0xF482);

    /// <summary>
    /// oct-file_symlink_file.
    /// </summary>
    public static Rune OctFileSymlinkFile => new(0xF481);

    /// <summary>
    /// oct-file_zip.
    /// </summary>
    public static Rune OctFileZip => new(0xF410);

    /// <summary>
    /// oct-filter.
    /// </summary>
    public static Rune OctFilter => new(0xF4D7);

    /// <summary>
    /// oct-fiscal_host.
    /// </summary>
    public static Rune OctFiscalHost => new(0xF4D8);

    /// <summary>
    /// oct-flame.
    /// </summary>
    public static Rune OctFlame => new(0xF490);

    /// <summary>
    /// oct-fold.
    /// </summary>
    public static Rune OctFold => new(0xF48C);

    /// <summary>
    /// oct-fold_down.
    /// </summary>
    public static Rune OctFoldDown => new(0xF4D9);

    /// <summary>
    /// oct-fold_up.
    /// </summary>
    public static Rune OctFoldUp => new(0xF4DA);

    /// <summary>
    /// oct-gear.
    /// </summary>
    public static Rune OctGear => new(0xF423);

    /// <summary>
    /// oct-gift.
    /// </summary>
    public static Rune OctGift => new(0xF436);

    /// <summary>
    /// oct-git_branch.
    /// </summary>
    public static Rune OctGitBranch => new(0xF418);

    /// <summary>
    /// oct-git_commit.
    /// </summary>
    public static Rune OctGitCommit => new(0xF417);

    /// <summary>
    /// oct-git_compare.
    /// </summary>
    public static Rune OctGitCompare => new(0xF47F);

    /// <summary>
    /// oct-git_merge.
    /// </summary>
    public static Rune OctGitMerge => new(0xF419);

    /// <summary>
    /// oct-git_merge_queue.
    /// </summary>
    public static Rune OctGitMergeQueue => new(0xF4DB);

    /// <summary>
    /// oct-git_pull_request.
    /// </summary>
    public static Rune OctGitPullRequest => new(0xF407);

    /// <summary>
    /// oct-git_pull_request_closed.
    /// </summary>
    public static Rune OctGitPullRequestClosed => new(0xF4DC);

    /// <summary>
    /// oct-git_pull_request_draft.
    /// </summary>
    public static Rune OctGitPullRequestDraft => new(0xF4DD);

    /// <summary>
    /// oct-globe.
    /// </summary>
    public static Rune OctGlobe => new(0xF484);

    /// <summary>
    /// oct-goal.
    /// </summary>
    public static Rune OctGoal => new(0xF4DE);

    /// <summary>
    /// oct-grabber.
    /// </summary>
    public static Rune OctGrabber => new(0xF4A6);

    /// <summary>
    /// oct-graph.
    /// </summary>
    public static Rune OctGraph => new(0xF437);

    /// <summary>
    /// oct-hash.
    /// </summary>
    public static Rune OctHash => new(0xF4DF);

    /// <summary>
    /// oct-heading.
    /// </summary>
    public static Rune OctHeading => new(0xF4E0);

    /// <summary>
    /// oct-heart.
    /// </summary>
    public static Rune OctHeart => new(0x2665);

    /// <summary>
    /// oct-heart_fill.
    /// </summary>
    public static Rune OctHeartFill => new(0xF4E1);

    /// <summary>
    /// oct-history.
    /// </summary>
    public static Rune OctHistory => new(0xF464);

    /// <summary>
    /// oct-home.
    /// </summary>
    public static Rune OctHome => new(0xF46D);

    /// <summary>
    /// oct-home_fill.
    /// </summary>
    public static Rune OctHomeFill => new(0xF4E2);

    /// <summary>
    /// oct-horizontal_rule.
    /// </summary>
    public static Rune OctHorizontalRule => new(0xF45B);

    /// <summary>
    /// oct-hourglass.
    /// </summary>
    public static Rune OctHourglass => new(0xF4E3);

    /// <summary>
    /// oct-hubot.
    /// </summary>
    public static Rune OctHubot => new(0xF477);

    /// <summary>
    /// oct-id_badge.
    /// </summary>
    public static Rune OctIdBadge => new(0xF4E4);

    /// <summary>
    /// oct-image.
    /// </summary>
    public static Rune OctImage => new(0xF4E5);

    /// <summary>
    /// oct-inbox.
    /// </summary>
    public static Rune OctInbox => new(0xF48D);

    /// <summary>
    /// oct-infinity.
    /// </summary>
    public static Rune OctInfinity => new(0xF4E6);

    /// <summary>
    /// oct-info.
    /// </summary>
    public static Rune OctInfo => new(0xF449);

    /// <summary>
    /// oct-issue_closed.
    /// </summary>
    public static Rune OctIssueClosed => new(0xF41D);

    /// <summary>
    /// oct-issue_draft.
    /// </summary>
    public static Rune OctIssueDraft => new(0xF4E7);

    /// <summary>
    /// oct-issue_opened.
    /// </summary>
    public static Rune OctIssueOpened => new(0xF41B);

    /// <summary>
    /// oct-issue_reopened.
    /// </summary>
    public static Rune OctIssueReopened => new(0xF41C);

    /// <summary>
    /// oct-issue_tracked_by.
    /// </summary>
    public static Rune OctIssueTrackedBy => new(0xF4E8);

    /// <summary>
    /// oct-issue_tracks.
    /// </summary>
    public static Rune OctIssueTracks => new(0xF4E9);

    /// <summary>
    /// oct-italic.
    /// </summary>
    public static Rune OctItalic => new(0xF49F);

    /// <summary>
    /// oct-iterations.
    /// </summary>
    public static Rune OctIterations => new(0xF4EA);

    /// <summary>
    /// oct-kebab_horizontal.
    /// </summary>
    public static Rune OctKebabHorizontal => new(0xF4EB);

    /// <summary>
    /// oct-key.
    /// </summary>
    public static Rune OctKey => new(0xF43D);

    /// <summary>
    /// oct-key_asterisk.
    /// </summary>
    public static Rune OctKeyAsterisk => new(0xF4EC);

    /// <summary>
    /// oct-law.
    /// </summary>
    public static Rune OctLaw => new(0xF495);

    /// <summary>
    /// oct-light_bulb.
    /// </summary>
    public static Rune OctLightBulb => new(0xF400);

    /// <summary>
    /// oct-link.
    /// </summary>
    public static Rune OctLink => new(0xF44C);

    /// <summary>
    /// oct-link_external.
    /// </summary>
    public static Rune OctLinkExternal => new(0xF465);

    /// <summary>
    /// oct-list_ordered.
    /// </summary>
    public static Rune OctListOrdered => new(0xF452);

    /// <summary>
    /// oct-list_unordered.
    /// </summary>
    public static Rune OctListUnordered => new(0xF451);

    /// <summary>
    /// oct-location.
    /// </summary>
    public static Rune OctLocation => new(0xF450);

    /// <summary>
    /// oct-lock.
    /// </summary>
    public static Rune OctLock => new(0xF456);

    /// <summary>
    /// oct-log.
    /// </summary>
    public static Rune OctLog => new(0xF4ED);

    /// <summary>
    /// oct-logo_gist.
    /// </summary>
    public static Rune OctLogoGist => new(0xF480);

    /// <summary>
    /// oct-logo_github.
    /// </summary>
    public static Rune OctLogoGithub => new(0xF470);

    /// <summary>
    /// oct-mail.
    /// </summary>
    public static Rune OctMail => new(0xF42F);

    /// <summary>
    /// oct-mark_github.
    /// </summary>
    public static Rune OctMarkGithub => new(0xF408);

    /// <summary>
    /// oct-markdown.
    /// </summary>
    public static Rune OctMarkdown => new(0xF48A);

    /// <summary>
    /// oct-megaphone.
    /// </summary>
    public static Rune OctMegaphone => new(0xF45F);

    /// <summary>
    /// oct-mention.
    /// </summary>
    public static Rune OctMention => new(0xF486);

    /// <summary>
    /// oct-meter.
    /// </summary>
    public static Rune OctMeter => new(0xF463);

    /// <summary>
    /// oct-milestone.
    /// </summary>
    public static Rune OctMilestone => new(0xF45D);

    /// <summary>
    /// oct-mirror.
    /// </summary>
    public static Rune OctMirror => new(0xF41A);

    /// <summary>
    /// oct-moon.
    /// </summary>
    public static Rune OctMoon => new(0xF4EE);

    /// <summary>
    /// oct-mortar_board.
    /// </summary>
    public static Rune OctMortarBoard => new(0xF494);

    /// <summary>
    /// oct-move_to_bottom.
    /// </summary>
    public static Rune OctMoveToBottom => new(0xF4EF);

    /// <summary>
    /// oct-move_to_end.
    /// </summary>
    public static Rune OctMoveToEnd => new(0xF4F0);

    /// <summary>
    /// oct-move_to_start.
    /// </summary>
    public static Rune OctMoveToStart => new(0xF4F1);

    /// <summary>
    /// oct-move_to_top.
    /// </summary>
    public static Rune OctMoveToTop => new(0xF4F2);

    /// <summary>
    /// oct-multi_select.
    /// </summary>
    public static Rune OctMultiSelect => new(0xF4F3);

    /// <summary>
    /// oct-mute.
    /// </summary>
    public static Rune OctMute => new(0xF466);

    /// <summary>
    /// oct-no_entry.
    /// </summary>
    public static Rune OctNoEntry => new(0xF4F4);

    /// <summary>
    /// oct-north_star.
    /// </summary>
    public static Rune OctNorthStar => new(0xF4F5);

    /// <summary>
    /// oct-note.
    /// </summary>
    public static Rune OctNote => new(0xF4F6);

    /// <summary>
    /// oct-number.
    /// </summary>
    public static Rune OctNumber => new(0xF4F7);

    /// <summary>
    /// oct-organization.
    /// </summary>
    public static Rune OctOrganization => new(0xF42B);

    /// <summary>
    /// oct-package.
    /// </summary>
    public static Rune OctPackage => new(0xF487);

    /// <summary>
    /// oct-package_dependencies.
    /// </summary>
    public static Rune OctPackageDependencies => new(0xF4F8);

    /// <summary>
    /// oct-package_dependents.
    /// </summary>
    public static Rune OctPackageDependents => new(0xF4F9);

    /// <summary>
    /// oct-paintbrush.
    /// </summary>
    public static Rune OctPaintbrush => new(0xF48F);

    /// <summary>
    /// oct-paper_airplane.
    /// </summary>
    public static Rune OctPaperAirplane => new(0xF4FA);

    /// <summary>
    /// oct-paperclip.
    /// </summary>
    public static Rune OctPaperclip => new(0xF4FB);

    /// <summary>
    /// oct-passkey_fill.
    /// </summary>
    public static Rune OctPasskeyFill => new(0xF4FC);

    /// <summary>
    /// oct-paste.
    /// </summary>
    public static Rune OctPaste => new(0xF429);

    /// <summary>
    /// oct-pencil.
    /// </summary>
    public static Rune OctPencil => new(0xF448);

    /// <summary>
    /// oct-people.
    /// </summary>
    public static Rune OctPeople => new(0xF4FD);

    /// <summary>
    /// oct-person.
    /// </summary>
    public static Rune OctPerson => new(0xF415);

    /// <summary>
    /// oct-person_add.
    /// </summary>
    public static Rune OctPersonAdd => new(0xF4FE);

    /// <summary>
    /// oct-person_fill.
    /// </summary>
    public static Rune OctPersonFill => new(0xF4FF);

    /// <summary>
    /// oct-pin.
    /// </summary>
    public static Rune OctPin => new(0xF435);

    /// <summary>
    /// oct-play.
    /// </summary>
    public static Rune OctPlay => new(0xF500);

    /// <summary>
    /// oct-plug.
    /// </summary>
    public static Rune OctPlug => new(0xF492);

    /// <summary>
    /// oct-plus.
    /// </summary>
    public static Rune OctPlus => new(0xF44D);

    /// <summary>
    /// oct-plus_circle.
    /// </summary>
    public static Rune OctPlusCircle => new(0xF501);

    /// <summary>
    /// oct-project.
    /// </summary>
    public static Rune OctProject => new(0xF502);

    /// <summary>
    /// oct-project_roadmap.
    /// </summary>
    public static Rune OctProjectRoadmap => new(0xF503);

    /// <summary>
    /// oct-project_symlink.
    /// </summary>
    public static Rune OctProjectSymlink => new(0xF504);

    /// <summary>
    /// oct-project_template.
    /// </summary>
    public static Rune OctProjectTemplate => new(0xF505);

    /// <summary>
    /// oct-pulse.
    /// </summary>
    public static Rune OctPulse => new(0xF469);

    /// <summary>
    /// oct-question.
    /// </summary>
    public static Rune OctQuestion => new(0xF420);

    /// <summary>
    /// oct-quote.
    /// </summary>
    public static Rune OctQuote => new(0xF453);

    /// <summary>
    /// oct-read.
    /// </summary>
    public static Rune OctRead => new(0xF430);

    /// <summary>
    /// oct-rel_file_path.
    /// </summary>
    public static Rune OctRelFilePath => new(0xF506);

    /// <summary>
    /// oct-reply.
    /// </summary>
    public static Rune OctReply => new(0xF4A8);

    /// <summary>
    /// oct-repo.
    /// </summary>
    public static Rune OctRepo => new(0xF401);

    /// <summary>
    /// oct-repo_clone.
    /// </summary>
    public static Rune OctRepoClone => new(0xF43F);

    /// <summary>
    /// oct-repo_deleted.
    /// </summary>
    public static Rune OctRepoDeleted => new(0xF507);

    /// <summary>
    /// oct-repo_forked.
    /// </summary>
    public static Rune OctRepoForked => new(0xF402);

    /// <summary>
    /// oct-repo_locked.
    /// </summary>
    public static Rune OctRepoLocked => new(0xF508);

    /// <summary>
    /// oct-repo_pull.
    /// </summary>
    public static Rune OctRepoPull => new(0xF404);

    /// <summary>
    /// oct-repo_push.
    /// </summary>
    public static Rune OctRepoPush => new(0xF403);

    /// <summary>
    /// oct-repo_template.
    /// </summary>
    public static Rune OctRepoTemplate => new(0xF509);

    /// <summary>
    /// oct-report.
    /// </summary>
    public static Rune OctReport => new(0xF50A);

    /// <summary>
    /// oct-rocket.
    /// </summary>
    public static Rune OctRocket => new(0xF427);

    /// <summary>
    /// oct-rows.
    /// </summary>
    public static Rune OctRows => new(0xF50B);

    /// <summary>
    /// oct-rss.
    /// </summary>
    public static Rune OctRss => new(0xF428);

    /// <summary>
    /// oct-ruby.
    /// </summary>
    public static Rune OctRuby => new(0xF43B);

    /// <summary>
    /// oct-screen_full.
    /// </summary>
    public static Rune OctScreenFull => new(0xF50C);

    /// <summary>
    /// oct-screen_normal.
    /// </summary>
    public static Rune OctScreenNormal => new(0xF50D);

    /// <summary>
    /// oct-search.
    /// </summary>
    public static Rune OctSearch => new(0xF422);

    /// <summary>
    /// oct-server.
    /// </summary>
    public static Rune OctServer => new(0xF473);

    /// <summary>
    /// oct-share.
    /// </summary>
    public static Rune OctShare => new(0xF50E);

    /// <summary>
    /// oct-share_android.
    /// </summary>
    public static Rune OctShareAndroid => new(0xF50F);

    /// <summary>
    /// oct-shield.
    /// </summary>
    public static Rune OctShield => new(0xF49C);

    /// <summary>
    /// oct-shield_check.
    /// </summary>
    public static Rune OctShieldCheck => new(0xF510);

    /// <summary>
    /// oct-shield_lock.
    /// </summary>
    public static Rune OctShieldLock => new(0xF511);

    /// <summary>
    /// oct-shield_slash.
    /// </summary>
    public static Rune OctShieldSlash => new(0xF512);

    /// <summary>
    /// oct-shield_x.
    /// </summary>
    public static Rune OctShieldX => new(0xF513);

    /// <summary>
    /// oct-sidebar_collapse.
    /// </summary>
    public static Rune OctSidebarCollapse => new(0xF514);

    /// <summary>
    /// oct-sidebar_expand.
    /// </summary>
    public static Rune OctSidebarExpand => new(0xF515);

    /// <summary>
    /// oct-sign_in.
    /// </summary>
    public static Rune OctSignIn => new(0xF42A);

    /// <summary>
    /// oct-sign_out.
    /// </summary>
    public static Rune OctSignOut => new(0xF426);

    /// <summary>
    /// oct-single_select.
    /// </summary>
    public static Rune OctSingleSelect => new(0xF516);

    /// <summary>
    /// oct-skip.
    /// </summary>
    public static Rune OctSkip => new(0xF517);

    /// <summary>
    /// oct-skip_fill.
    /// </summary>
    public static Rune OctSkipFill => new(0xF518);

    /// <summary>
    /// oct-sliders.
    /// </summary>
    public static Rune OctSliders => new(0xF462);

    /// <summary>
    /// oct-smiley.
    /// </summary>
    public static Rune OctSmiley => new(0xF4A2);

    /// <summary>
    /// oct-sort_asc.
    /// </summary>
    public static Rune OctSortAsc => new(0xF519);

    /// <summary>
    /// oct-sort_desc.
    /// </summary>
    public static Rune OctSortDesc => new(0xF51A);

    /// <summary>
    /// oct-sparkle_fill.
    /// </summary>
    public static Rune OctSparkleFill => new(0xF51B);

    /// <summary>
    /// oct-sponsor_tiers.
    /// </summary>
    public static Rune OctSponsorTiers => new(0xF51C);

    /// <summary>
    /// oct-square.
    /// </summary>
    public static Rune OctSquare => new(0xF51D);

    /// <summary>
    /// oct-square_fill.
    /// </summary>
    public static Rune OctSquareFill => new(0xF445);

    /// <summary>
    /// oct-squirrel.
    /// </summary>
    public static Rune OctSquirrel => new(0xF483);

    /// <summary>
    /// oct-stack.
    /// </summary>
    public static Rune OctStack => new(0xF51E);

    /// <summary>
    /// oct-star.
    /// </summary>
    public static Rune OctStar => new(0xF41E);

    /// <summary>
    /// oct-star_fill.
    /// </summary>
    public static Rune OctStarFill => new(0xF51F);

    /// <summary>
    /// oct-stop.
    /// </summary>
    public static Rune OctStop => new(0xF46E);

    /// <summary>
    /// oct-stopwatch.
    /// </summary>
    public static Rune OctStopwatch => new(0xF520);

    /// <summary>
    /// oct-strikethrough.
    /// </summary>
    public static Rune OctStrikethrough => new(0xF521);

    /// <summary>
    /// oct-sun.
    /// </summary>
    public static Rune OctSun => new(0xF522);

    /// <summary>
    /// oct-sync.
    /// </summary>
    public static Rune OctSync => new(0xF46A);

    /// <summary>
    /// oct-tab.
    /// </summary>
    public static Rune OctTab => new(0xF523);

    /// <summary>
    /// oct-tab_external.
    /// </summary>
    public static Rune OctTabExternal => new(0xF524);

    /// <summary>
    /// oct-table.
    /// </summary>
    public static Rune OctTable => new(0xF525);

    /// <summary>
    /// oct-tag.
    /// </summary>
    public static Rune OctTag => new(0xF412);

    /// <summary>
    /// oct-tasklist.
    /// </summary>
    public static Rune OctTasklist => new(0xF4A0);

    /// <summary>
    /// oct-telescope.
    /// </summary>
    public static Rune OctTelescope => new(0xF46B);

    /// <summary>
    /// oct-telescope_fill.
    /// </summary>
    public static Rune OctTelescopeFill => new(0xF526);

    /// <summary>
    /// oct-terminal.
    /// </summary>
    public static Rune OctTerminal => new(0xF489);

    /// <summary>
    /// oct-three_bars.
    /// </summary>
    public static Rune OctThreeBars => new(0xF44E);

    /// <summary>
    /// oct-thumbsdown.
    /// </summary>
    public static Rune OctThumbsdown => new(0xF497);

    /// <summary>
    /// oct-thumbsup.
    /// </summary>
    public static Rune OctThumbsup => new(0xF496);

    /// <summary>
    /// oct-tools.
    /// </summary>
    public static Rune OctTools => new(0xF425);

    /// <summary>
    /// oct-trash.
    /// </summary>
    public static Rune OctTrash => new(0xF48E);

    /// <summary>
    /// oct-triangle_down.
    /// </summary>
    public static Rune OctTriangleDown => new(0xF44B);

    /// <summary>
    /// oct-triangle_left.
    /// </summary>
    public static Rune OctTriangleLeft => new(0xF438);

    /// <summary>
    /// oct-triangle_right.
    /// </summary>
    public static Rune OctTriangleRight => new(0xF44A);

    /// <summary>
    /// oct-triangle_up.
    /// </summary>
    public static Rune OctTriangleUp => new(0xF47E);

    /// <summary>
    /// oct-trophy.
    /// </summary>
    public static Rune OctTrophy => new(0xF527);

    /// <summary>
    /// oct-typography.
    /// </summary>
    public static Rune OctTypography => new(0xF528);

    /// <summary>
    /// oct-unfold.
    /// </summary>
    public static Rune OctUnfold => new(0xF42D);

    /// <summary>
    /// oct-unlink.
    /// </summary>
    public static Rune OctUnlink => new(0xF529);

    /// <summary>
    /// oct-unlock.
    /// </summary>
    public static Rune OctUnlock => new(0xF52A);

    /// <summary>
    /// oct-unmute.
    /// </summary>
    public static Rune OctUnmute => new(0xF485);

    /// <summary>
    /// oct-unread.
    /// </summary>
    public static Rune OctUnread => new(0xF52B);

    /// <summary>
    /// oct-unverified.
    /// </summary>
    public static Rune OctUnverified => new(0xF4A3);

    /// <summary>
    /// oct-upload.
    /// </summary>
    public static Rune OctUpload => new(0xF40A);

    /// <summary>
    /// oct-verified.
    /// </summary>
    public static Rune OctVerified => new(0xF4A1);

    /// <summary>
    /// oct-versions.
    /// </summary>
    public static Rune OctVersions => new(0xF454);

    /// <summary>
    /// oct-video.
    /// </summary>
    public static Rune OctVideo => new(0xF52C);

    /// <summary>
    /// oct-webhook.
    /// </summary>
    public static Rune OctWebhook => new(0xF52D);

    /// <summary>
    /// oct-workflow.
    /// </summary>
    public static Rune OctWorkflow => new(0xF52E);

    /// <summary>
    /// oct-x.
    /// </summary>
    public static Rune OctX => new(0xF467);

    /// <summary>
    /// oct-x_circle.
    /// </summary>
    public static Rune OctXCircle => new(0xF52F);

    /// <summary>
    /// oct-x_circle_fill.
    /// </summary>
    public static Rune OctXCircleFill => new(0xF530);

    /// <summary>
    /// oct-zap.
    /// </summary>
    public static Rune OctZap => new(0x26A1);

    /// <summary>
    /// oct-zoom_in.
    /// </summary>
    public static Rune OctZoomIn => new(0xF531);

    /// <summary>
    /// oct-zoom_out.
    /// </summary>
    public static Rune OctZoomOut => new(0xF532);

}
