// <auto-generated />

using System.Text;

namespace XenoAtom.Terminal.UI;

public static partial class NerdFont
{
    /// <summary>
    /// pl-branch.
    /// </summary>
    public static Rune PlBranch => new(0xE0A0);

    /// <summary>
    /// pl-current_line.
    /// </summary>
    public static Rune PlCurrentLine => new(0xE0A1);

    /// <summary>
    /// pl-hostname.
    /// </summary>
    public static Rune PlHostname => new(0xE0A2);

    /// <summary>
    /// pl-left_hard_divider.
    /// </summary>
    public static Rune PlLeftHardDivider => new(0xE0B0);

    /// <summary>
    /// pl-left_soft_divider.
    /// </summary>
    public static Rune PlLeftSoftDivider => new(0xE0B1);

    /// <summary>
    /// pl-line_number.
    /// </summary>
    public static Rune PlLineNumber => new(0xE0A1);

    /// <summary>
    /// pl-readonly.
    /// </summary>
    public static Rune PlReadonly => new(0xE0A2);

    /// <summary>
    /// pl-right_hard_divider.
    /// </summary>
    public static Rune PlRightHardDivider => new(0xE0B2);

    /// <summary>
    /// pl-right_soft_divider.
    /// </summary>
    public static Rune PlRightSoftDivider => new(0xE0B3);

}
