// <auto-generated />

using System.Text;

namespace XenoAtom.Terminal.UI;

public static partial class NerdFont
{
    /// <summary>
    /// iec-power.
    /// </summary>
    public static Rune IecPower => new(0x23FB);

    /// <summary>
    /// iec-power_off.
    /// </summary>
    public static Rune IecPowerOff => new(0x2B58);

    /// <summary>
    /// iec-power_on.
    /// </summary>
    public static Rune IecPowerOn => new(0x23FD);

    /// <summary>
    /// iec-sleep_mode.
    /// </summary>
    public static Rune IecSleepMode => new(0x23FE);

    /// <summary>
    /// iec-toggle_power.
    /// </summary>
    public static Rune IecTogglePower => new(0x23FC);

}
