// <auto-generated />

using System.Text;

namespace XenoAtom.Terminal.UI;

public static partial class NerdFont
{
    /// <summary>
    /// pom-away.
    /// </summary>
    public static Rune PomAway => new(0xE007);

    /// <summary>
    /// pom-clean_code.
    /// </summary>
    public static Rune PomCleanCode => new(0xE000);

    /// <summary>
    /// pom-external_interruption.
    /// </summary>
    public static Rune PomExternalInterruption => new(0xE00A);

    /// <summary>
    /// pom-internal_interruption.
    /// </summary>
    public static Rune PomInternalInterruption => new(0xE009);

    /// <summary>
    /// pom-long_pause.
    /// </summary>
    public static Rune PomLongPause => new(0xE006);

    /// <summary>
    /// pom-pair_programming.
    /// </summary>
    public static Rune PomPairProgramming => new(0xE008);

    /// <summary>
    /// pom-pomodoro_done.
    /// </summary>
    public static Rune PomPomodoroDone => new(0xE001);

    /// <summary>
    /// pom-pomodoro_estimated.
    /// </summary>
    public static Rune PomPomodoroEstimated => new(0xE002);

    /// <summary>
    /// pom-pomodoro_squashed.
    /// </summary>
    public static Rune PomPomodoroSquashed => new(0xE004);

    /// <summary>
    /// pom-pomodoro_ticking.
    /// </summary>
    public static Rune PomPomodoroTicking => new(0xE003);

    /// <summary>
    /// pom-short_pause.
    /// </summary>
    public static Rune PomShortPause => new(0xE005);

}
