// <auto-generated />

using System.Text;

namespace XenoAtom.Terminal.UI;

public static partial class NerdFont
{
    /// <summary>
    /// weather-alien.
    /// </summary>
    public static Rune WeatherAlien => new(0xE36E);

    /// <summary>
    /// weather-aliens.
    /// </summary>
    public static Rune WeatherAliens => new(0xE345);

    /// <summary>
    /// weather-barometer.
    /// </summary>
    public static Rune WeatherBarometer => new(0xE372);

    /// <summary>
    /// weather-celsius.
    /// </summary>
    public static Rune WeatherCelsius => new(0xE339);

    /// <summary>
    /// weather-cloud.
    /// </summary>
    public static Rune WeatherCloud => new(0xE33D);

    /// <summary>
    /// weather-cloud_down.
    /// </summary>
    public static Rune WeatherCloudDown => new(0xE33A);

    /// <summary>
    /// weather-cloud_refresh.
    /// </summary>
    public static Rune WeatherCloudRefresh => new(0xE33B);

    /// <summary>
    /// weather-cloud_up.
    /// </summary>
    public static Rune WeatherCloudUp => new(0xE33C);

    /// <summary>
    /// weather-cloudy.
    /// </summary>
    public static Rune WeatherCloudy => new(0xE312);

    /// <summary>
    /// weather-cloudy_gusts.
    /// </summary>
    public static Rune WeatherCloudyGusts => new(0xE310);

    /// <summary>
    /// weather-cloudy_windy.
    /// </summary>
    public static Rune WeatherCloudyWindy => new(0xE311);

    /// <summary>
    /// weather-day_cloudy.
    /// </summary>
    public static Rune WeatherDayCloudy => new(0xE302);

    /// <summary>
    /// weather-day_cloudy_gusts.
    /// </summary>
    public static Rune WeatherDayCloudyGusts => new(0xE300);

    /// <summary>
    /// weather-day_cloudy_high.
    /// </summary>
    public static Rune WeatherDayCloudyHigh => new(0xE376);

    /// <summary>
    /// weather-day_cloudy_windy.
    /// </summary>
    public static Rune WeatherDayCloudyWindy => new(0xE301);

    /// <summary>
    /// weather-day_fog.
    /// </summary>
    public static Rune WeatherDayFog => new(0xE303);

    /// <summary>
    /// weather-day_hail.
    /// </summary>
    public static Rune WeatherDayHail => new(0xE304);

    /// <summary>
    /// weather-day_haze.
    /// </summary>
    public static Rune WeatherDayHaze => new(0xE3AE);

    /// <summary>
    /// weather-day_light_wind.
    /// </summary>
    public static Rune WeatherDayLightWind => new(0xE3BC);

    /// <summary>
    /// weather-day_lightning.
    /// </summary>
    public static Rune WeatherDayLightning => new(0xE305);

    /// <summary>
    /// weather-day_rain.
    /// </summary>
    public static Rune WeatherDayRain => new(0xE308);

    /// <summary>
    /// weather-day_rain_mix.
    /// </summary>
    public static Rune WeatherDayRainMix => new(0xE306);

    /// <summary>
    /// weather-day_rain_wind.
    /// </summary>
    public static Rune WeatherDayRainWind => new(0xE307);

    /// <summary>
    /// weather-day_showers.
    /// </summary>
    public static Rune WeatherDayShowers => new(0xE309);

    /// <summary>
    /// weather-day_sleet.
    /// </summary>
    public static Rune WeatherDaySleet => new(0xE3AA);

    /// <summary>
    /// weather-day_sleet_storm.
    /// </summary>
    public static Rune WeatherDaySleetStorm => new(0xE362);

    /// <summary>
    /// weather-day_snow.
    /// </summary>
    public static Rune WeatherDaySnow => new(0xE30A);

    /// <summary>
    /// weather-day_snow_thunderstorm.
    /// </summary>
    public static Rune WeatherDaySnowThunderstorm => new(0xE365);

    /// <summary>
    /// weather-day_snow_wind.
    /// </summary>
    public static Rune WeatherDaySnowWind => new(0xE35F);

    /// <summary>
    /// weather-day_sprinkle.
    /// </summary>
    public static Rune WeatherDaySprinkle => new(0xE30B);

    /// <summary>
    /// weather-day_storm_showers.
    /// </summary>
    public static Rune WeatherDayStormShowers => new(0xE30E);

    /// <summary>
    /// weather-day_sunny.
    /// </summary>
    public static Rune WeatherDaySunny => new(0xE30D);

    /// <summary>
    /// weather-day_sunny_overcast.
    /// </summary>
    public static Rune WeatherDaySunnyOvercast => new(0xE30C);

    /// <summary>
    /// weather-day_thunderstorm.
    /// </summary>
    public static Rune WeatherDayThunderstorm => new(0xE30F);

    /// <summary>
    /// weather-day_windy.
    /// </summary>
    public static Rune WeatherDayWindy => new(0xE37D);

    /// <summary>
    /// weather-degrees.
    /// </summary>
    public static Rune WeatherDegrees => new(0xE33E);

    /// <summary>
    /// weather-direction_down.
    /// </summary>
    public static Rune WeatherDirectionDown => new(0xE340);

    /// <summary>
    /// weather-direction_down_left.
    /// </summary>
    public static Rune WeatherDirectionDownLeft => new(0xE33F);

    /// <summary>
    /// weather-direction_down_right.
    /// </summary>
    public static Rune WeatherDirectionDownRight => new(0xE380);

    /// <summary>
    /// weather-direction_left.
    /// </summary>
    public static Rune WeatherDirectionLeft => new(0xE344);

    /// <summary>
    /// weather-direction_right.
    /// </summary>
    public static Rune WeatherDirectionRight => new(0xE349);

    /// <summary>
    /// weather-direction_up.
    /// </summary>
    public static Rune WeatherDirectionUp => new(0xE353);

    /// <summary>
    /// weather-direction_up_left.
    /// </summary>
    public static Rune WeatherDirectionUpLeft => new(0xE37F);

    /// <summary>
    /// weather-direction_up_right.
    /// </summary>
    public static Rune WeatherDirectionUpRight => new(0xE352);

    /// <summary>
    /// weather-dust.
    /// </summary>
    public static Rune WeatherDust => new(0xE35D);

    /// <summary>
    /// weather-earthquake.
    /// </summary>
    public static Rune WeatherEarthquake => new(0xE3BE);

    /// <summary>
    /// weather-fahrenheit.
    /// </summary>
    public static Rune WeatherFahrenheit => new(0xE341);

    /// <summary>
    /// weather-fire.
    /// </summary>
    public static Rune WeatherFire => new(0xE3BF);

    /// <summary>
    /// weather-flood.
    /// </summary>
    public static Rune WeatherFlood => new(0xE375);

    /// <summary>
    /// weather-fog.
    /// </summary>
    public static Rune WeatherFog => new(0xE313);

    /// <summary>
    /// weather-gale_warning.
    /// </summary>
    public static Rune WeatherGaleWarning => new(0xE3C5);

    /// <summary>
    /// weather-hail.
    /// </summary>
    public static Rune WeatherHail => new(0xE314);

    /// <summary>
    /// weather-horizon.
    /// </summary>
    public static Rune WeatherHorizon => new(0xE343);

    /// <summary>
    /// weather-horizon_alt.
    /// </summary>
    public static Rune WeatherHorizonAlt => new(0xE342);

    /// <summary>
    /// weather-hot.
    /// </summary>
    public static Rune WeatherHot => new(0xE36B);

    /// <summary>
    /// weather-humidity.
    /// </summary>
    public static Rune WeatherHumidity => new(0xE373);

    /// <summary>
    /// weather-hurricane.
    /// </summary>
    public static Rune WeatherHurricane => new(0xE36C);

    /// <summary>
    /// weather-hurricane_warning.
    /// </summary>
    public static Rune WeatherHurricaneWarning => new(0xE3C7);

    /// <summary>
    /// weather-lightning.
    /// </summary>
    public static Rune WeatherLightning => new(0xE315);

    /// <summary>
    /// weather-lunar_eclipse.
    /// </summary>
    public static Rune WeatherLunarEclipse => new(0xE369);

    /// <summary>
    /// weather-meteor.
    /// </summary>
    public static Rune WeatherMeteor => new(0xE36A);

    /// <summary>
    /// weather-moon_alt_first_quarter.
    /// </summary>
    public static Rune WeatherMoonAltFirstQuarter => new(0xE3CE);

    /// <summary>
    /// weather-moon_alt_full.
    /// </summary>
    public static Rune WeatherMoonAltFull => new(0xE3D5);

    /// <summary>
    /// weather-moon_alt_new.
    /// </summary>
    public static Rune WeatherMoonAltNew => new(0xE3E3);

    /// <summary>
    /// weather-moon_alt_third_quarter.
    /// </summary>
    public static Rune WeatherMoonAltThirdQuarter => new(0xE3DC);

    /// <summary>
    /// weather-moon_alt_waning_crescent_1.
    /// </summary>
    public static Rune WeatherMoonAltWaningCrescent1 => new(0xE3DD);

    /// <summary>
    /// weather-moon_alt_waning_crescent_2.
    /// </summary>
    public static Rune WeatherMoonAltWaningCrescent2 => new(0xE3DE);

    /// <summary>
    /// weather-moon_alt_waning_crescent_3.
    /// </summary>
    public static Rune WeatherMoonAltWaningCrescent3 => new(0xE3DF);

    /// <summary>
    /// weather-moon_alt_waning_crescent_4.
    /// </summary>
    public static Rune WeatherMoonAltWaningCrescent4 => new(0xE3E0);

    /// <summary>
    /// weather-moon_alt_waning_crescent_5.
    /// </summary>
    public static Rune WeatherMoonAltWaningCrescent5 => new(0xE3E1);

    /// <summary>
    /// weather-moon_alt_waning_crescent_6.
    /// </summary>
    public static Rune WeatherMoonAltWaningCrescent6 => new(0xE3E2);

    /// <summary>
    /// weather-moon_alt_waning_gibbous_1.
    /// </summary>
    public static Rune WeatherMoonAltWaningGibbous1 => new(0xE3D6);

    /// <summary>
    /// weather-moon_alt_waning_gibbous_2.
    /// </summary>
    public static Rune WeatherMoonAltWaningGibbous2 => new(0xE3D7);

    /// <summary>
    /// weather-moon_alt_waning_gibbous_3.
    /// </summary>
    public static Rune WeatherMoonAltWaningGibbous3 => new(0xE3D8);

    /// <summary>
    /// weather-moon_alt_waning_gibbous_4.
    /// </summary>
    public static Rune WeatherMoonAltWaningGibbous4 => new(0xE3D9);

    /// <summary>
    /// weather-moon_alt_waning_gibbous_5.
    /// </summary>
    public static Rune WeatherMoonAltWaningGibbous5 => new(0xE3DA);

    /// <summary>
    /// weather-moon_alt_waning_gibbous_6.
    /// </summary>
    public static Rune WeatherMoonAltWaningGibbous6 => new(0xE3DB);

    /// <summary>
    /// weather-moon_alt_waxing_crescent_1.
    /// </summary>
    public static Rune WeatherMoonAltWaxingCrescent1 => new(0xE3C8);

    /// <summary>
    /// weather-moon_alt_waxing_crescent_2.
    /// </summary>
    public static Rune WeatherMoonAltWaxingCrescent2 => new(0xE3C9);

    /// <summary>
    /// weather-moon_alt_waxing_crescent_3.
    /// </summary>
    public static Rune WeatherMoonAltWaxingCrescent3 => new(0xE3CA);

    /// <summary>
    /// weather-moon_alt_waxing_crescent_4.
    /// </summary>
    public static Rune WeatherMoonAltWaxingCrescent4 => new(0xE3CB);

    /// <summary>
    /// weather-moon_alt_waxing_crescent_5.
    /// </summary>
    public static Rune WeatherMoonAltWaxingCrescent5 => new(0xE3CC);

    /// <summary>
    /// weather-moon_alt_waxing_crescent_6.
    /// </summary>
    public static Rune WeatherMoonAltWaxingCrescent6 => new(0xE3CD);

    /// <summary>
    /// weather-moon_alt_waxing_gibbous_1.
    /// </summary>
    public static Rune WeatherMoonAltWaxingGibbous1 => new(0xE3CF);

    /// <summary>
    /// weather-moon_alt_waxing_gibbous_2.
    /// </summary>
    public static Rune WeatherMoonAltWaxingGibbous2 => new(0xE3D0);

    /// <summary>
    /// weather-moon_alt_waxing_gibbous_3.
    /// </summary>
    public static Rune WeatherMoonAltWaxingGibbous3 => new(0xE3D1);

    /// <summary>
    /// weather-moon_alt_waxing_gibbous_4.
    /// </summary>
    public static Rune WeatherMoonAltWaxingGibbous4 => new(0xE3D2);

    /// <summary>
    /// weather-moon_alt_waxing_gibbous_5.
    /// </summary>
    public static Rune WeatherMoonAltWaxingGibbous5 => new(0xE3D3);

    /// <summary>
    /// weather-moon_alt_waxing_gibbous_6.
    /// </summary>
    public static Rune WeatherMoonAltWaxingGibbous6 => new(0xE3D4);

    /// <summary>
    /// weather-moon_first_quarter.
    /// </summary>
    public static Rune WeatherMoonFirstQuarter => new(0xE394);

    /// <summary>
    /// weather-moon_full.
    /// </summary>
    public static Rune WeatherMoonFull => new(0xE39B);

    /// <summary>
    /// weather-moon_new.
    /// </summary>
    public static Rune WeatherMoonNew => new(0xE38D);

    /// <summary>
    /// weather-moon_third_quarter.
    /// </summary>
    public static Rune WeatherMoonThirdQuarter => new(0xE3A2);

    /// <summary>
    /// weather-moon_waning_crescent_1.
    /// </summary>
    public static Rune WeatherMoonWaningCrescent1 => new(0xE3A3);

    /// <summary>
    /// weather-moon_waning_crescent_2.
    /// </summary>
    public static Rune WeatherMoonWaningCrescent2 => new(0xE3A4);

    /// <summary>
    /// weather-moon_waning_crescent_3.
    /// </summary>
    public static Rune WeatherMoonWaningCrescent3 => new(0xE3A5);

    /// <summary>
    /// weather-moon_waning_crescent_4.
    /// </summary>
    public static Rune WeatherMoonWaningCrescent4 => new(0xE3A6);

    /// <summary>
    /// weather-moon_waning_crescent_5.
    /// </summary>
    public static Rune WeatherMoonWaningCrescent5 => new(0xE3A7);

    /// <summary>
    /// weather-moon_waning_crescent_6.
    /// </summary>
    public static Rune WeatherMoonWaningCrescent6 => new(0xE3A8);

    /// <summary>
    /// weather-moon_waning_gibbous_1.
    /// </summary>
    public static Rune WeatherMoonWaningGibbous1 => new(0xE39C);

    /// <summary>
    /// weather-moon_waning_gibbous_2.
    /// </summary>
    public static Rune WeatherMoonWaningGibbous2 => new(0xE39D);

    /// <summary>
    /// weather-moon_waning_gibbous_3.
    /// </summary>
    public static Rune WeatherMoonWaningGibbous3 => new(0xE39E);

    /// <summary>
    /// weather-moon_waning_gibbous_4.
    /// </summary>
    public static Rune WeatherMoonWaningGibbous4 => new(0xE39F);

    /// <summary>
    /// weather-moon_waning_gibbous_5.
    /// </summary>
    public static Rune WeatherMoonWaningGibbous5 => new(0xE3A0);

    /// <summary>
    /// weather-moon_waning_gibbous_6.
    /// </summary>
    public static Rune WeatherMoonWaningGibbous6 => new(0xE3A1);

    /// <summary>
    /// weather-moon_waxing_crescent_1.
    /// </summary>
    public static Rune WeatherMoonWaxingCrescent1 => new(0xE38E);

    /// <summary>
    /// weather-moon_waxing_crescent_2.
    /// </summary>
    public static Rune WeatherMoonWaxingCrescent2 => new(0xE38F);

    /// <summary>
    /// weather-moon_waxing_crescent_3.
    /// </summary>
    public static Rune WeatherMoonWaxingCrescent3 => new(0xE390);

    /// <summary>
    /// weather-moon_waxing_crescent_4.
    /// </summary>
    public static Rune WeatherMoonWaxingCrescent4 => new(0xE391);

    /// <summary>
    /// weather-moon_waxing_crescent_5.
    /// </summary>
    public static Rune WeatherMoonWaxingCrescent5 => new(0xE392);

    /// <summary>
    /// weather-moon_waxing_crescent_6.
    /// </summary>
    public static Rune WeatherMoonWaxingCrescent6 => new(0xE393);

    /// <summary>
    /// weather-moon_waxing_gibbous_1.
    /// </summary>
    public static Rune WeatherMoonWaxingGibbous1 => new(0xE395);

    /// <summary>
    /// weather-moon_waxing_gibbous_2.
    /// </summary>
    public static Rune WeatherMoonWaxingGibbous2 => new(0xE396);

    /// <summary>
    /// weather-moon_waxing_gibbous_3.
    /// </summary>
    public static Rune WeatherMoonWaxingGibbous3 => new(0xE397);

    /// <summary>
    /// weather-moon_waxing_gibbous_4.
    /// </summary>
    public static Rune WeatherMoonWaxingGibbous4 => new(0xE398);

    /// <summary>
    /// weather-moon_waxing_gibbous_5.
    /// </summary>
    public static Rune WeatherMoonWaxingGibbous5 => new(0xE399);

    /// <summary>
    /// weather-moon_waxing_gibbous_6.
    /// </summary>
    public static Rune WeatherMoonWaxingGibbous6 => new(0xE39A);

    /// <summary>
    /// weather-moonrise.
    /// </summary>
    public static Rune WeatherMoonrise => new(0xE3C1);

    /// <summary>
    /// weather-moonset.
    /// </summary>
    public static Rune WeatherMoonset => new(0xE3C2);

    /// <summary>
    /// weather-na.
    /// </summary>
    public static Rune WeatherNa => new(0xE374);

    /// <summary>
    /// weather-night_alt_cloudy.
    /// </summary>
    public static Rune WeatherNightAltCloudy => new(0xE37E);

    /// <summary>
    /// weather-night_alt_cloudy_gusts.
    /// </summary>
    public static Rune WeatherNightAltCloudyGusts => new(0xE31F);

    /// <summary>
    /// weather-night_alt_cloudy_high.
    /// </summary>
    public static Rune WeatherNightAltCloudyHigh => new(0xE377);

    /// <summary>
    /// weather-night_alt_cloudy_windy.
    /// </summary>
    public static Rune WeatherNightAltCloudyWindy => new(0xE320);

    /// <summary>
    /// weather-night_alt_hail.
    /// </summary>
    public static Rune WeatherNightAltHail => new(0xE321);

    /// <summary>
    /// weather-night_alt_lightning.
    /// </summary>
    public static Rune WeatherNightAltLightning => new(0xE322);

    /// <summary>
    /// weather-night_alt_partly_cloudy.
    /// </summary>
    public static Rune WeatherNightAltPartlyCloudy => new(0xE379);

    /// <summary>
    /// weather-night_alt_rain.
    /// </summary>
    public static Rune WeatherNightAltRain => new(0xE325);

    /// <summary>
    /// weather-night_alt_rain_mix.
    /// </summary>
    public static Rune WeatherNightAltRainMix => new(0xE323);

    /// <summary>
    /// weather-night_alt_rain_wind.
    /// </summary>
    public static Rune WeatherNightAltRainWind => new(0xE324);

    /// <summary>
    /// weather-night_alt_showers.
    /// </summary>
    public static Rune WeatherNightAltShowers => new(0xE326);

    /// <summary>
    /// weather-night_alt_sleet.
    /// </summary>
    public static Rune WeatherNightAltSleet => new(0xE3AC);

    /// <summary>
    /// weather-night_alt_sleet_storm.
    /// </summary>
    public static Rune WeatherNightAltSleetStorm => new(0xE364);

    /// <summary>
    /// weather-night_alt_snow.
    /// </summary>
    public static Rune WeatherNightAltSnow => new(0xE327);

    /// <summary>
    /// weather-night_alt_snow_thunderstorm.
    /// </summary>
    public static Rune WeatherNightAltSnowThunderstorm => new(0xE367);

    /// <summary>
    /// weather-night_alt_snow_wind.
    /// </summary>
    public static Rune WeatherNightAltSnowWind => new(0xE361);

    /// <summary>
    /// weather-night_alt_sprinkle.
    /// </summary>
    public static Rune WeatherNightAltSprinkle => new(0xE328);

    /// <summary>
    /// weather-night_alt_storm_showers.
    /// </summary>
    public static Rune WeatherNightAltStormShowers => new(0xE329);

    /// <summary>
    /// weather-night_alt_thunderstorm.
    /// </summary>
    public static Rune WeatherNightAltThunderstorm => new(0xE32A);

    /// <summary>
    /// weather-night_clear.
    /// </summary>
    public static Rune WeatherNightClear => new(0xE32B);

    /// <summary>
    /// weather-night_cloudy.
    /// </summary>
    public static Rune WeatherNightCloudy => new(0xE32E);

    /// <summary>
    /// weather-night_cloudy_gusts.
    /// </summary>
    public static Rune WeatherNightCloudyGusts => new(0xE32C);

    /// <summary>
    /// weather-night_cloudy_high.
    /// </summary>
    public static Rune WeatherNightCloudyHigh => new(0xE378);

    /// <summary>
    /// weather-night_cloudy_windy.
    /// </summary>
    public static Rune WeatherNightCloudyWindy => new(0xE32D);

    /// <summary>
    /// weather-night_fog.
    /// </summary>
    public static Rune WeatherNightFog => new(0xE346);

    /// <summary>
    /// weather-night_hail.
    /// </summary>
    public static Rune WeatherNightHail => new(0xE32F);

    /// <summary>
    /// weather-night_lightning.
    /// </summary>
    public static Rune WeatherNightLightning => new(0xE330);

    /// <summary>
    /// weather-night_partly_cloudy.
    /// </summary>
    public static Rune WeatherNightPartlyCloudy => new(0xE37B);

    /// <summary>
    /// weather-night_rain.
    /// </summary>
    public static Rune WeatherNightRain => new(0xE333);

    /// <summary>
    /// weather-night_rain_mix.
    /// </summary>
    public static Rune WeatherNightRainMix => new(0xE331);

    /// <summary>
    /// weather-night_rain_wind.
    /// </summary>
    public static Rune WeatherNightRainWind => new(0xE332);

    /// <summary>
    /// weather-night_showers.
    /// </summary>
    public static Rune WeatherNightShowers => new(0xE334);

    /// <summary>
    /// weather-night_sleet.
    /// </summary>
    public static Rune WeatherNightSleet => new(0xE3AB);

    /// <summary>
    /// weather-night_sleet_storm.
    /// </summary>
    public static Rune WeatherNightSleetStorm => new(0xE363);

    /// <summary>
    /// weather-night_snow.
    /// </summary>
    public static Rune WeatherNightSnow => new(0xE335);

    /// <summary>
    /// weather-night_snow_thunderstorm.
    /// </summary>
    public static Rune WeatherNightSnowThunderstorm => new(0xE366);

    /// <summary>
    /// weather-night_snow_wind.
    /// </summary>
    public static Rune WeatherNightSnowWind => new(0xE360);

    /// <summary>
    /// weather-night_sprinkle.
    /// </summary>
    public static Rune WeatherNightSprinkle => new(0xE336);

    /// <summary>
    /// weather-night_storm_showers.
    /// </summary>
    public static Rune WeatherNightStormShowers => new(0xE337);

    /// <summary>
    /// weather-night_thunderstorm.
    /// </summary>
    public static Rune WeatherNightThunderstorm => new(0xE338);

    /// <summary>
    /// weather-rain.
    /// </summary>
    public static Rune WeatherRain => new(0xE318);

    /// <summary>
    /// weather-rain_mix.
    /// </summary>
    public static Rune WeatherRainMix => new(0xE316);

    /// <summary>
    /// weather-rain_wind.
    /// </summary>
    public static Rune WeatherRainWind => new(0xE317);

    /// <summary>
    /// weather-raindrop.
    /// </summary>
    public static Rune WeatherRaindrop => new(0xE371);

    /// <summary>
    /// weather-raindrops.
    /// </summary>
    public static Rune WeatherRaindrops => new(0xE34A);

    /// <summary>
    /// weather-refresh.
    /// </summary>
    public static Rune WeatherRefresh => new(0xE348);

    /// <summary>
    /// weather-refresh_alt.
    /// </summary>
    public static Rune WeatherRefreshAlt => new(0xE347);

    /// <summary>
    /// weather-sandstorm.
    /// </summary>
    public static Rune WeatherSandstorm => new(0xE37A);

    /// <summary>
    /// weather-showers.
    /// </summary>
    public static Rune WeatherShowers => new(0xE319);

    /// <summary>
    /// weather-sleet.
    /// </summary>
    public static Rune WeatherSleet => new(0xE3AD);

    /// <summary>
    /// weather-small_craft_advisory.
    /// </summary>
    public static Rune WeatherSmallCraftAdvisory => new(0xE3C4);

    /// <summary>
    /// weather-smog.
    /// </summary>
    public static Rune WeatherSmog => new(0xE36D);

    /// <summary>
    /// weather-smoke.
    /// </summary>
    public static Rune WeatherSmoke => new(0xE35C);

    /// <summary>
    /// weather-snow.
    /// </summary>
    public static Rune WeatherSnow => new(0xE31A);

    /// <summary>
    /// weather-snow_wind.
    /// </summary>
    public static Rune WeatherSnowWind => new(0xE35E);

    /// <summary>
    /// weather-snowflake_cold.
    /// </summary>
    public static Rune WeatherSnowflakeCold => new(0xE36F);

    /// <summary>
    /// weather-solar_eclipse.
    /// </summary>
    public static Rune WeatherSolarEclipse => new(0xE368);

    /// <summary>
    /// weather-sprinkle.
    /// </summary>
    public static Rune WeatherSprinkle => new(0xE31B);

    /// <summary>
    /// weather-stars.
    /// </summary>
    public static Rune WeatherStars => new(0xE370);

    /// <summary>
    /// weather-storm_showers.
    /// </summary>
    public static Rune WeatherStormShowers => new(0xE31C);

    /// <summary>
    /// weather-storm_warning.
    /// </summary>
    public static Rune WeatherStormWarning => new(0xE3C6);

    /// <summary>
    /// weather-strong_wind.
    /// </summary>
    public static Rune WeatherStrongWind => new(0xE34B);

    /// <summary>
    /// weather-sunrise.
    /// </summary>
    public static Rune WeatherSunrise => new(0xE34C);

    /// <summary>
    /// weather-sunset.
    /// </summary>
    public static Rune WeatherSunset => new(0xE34D);

    /// <summary>
    /// weather-thermometer.
    /// </summary>
    public static Rune WeatherThermometer => new(0xE350);

    /// <summary>
    /// weather-thermometer_exterior.
    /// </summary>
    public static Rune WeatherThermometerExterior => new(0xE34E);

    /// <summary>
    /// weather-thermometer_internal.
    /// </summary>
    public static Rune WeatherThermometerInternal => new(0xE34F);

    /// <summary>
    /// weather-thunderstorm.
    /// </summary>
    public static Rune WeatherThunderstorm => new(0xE31D);

    /// <summary>
    /// weather-time_1.
    /// </summary>
    public static Rune WeatherTime1 => new(0xE382);

    /// <summary>
    /// weather-time_10.
    /// </summary>
    public static Rune WeatherTime10 => new(0xE38B);

    /// <summary>
    /// weather-time_11.
    /// </summary>
    public static Rune WeatherTime11 => new(0xE38C);

    /// <summary>
    /// weather-time_12.
    /// </summary>
    public static Rune WeatherTime12 => new(0xE381);

    /// <summary>
    /// weather-time_2.
    /// </summary>
    public static Rune WeatherTime2 => new(0xE383);

    /// <summary>
    /// weather-time_3.
    /// </summary>
    public static Rune WeatherTime3 => new(0xE384);

    /// <summary>
    /// weather-time_4.
    /// </summary>
    public static Rune WeatherTime4 => new(0xE385);

    /// <summary>
    /// weather-time_5.
    /// </summary>
    public static Rune WeatherTime5 => new(0xE386);

    /// <summary>
    /// weather-time_6.
    /// </summary>
    public static Rune WeatherTime6 => new(0xE387);

    /// <summary>
    /// weather-time_7.
    /// </summary>
    public static Rune WeatherTime7 => new(0xE388);

    /// <summary>
    /// weather-time_8.
    /// </summary>
    public static Rune WeatherTime8 => new(0xE389);

    /// <summary>
    /// weather-time_9.
    /// </summary>
    public static Rune WeatherTime9 => new(0xE38A);

    /// <summary>
    /// weather-tornado.
    /// </summary>
    public static Rune WeatherTornado => new(0xE351);

    /// <summary>
    /// weather-train.
    /// </summary>
    public static Rune WeatherTrain => new(0xE3C3);

    /// <summary>
    /// weather-tsunami.
    /// </summary>
    public static Rune WeatherTsunami => new(0xE3BD);

    /// <summary>
    /// weather-umbrella.
    /// </summary>
    public static Rune WeatherUmbrella => new(0xE37C);

    /// <summary>
    /// weather-volcano.
    /// </summary>
    public static Rune WeatherVolcano => new(0xE3C0);

    /// <summary>
    /// weather-wind_beaufort_0.
    /// </summary>
    public static Rune WeatherWindBeaufort0 => new(0xE3AF);

    /// <summary>
    /// weather-wind_beaufort_1.
    /// </summary>
    public static Rune WeatherWindBeaufort1 => new(0xE3B0);

    /// <summary>
    /// weather-wind_beaufort_10.
    /// </summary>
    public static Rune WeatherWindBeaufort10 => new(0xE3B9);

    /// <summary>
    /// weather-wind_beaufort_11.
    /// </summary>
    public static Rune WeatherWindBeaufort11 => new(0xE3BA);

    /// <summary>
    /// weather-wind_beaufort_12.
    /// </summary>
    public static Rune WeatherWindBeaufort12 => new(0xE3BB);

    /// <summary>
    /// weather-wind_beaufort_2.
    /// </summary>
    public static Rune WeatherWindBeaufort2 => new(0xE3B1);

    /// <summary>
    /// weather-wind_beaufort_3.
    /// </summary>
    public static Rune WeatherWindBeaufort3 => new(0xE3B2);

    /// <summary>
    /// weather-wind_beaufort_4.
    /// </summary>
    public static Rune WeatherWindBeaufort4 => new(0xE3B3);

    /// <summary>
    /// weather-wind_beaufort_5.
    /// </summary>
    public static Rune WeatherWindBeaufort5 => new(0xE3B4);

    /// <summary>
    /// weather-wind_beaufort_6.
    /// </summary>
    public static Rune WeatherWindBeaufort6 => new(0xE3B5);

    /// <summary>
    /// weather-wind_beaufort_7.
    /// </summary>
    public static Rune WeatherWindBeaufort7 => new(0xE3B6);

    /// <summary>
    /// weather-wind_beaufort_8.
    /// </summary>
    public static Rune WeatherWindBeaufort8 => new(0xE3B7);

    /// <summary>
    /// weather-wind_beaufort_9.
    /// </summary>
    public static Rune WeatherWindBeaufort9 => new(0xE3B8);

    /// <summary>
    /// weather-wind_direction.
    /// </summary>
    public static Rune WeatherWindDirection => new(0xE3A9);

    /// <summary>
    /// weather-wind_east.
    /// </summary>
    public static Rune WeatherWindEast => new(0xE35B);

    /// <summary>
    /// weather-wind_north.
    /// </summary>
    public static Rune WeatherWindNorth => new(0xE35A);

    /// <summary>
    /// weather-wind_north_east.
    /// </summary>
    public static Rune WeatherWindNorthEast => new(0xE359);

    /// <summary>
    /// weather-wind_north_west.
    /// </summary>
    public static Rune WeatherWindNorthWest => new(0xE358);

    /// <summary>
    /// weather-wind_south.
    /// </summary>
    public static Rune WeatherWindSouth => new(0xE357);

    /// <summary>
    /// weather-wind_south_east.
    /// </summary>
    public static Rune WeatherWindSouthEast => new(0xE356);

    /// <summary>
    /// weather-wind_south_west.
    /// </summary>
    public static Rune WeatherWindSouthWest => new(0xE355);

    /// <summary>
    /// weather-wind_west.
    /// </summary>
    public static Rune WeatherWindWest => new(0xE354);

    /// <summary>
    /// weather-windy.
    /// </summary>
    public static Rune WeatherWindy => new(0xE31E);

}
