// <auto-generated />

using System.Text;

namespace XenoAtom.Terminal.UI;

public static partial class NerdFont
{
    /// <summary>
    /// indent-dotted_guide.
    /// </summary>
    public static Rune IndentDottedGuide => new(0xE621);

    /// <summary>
    /// indent-line.
    /// </summary>
    public static Rune IndentLine => new(0xE621);

}
