// <auto-generated />

using System.Text;

namespace XenoAtom.Terminal.UI;

public static partial class NerdFont
{
    /// <summary>
    /// extra-progress_empty_left.
    /// </summary>
    public static Rune ExtraProgressEmptyLeft => new(0xEE00);

    /// <summary>
    /// extra-progress_empty_mid.
    /// </summary>
    public static Rune ExtraProgressEmptyMid => new(0xEE01);

    /// <summary>
    /// extra-progress_empty_right.
    /// </summary>
    public static Rune ExtraProgressEmptyRight => new(0xEE02);

    /// <summary>
    /// extra-progress_full_left.
    /// </summary>
    public static Rune ExtraProgressFullLeft => new(0xEE03);

    /// <summary>
    /// extra-progress_full_mid.
    /// </summary>
    public static Rune ExtraProgressFullMid => new(0xEE04);

    /// <summary>
    /// extra-progress_full_right.
    /// </summary>
    public static Rune ExtraProgressFullRight => new(0xEE05);

    /// <summary>
    /// extra-progress_spinner_1.
    /// </summary>
    public static Rune ExtraProgressSpinner1 => new(0xEE06);

    /// <summary>
    /// extra-progress_spinner_2.
    /// </summary>
    public static Rune ExtraProgressSpinner2 => new(0xEE07);

    /// <summary>
    /// extra-progress_spinner_3.
    /// </summary>
    public static Rune ExtraProgressSpinner3 => new(0xEE08);

    /// <summary>
    /// extra-progress_spinner_4.
    /// </summary>
    public static Rune ExtraProgressSpinner4 => new(0xEE09);

    /// <summary>
    /// extra-progress_spinner_5.
    /// </summary>
    public static Rune ExtraProgressSpinner5 => new(0xEE0A);

    /// <summary>
    /// extra-progress_spinner_6.
    /// </summary>
    public static Rune ExtraProgressSpinner6 => new(0xEE0B);

}
