// Copyright (c) Alexandre Mutel. All rights reserved.
// Licensed under the BSD-Clause 2 license.
// See license.txt file in the project root for full license information.

// <auto-generated />

using System.IO.Compression;
using System.Text;

namespace XenoAtom.Terminal.UI.Figlet;

/// <summary>
/// Provides predefined FIGlet fonts embedded in the library.
/// </summary>
public static partial class FigletPredefinedFont
{
    internal static string Decompress(byte[] compressedData)
    {
        ArgumentNullException.ThrowIfNull(compressedData);
        if (compressedData.Length == 0)
        {
            return string.Empty;
        }

        // ZLibStream requires a stream input.
        // Holders cache the parsed FigletFont instance, so we only decompress once per font.
        using var input = new MemoryStream(compressedData, writable: false);
        using var zlib = new ZLibStream(input, CompressionMode.Decompress);

        using var output = new MemoryStream();
        zlib.CopyTo(output);

        return Encoding.UTF8.GetString(output.GetBuffer(), 0, (int)output.Length);
    }

    /// <summary>
    /// Gets all predefined FIGlet fonts embedded in this assembly (excluding <see cref="FigletFont.Block"/>).
    /// </summary>
    public static IReadOnlyList<FigletFont> GetFonts() =>
    [
        Banner3D,
        Big,
        Bubble,
        BulbHead,
        CyberLarge,
        CyberMedium,
        Digital,
        Doh,
        Doom,
        DotMatrix,
        Isometric1,
        Isometric2,
        Isometric3,
        Lcd,
        Ogre,
        Shadow,
        Slant,
        Small,
        Smslant,
        Standard,
        ThreeD,
        ThreeXFive,
    ];
}
