using System.IO.Compression;
using System.Net.Http.Headers;
using System.Text;

namespace FigletCodeGenApp;

internal static class Program
{
    public static int Main(string[] args)
    {
        try
        {
            return Run(args);
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine(ex);
            return 1;
        }
    }

    private static int Run(string[] args)
    {
        _ = args;

        var repoRoot = FindRepoRoot(Environment.CurrentDirectory);
        var artifactsDir = Path.Combine(repoRoot, "artifacts", "figlet-fonts");
        var outputDir = Path.Combine(repoRoot, "src", "XenoAtom.Terminal.UI", "Figlet");

        Directory.CreateDirectory(artifactsDir);
        Directory.CreateDirectory(outputDir);

        var fonts = GetFonts();

        GeneratePredefinedFontHelper(outputDir, fonts);

        using var http = CreateHttpClient();

        for (var i = 0; i < fonts.Length; i++)
        {
            var font = fonts[i];
            var localPath = Path.Combine(artifactsDir, font.FileName);
            if (!File.Exists(localPath))
            {
                DownloadFont(http, font.Url, localPath);
            }

            var rawBytes = File.ReadAllBytes(localPath);
            var compressedBytes = CompressZlib(rawBytes);
            GenerateFontDataFile(outputDir, font, compressedBytes);
        }

        Console.WriteLine($"Generated {fonts.Length} FIGlet fonts into '{outputDir}'.");
        return 0;
    }

    private static HttpClient CreateHttpClient()
    {
        var http = new HttpClient();
        http.DefaultRequestHeaders.UserAgent.Add(new ProductInfoHeaderValue("XenoAtom.Terminal.UI", "1.0"));
        http.Timeout = TimeSpan.FromSeconds(60);
        return http;
    }

    private static void DownloadFont(HttpClient http, string url, string localPath)
    {
        Console.WriteLine($"Downloading {url}");
        using var response = http.GetAsync(url, HttpCompletionOption.ResponseHeadersRead).GetAwaiter().GetResult();
        response.EnsureSuccessStatusCode();

        var bytes = response.Content.ReadAsByteArrayAsync().GetAwaiter().GetResult();
        File.WriteAllBytes(localPath, bytes);
    }

    private static byte[] CompressZlib(byte[] raw)
    {
        using var ms = new MemoryStream();
        using (var z = new ZLibStream(ms, CompressionLevel.Optimal, leaveOpen: true))
        {
            z.Write(raw, 0, raw.Length);
        }
        return ms.ToArray();
    }

    private static void GeneratePredefinedFontHelper(string outputDir, ReadOnlySpan<FigletFontSpec> fonts)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Copyright (c) Alexandre Mutel. All rights reserved.");
        sb.AppendLine("// Licensed under the BSD-Clause 2 license.");
        sb.AppendLine("// See license.txt file in the project root for full license information.");
        sb.AppendLine();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine();
        sb.AppendLine("using System.IO.Compression;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine();
        sb.AppendLine("namespace XenoAtom.Terminal.UI.Figlet;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Provides predefined FIGlet fonts embedded in the library.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static partial class FigletPredefinedFont");
        sb.AppendLine("{");
        sb.AppendLine("    internal static string Decompress(byte[] compressedData)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(compressedData);");
        sb.AppendLine("        if (compressedData.Length == 0)");
        sb.AppendLine("        {");
        sb.AppendLine("            return string.Empty;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        // ZLibStream requires a stream input.");
        sb.AppendLine("        // Holders cache the parsed FigletFont instance, so we only decompress once per font.");
        sb.AppendLine("        using var input = new MemoryStream(compressedData, writable: false);");
        sb.AppendLine("        using var zlib = new ZLibStream(input, CompressionMode.Decompress);");
        sb.AppendLine();
        sb.AppendLine("        using var output = new MemoryStream();");
        sb.AppendLine("        zlib.CopyTo(output);");
        sb.AppendLine();
        sb.AppendLine("        return Encoding.UTF8.GetString(output.GetBuffer(), 0, (int)output.Length);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets all predefined FIGlet fonts embedded in this assembly (excluding <see cref=\"FigletFont.Block\"/>).");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IReadOnlyList<FigletFont> GetFonts() =>");
        sb.AppendLine("    [");
        for (var i = 0; i < fonts.Length; i++)
        {
            sb.AppendLine($"        {fonts[i].PropertyName},");
        }
        sb.AppendLine("    ];");
        sb.AppendLine("}");

        File.WriteAllText(Path.Combine(outputDir, "FigletPredefinedFont.g.cs"), sb.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
    }

    private static void GenerateFontDataFile(string outputDir, FigletFontSpec font, byte[] compressedBytes)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Copyright (c) Alexandre Mutel. All rights reserved.");
        sb.AppendLine("// Licensed under the BSD-Clause 2 license.");
        sb.AppendLine("// See license.txt file in the project root for full license information.");
        sb.AppendLine();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine();
        sb.AppendLine("namespace XenoAtom.Terminal.UI.Figlet;");
        sb.AppendLine();
        sb.AppendLine("public static partial class FigletPredefinedFont");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Gets the {font.InfoName} FIGlet font used for rendering text in the FIGlet format. From {font.Url}.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static FigletFont {font.PropertyName} => {font.PropertyName}FontHolder.Instance;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Holds the {font.PropertyName} font instance for lazy initialization and NativeAOT friendliness.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    private static class {font.PropertyName}FontHolder");
        sb.AppendLine("    {");
        sb.AppendLine($"        // Compressed (ZLib) UTF8 bytes of {font.Url}");
        sb.AppendLine($"        private static readonly byte[] {font.PropertyName}FontDataBytes =");
        sb.AppendLine("        [");

        const int bytesPerLine = 32;
        for (var i = 0; i < compressedBytes.Length; i += bytesPerLine)
        {
            sb.Append("            ");
            var end = Math.Min(compressedBytes.Length, i + bytesPerLine);
            for (var j = i; j < end; j++)
            {
                sb.Append(compressedBytes[j]);
                sb.Append(j + 1 < end ? ", " : "");
            }
            sb.AppendLine(i + bytesPerLine < compressedBytes.Length ? "," : "");
        }

        sb.AppendLine("        ];");
        sb.AppendLine();
        sb.AppendLine($"        public static readonly FigletFont Instance = FigletFont.Parse(Decompress({font.PropertyName}FontDataBytes), new(\"{EscapeString(font.InfoName)}\", \"{EscapeString(font.Author)}\", \"{EscapeString(font.Url)}\"));");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        var fileName = $"FigletPredefinedFont.FontData.{font.PropertyName}.g.cs";
        File.WriteAllText(Path.Combine(outputDir, fileName), sb.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
    }

    private static string EscapeString(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string FindRepoRoot(string startDir)
    {
        var dir = new DirectoryInfo(startDir);
        while (dir is not null)
        {
            var slnx = Path.Combine(dir.FullName, "src", "XenoAtom.Terminal.UI.slnx");
            if (File.Exists(slnx))
            {
                return dir.FullName;
            }

            dir = dir.Parent;
        }

        throw new InvalidOperationException("Unable to locate repo root (expected src/XenoAtom.Terminal.UI.slnx).");
    }

    private readonly record struct FigletFontSpec(string PropertyName, string FileName, string InfoName, string Author, string Url);

    private static FigletFontSpec[] GetFonts() =>
    [
        new("Banner3D", "banner3-D.flf", "banner3-D", "Merlyn Greywolf", "https://www.figlet.org/fonts/banner3-D.flf"),
        new("Big", "big.flf", "Big", "Glenn Chappel", "https://www.figlet.org/fonts/big.flf"),
        new("Bubble", "bubble.flf", "Bubble", "Glenn Chappell", "https://www.figlet.org/fonts/bubble.flf"),
        new("BulbHead", "bulbhead.flf", "Bulbhead", "Jef Poskanzer", "https://www.figlet.org/fonts/bulbhead.flf"),
        new("CyberLarge", "cyberlarge.flf", "Cyberfont - Large", "Kent Nassen, Lennert Stock", "https://www.figlet.org/fonts/cyberlarge.flf"),
        new("CyberMedium", "cybermedium.flf", "Cyberfont - medium", "Kent Nassen, Lennert Stock", "https://www.figlet.org/fonts/cybermedium.flf"),
        new("Digital", "digital.flf", "Digital", "Glenn Chappell", "https://www.figlet.org/fonts/digital.flf"),
        new("Doh", "doh.flf", "doh", "Curtis Wanner", "https://www.figlet.org/fonts/doh.flf"),
        new("Doom", "doom.flf", "DOOM", "Frans P. de Vries", "https://www.figlet.org/fonts/doom.flf"),
        new("DotMatrix", "dotmatrix.flf", "dotmatrix", "Curtis Wanner", "https://www.figlet.org/fonts/dotmatrix.flf"),
        new("Isometric1", "isometric1.flf", "isometric1", "Kent Nassen, Lennert Stock", "https://www.figlet.org/fonts/isometric1.flf"),
        new("Isometric2", "isometric2.flf", "isometric2", "Kent Nassen, Lennert Stock", "https://www.figlet.org/fonts/isometric2.flf"),
        new("Isometric3", "isometric3.flf", "isometric3", "Kent Nassen, Lennert Stock", "https://www.figlet.org/fonts/isometric3.flf"),
        new("Lcd", "lcd.flf", "Lcd", "Karl von Laudermann", "https://www.figlet.org/fonts/lcd.flf"),
        new("Ogre", "ogre.flf", "Ogre", "Glenn Chappell, Frank Sheeran", "https://www.figlet.org/fonts/ogre.flf"),
        new("Shadow", "shadow.flf", "Shadow", "Glenn Chappell", "https://www.figlet.org/fonts/shadow.flf"),
        new("Slant", "slant.flf", "Slant", "Glenn Chappell", "https://www.figlet.org/fonts/slant.flf"),
        new("Small", "small.flf", "Small", "Glenn Chappell", "https://www.figlet.org/fonts/small.flf"),
        new("Smslant", "smslant.flf", "SmSlant", "Glenn Chappell", "https://www.figlet.org/fonts/smslant.flf"),
        new("Standard", "standard.flf", "Standard", "Glenn Chappell & Ian Chai", "https://www.figlet.org/fonts/standard.flf"),
        new("ThreeD", "3-d.flf", "3-D", "Daniel Henninger", "https://www.figlet.org/fonts/3-d.flf"),
        new("ThreeXFive", "3x5.flf", "3x5", "Richard Kirk", "https://www.figlet.org/fonts/3x5.flf"),
    ];
}
