<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="HarfBuzzSharp.NativeAssets.Linux" Version="8.3.1.5" />
    <PackageVersion Include="MinVer" Version="8.0.0" />
    <PackageVersion Include="Markdig" Version="1.4.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="5.0.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
    <PackageVersion Include="MSTest" Version="4.4.1" />
    <PackageVersion Include="SkiaSharp" Version="3.119.4" />
    <PackageVersion Include="SkiaSharp.HarfBuzz" Version="3.119.4" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Linux" Version="3.119.4" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Win32" Version="3.119.4" />
    <PackageVersion Include="TextMateSharp" Version="2.0.4" />
    <PackageVersion Include="TextMateSharp.Grammars" Version="2.0.4" />
    <PackageVersion Include="Verify.DiffPlex" Version="3.3.1" />
    <PackageVersion Include="Verify.MSTest" Version="33.1.1" />
    <PackageVersion Include="XenoAtom.Ansi" Version="1.7.1" />
    <PackageVersion Include="XenoAtom.Terminal" Version="2.2.0" />
    <PackageVersion Include="XenoAtom.Terminal.Graphics" Version="2.2.0" />
  </ItemGroup>
</Project>