# configuration file for dotnet-releaser
# Disable default packs - It will only publish NuGet and the Changelog
profile = "custom"
[msbuild]
project = "XenoAtom.Terminal.UI.slnx"
[github]
user = "XenoAtom"
repo = "XenoAtom.Terminal.UI"
[changelog]
owners = ["xoofx"] # To avoid to be mentioned in the changelog
[nuget]
user = "xoofx"
trusted_publishing = true
